import fs from 'node:fs';import path from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),exists=p=>fs.existsSync(path.join(root,p)),assert=(ok,msg)=>{if(!ok){console.error(`SMOKE FAIL: ${msg}`);process.exitCode=1}};
const required=['index.html','overhaul.css','quality.css','systems.css','mobile.css','manifest.webmanifest','src/app.js','src/game.js','src/config.js','src/data.js','src/i18n.js','src/mobile-controls.js','src/error-boundary.js','server/server.js'];for(const f of required)assert(exists(f),`missing required file ${f}`);
const forbidden=['src/app-v3.js','src/data-v2.js','src/game-v5.js','src/game-v6.js','src/game-v9.js','src/lobby-ai.js','src/lobby-ux.js','styles.css'];for(const f of forbidden)assert(!exists(f),`legacy file should be removed: ${f}`);
const html=read('index.html');for(const ref of ['overhaul.css','quality.css','systems.css','mobile.css','src/error-boundary.js','src/app.js','src/game.js','src/mobile-controls.js'])assert(html.includes(ref),`index.html does not reference ${ref}`);for(const m of html.matchAll(/(?:src|href)="([^"]+)"/g)){const ref=m[1];if(/^(https?:|data:|#)/.test(ref))continue;assert(exists(ref),`index reference does not exist: ${ref}`)}
const manifest=JSON.parse(read('manifest.webmanifest'));assert(manifest.name?.includes('RE:BUILDFRONT'),'manifest name is missing');assert(manifest.display==='standalone','manifest should use standalone display');
const [{SUPPORTED_LANGUAGES,STRINGS},{MAX_ROOM_PLAYERS,MAPS,ITEM_DEFS,RECIPES,starterInventory},{ZONES,AI_PLAYERS,BUILDINGS,RESEARCH,RESOURCES,NODE_TYPES}]=await Promise.all([import(pathToFileURL(path.join(root,'src/i18n.js'))),import(pathToFileURL(path.join(root,'src/data.js'))),import(pathToFileURL(path.join(root,'src/config.js')))]);
assert(JSON.stringify(SUPPORTED_LANGUAGES)===JSON.stringify(['en','ko','ja','zh']),'supported languages must be en/ko/ja/zh');for(const lang of SUPPORTED_LANGUAGES)assert(STRINGS[lang],`missing translation table ${lang}`);assert(STRINGS.ko.unready==='준비중','Korean unready state must read 준비중');assert(MAX_ROOM_PLAYERS===15,'room hard cap must be 15');for(const m of MAPS)assert(m.maxPlayers<=MAX_ROOM_PLAYERS,`map ${m.id} exceeds cap`);assert(ZONES.length>=6,'expected six resource zones');assert(AI_PLAYERS.length>=14,'AI roster must fill 15-player room');
for(const tier of ['wood','stone','copper','iron','crystal'])for(const suffix of ['Sword','Pickaxe','Axe']){const id=`${tier}${suffix}`,d=ITEM_DEFS[id];assert(d?.kind==='tool',`missing tool ${id}`);assert(Number.isFinite(d.damage)&&d.damage>0,`${id} damage invalid`);assert(Number.isFinite(d.cooldown)&&d.cooldown>0,`${id} cooldown invalid`);assert(Number.isFinite(d.gather)&&d.gather>0,`${id} gather multiplier invalid`)}
assert(ITEM_DEFS.hammer?.toolType==='hammer','hammer tool missing');for(const id of ['workbench','researchBench','wallItem','generatorItem','relayItem','depotItem'])assert(ITEM_DEFS[id],`missing structure item ${id}`);for(const id of ['wall','generator','relay','depot','workbench','researchBench'])assert(BUILDINGS[id],`missing building ${id}`);for(const [id,n] of Object.entries(NODE_TYPES))assert(['axe','pickaxe'].includes(n.tool),`node ${id} must declare gathering tool`);
for(const r of RECIPES){assert(ITEM_DEFS[r.out.id],`recipe ${r.id} has invalid output ${r.out.id}`);for(const id of Object.keys(r.ingredients))assert(ITEM_DEFS[id],`recipe ${r.id} has invalid ingredient ${id}`)}assert(RECIPES.some(r=>r.id==='researchBench'),'research bench recipe missing');assert(RECIPES.some(r=>r.id==='wallItem'),'wall item recipe missing');
const starter=starterInventory().filter(Boolean).map(s=>s.id);for(const id of ['woodSword','woodPickaxe','woodAxe','hammer','workbench'])assert(starter.includes(id),`starter inventory missing ${id}`);
for(const id of ['wallI','wallII','fortify','corePlating','powerGrid','fieldRepair','logistics','rescue','survey'])assert(RESEARCH[id],`missing research ${id}`);for(const r of Object.values(RESEARCH))assert(r.cost&&typeof r.cost==='object','research costs must be resource objects');
const app=read('src/app.js'),game=read('src/game.js'),server=read('server/server.js'),error=read('src/error-boundary.js');assert(app.includes('window.rbfModal'),'app must expose shared modal');assert(!/\b(confirm|alert)\s*\(/.test(app),'browser confirm/alert popups are forbidden');assert(app.includes('cancelStart')&&app.includes('cancelCountdown'),'lobby start countdown must be cancellable');assert(app.includes('data-nav="customize"'),'customization navigation missing');assert(error.includes('window.rbfModal'),'fatal errors must use shared modal');
for(const token of ['cursorStack','slotClick','quickMove','collectMatching','openCraft','recipeSearch','openResearch','research-tree','buildDock','toolPower','nodeSpawnClearance'])assert(game.includes(token),`game missing ${token}`);assert(game.includes("toolType!=='hammer'")&&game.includes('findStructureItem'),'building must require hammer and crafted structure item');assert(game.includes('safePoint')&&game.includes('WORLD.nodeSpawnClearance'),'resource respawn must avoid buildings');assert(game.includes('S.phaseTime=Math.max(0'),'wave timer must support overtime semantics');
assert(/\bMAX_PLAYERS\s*=\s*15\b/.test(server),'server room cap must be 15');assert(server.includes("socket.on('add-ai'")&&server.includes("socket.on('remove-ai'"),'server must support lobby AI slots');
if(!process.exitCode)console.log(`Smoke checks passed: ${required.length} files, ${Object.keys(ITEM_DEFS).length} items, ${RECIPES.length} recipes, ${Object.keys(RESEARCH).length} research nodes.`);
