import {createI18n,SUPPORTED_LANGUAGES} from './i18n.js';
import {MAPS,DIFFICULTIES,ROOM_SEED} from './data-v2.js';

const root=document.getElementById('appRoot'),gameRoot=document.getElementById('gameRoot');
const i18n=createI18n();
const state={page:'home',user:null,guestName:sessionStorage.getItem('rbf.guest')||`User${Math.floor(Math.random()*900+1)}`,rooms:ROOM_SEED.map(r=>({...r})),room:null,settings:{volume:Number(localStorage.getItem('rbf.volume')??.8),reducedMotion:localStorage.getItem('rbf.motion')==='reduced'},custom:{templates:JSON.parse(localStorage.getItem('rbf.templates')||'[]'),active:null,adUploadUnlocked:false}};
sessionStorage.setItem('rbf.guest',state.guestName);
const t=k=>i18n.t(k),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const currentName=()=>state.user?.username||state.guestName;

function topbar(){return `<header class="site-top"><div class="brand"><small>RERIDY PRESENTS</small><h1>RE:BUILDFRONT</h1></div><div class="auth-actions">${state.user?`<span>${esc(state.user.username)}</span><button class="btn" data-nav="account">${t('account')}</button>`:`<button class="btn" data-nav="login">${t('login')}</button><button class="btn primary" data-nav="signup">${t('signup')}</button>`}</div></header>`}
function shell(body){return `<main class="shell">${topbar()}${body}</main>`}
function bindNav(){root.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav))}
function navigate(page){state.page=page;render()}

function home(){return shell(`<div class="menu-grid"><button class="menu-tile" data-nav="play"><strong>${t('play')}</strong><span>Rooms · QuickPlay · Lobby</span></button><button class="menu-tile" data-nav="account"><strong>${t('account')}</strong><span>${state.user?esc(state.user.username):t('guest')}</span></button><button class="menu-tile" data-nav="customize"><strong>${t('customize')}</strong><span>Draw · Stickers · Templates</span></button><button class="menu-tile" data-nav="settings"><strong>${t('settings')}</strong><span>${t('language')} · ${t('volume')}</span></button></div>`)}
function sideNav(){return `<aside class="panel side-nav"><button class="btn" data-nav="home">RE:BUILDFRONT</button><button class="btn" data-nav="play">${t('play')}</button><button class="btn" data-nav="account">${t('account')}</button><button class="btn" data-nav="customize">${t('customize')}</button><button class="btn" data-nav="settings">${t('settings')}</button></aside>`}
function page(title,body){return shell(`<div class="page-grid">${sideNav()}<section class="panel content"><h2>${title}</h2>${body}</section></div>`)}

function playPage(){const cards=state.rooms.map(r=>`<div class="room-card"><div><b>${esc(r.name)}</b><small>${esc(r.description)} · ${r.map} · ${r.difficulty} · ${r.players}/${r.maxPlayers} · ${r.language.toUpperCase()}</small></div><button class="btn" data-join="${r.id}">${t('join')}</button></div>`).join('');return page(t('play'),`<div class="row"><button id="quickPlay" class="btn primary">${t('quickPlay')}</button><label><input id="sameLang" type="checkbox" checked> ${t('sameLanguage')}</label><button id="showCreate" class="btn">${t('createRoom')}</button></div><h3>${t('roomBrowser')}</h3><div class="room-list">${cards||'<p class="muted">No rooms.</p>'}</div><div id="createRoomPanel" class="panel hidden" style="margin-top:12px"><div class="form-grid"><div class="field"><label>${t('roomName')}</label><input id="roomName" maxlength="40"></div><div class="field"><label>${t('map')}</label><select id="roomMap">${MAPS.map(m=>`<option value="${m.id}">${m.name}</option>`).join('')}</select></div><div class="field"><label>${t('difficulty')}</label><select id="roomDifficulty">${DIFFICULTIES.map(d=>`<option value="${d}">${t('difficulty'+d[0].toUpperCase()+d.slice(1))}</option>`).join('')}</select></div><div class="field"><label>${t('players')}</label><input id="roomMax" type="number" min="1" max="15" value="4"></div><div class="field" style="grid-column:1/-1"><label>${t('description')}</label><textarea id="roomDesc" maxlength="160"></textarea></div></div><button id="createRoom" class="btn primary">${t('create')}</button></div>`)}
function bindPlay(){root.querySelector('#showCreate')?.addEventListener('click',()=>root.querySelector('#createRoomPanel').classList.toggle('hidden'));root.querySelectorAll('[data-join]').forEach(b=>b.onclick=()=>joinRoom(b.dataset.join));root.querySelector('#quickPlay')?.addEventListener('click',()=>{const same=root.querySelector('#sameLang').checked;const candidates=state.rooms.filter(r=>r.players<r.maxPlayers&&(!same||r.language===i18n.lang));const pick=candidates.sort((a,b)=>(b.players/b.maxPlayers)-(a.players/a.maxPlayers))[0]||state.rooms.find(r=>r.players<r.maxPlayers);if(pick)joinRoom(pick.id)});root.querySelector('#createRoom')?.addEventListener('click',()=>{const room={id:`local-${Date.now()}`,name:root.querySelector('#roomName').value.trim()||`${currentName()}'s room`,description:root.querySelector('#roomDesc').value.trim(),map:root.querySelector('#roomMap').value,difficulty:root.querySelector('#roomDifficulty').value,maxPlayers:Math.max(1,Math.min(15,Number(root.querySelector('#roomMax').value)||4)),players:1,language:i18n.lang,host:currentName(),members:[{name:currentName(),host:true,ready:true}]};state.rooms.unshift(room);state.room=room;navigate('lobby')})}
function joinRoom(id){const r=state.rooms.find(x=>x.id===id);if(!r)return;state.room={...r,host:r.host||'Host',members:r.members||[{name:r.host||'Host',host:true,ready:true},{name:currentName(),host:false,ready:false}]};navigate('lobby')}
function lobby(){const r=state.room;if(!r)return playPage();const self=r.members.find(m=>m.name===currentName()),isHost=self?.host;const allReady=r.members.filter(m=>!m.host).every(m=>m.ready);return page(esc(r.name),`<div class="lobby-grid"><div><div class="form-grid"><div class="field"><label>${t('roomName')}</label><input id="lobbyName" value="${esc(r.name)}" ${isHost?'':'disabled'}></div><div class="field"><label>${t('map')}</label><select id="lobbyMap" ${isHost?'':'disabled'}>${MAPS.map(m=>`<option value="${m.id}" ${m.id===r.map?'selected':''}>${m.name}</option>`).join('')}</select></div><div class="field"><label>${t('difficulty')}</label><select id="lobbyDiff" ${isHost?'':'disabled'}>${DIFFICULTIES.map(d=>`<option value="${d}" ${d===r.difficulty?'selected':''}>${d}</option>`).join('')}</select></div><div class="field" style="grid-column:1/-1"><label>${t('description')}</label><textarea id="lobbyDesc" ${isHost?'':'disabled'}>${esc(r.description)}</textarea></div></div>${isHost?`<button id="saveRoom" class="btn">${t('save')}</button>`:''}<p class="muted">${r.map} · ${r.difficulty} · ${r.language.toUpperCase()}</p></div><aside class="panel"><h3>${t('players')}</h3>${r.members.map(m=>`<div class="player-row"><span>${esc(m.name)} ${m.host?'★':''}</span><span class="${m.ready?'ready':''}">${m.host?t('host'):(m.ready?t('ready'):t('unready'))}</span></div>`).join('')}<div style="margin-top:12px">${isHost?`<button id="startGame" class="btn primary" ${allReady?'':'disabled'}>${t('startGame')}</button>${allReady?'':`<p class="muted">${t('waitingReady')}</p>`}`:`<button id="toggleReady" class="btn primary">${self?.ready?t('unready'):t('ready')}</button>`}</div></aside></div>`)}
function bindLobby(){const r=state.room;if(!r)return;const self=r.members.find(m=>m.name===currentName()),isHost=self?.host;root.querySelector('#toggleReady')?.addEventListener('click',()=>{self.ready=!self.ready;render()});root.querySelector('#saveRoom')?.addEventListener('click',()=>{r.name=root.querySelector('#lobbyName').value.trim()||r.name;r.description=root.querySelector('#lobbyDesc').value.trim();r.map=root.querySelector('#lobbyMap').value;r.difficulty=root.querySelector('#lobbyDiff').value;render()});root.querySelector('#startGame')?.addEventListener('click',()=>{if(!isHost||!r.members.filter(m=>!m.host).every(m=>m.ready))return;startGame(r)})}
function startGame(room){root.classList.add('hidden');gameRoot.classList.remove('hidden');window.dispatchEvent(new CustomEvent('rbf-start-game',{detail:{room,playerName:currentName(),language:i18n.lang,settings:state.settings,custom:state.custom.active}}))}

function authPage(mode){const signup=mode==='signup';return shell(`<div class="login-card panel"><button class="btn" data-nav="home">← ${t('back')}</button><h2>${signup?t('signup'):t('login')}</h2><div class="field"><label>Username</label><input id="authUser" autocomplete="username" maxlength="20"></div><div class="field"><label>Password</label><input id="authPass" type="password" autocomplete="${signup?'new-password':'current-password'}" minlength="8"></div><button id="authSubmit" class="btn primary">${signup?t('signup'):t('login')}</button><p id="authStatus" class="muted"></p><hr style="border-color:var(--line)"><button class="btn" data-nav="${signup?'login':'signup'}">${signup?t('login'):t('signup')}</button><p class="muted">Google / Discord linking is reserved in the account model and can be enabled when OAuth credentials are configured.</p></div>`)}
async function submitAuth(mode){const username=root.querySelector('#authUser').value.trim(),password=root.querySelector('#authPass').value,status=root.querySelector('#authStatus');if(username.length<3||password.length<8){status.textContent='Username 3+ / Password 8+';return}status.textContent='…';try{const res=await fetch(`/api/auth/${mode}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password,language:i18n.lang})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Request failed');state.user=data.user;sessionStorage.setItem('rbf.token',data.token);navigate('home')}catch(err){status.textContent=`Backend required: ${err.message}`}}
function accountPage(){return page(t('account'),state.user?`<p><b>${esc(state.user.username)}</b></p><p class="muted">Language: ${esc(state.user.language||i18n.lang)}</p><div class="row"><button id="logout" class="btn">${t('logout')}</button><button id="deleteAccount" class="btn danger">${t('deleteAccount')}</button></div>`:`<p>${t('accountRequired')}</p><div class="row"><button class="btn" data-nav="login">${t('login')}</button><button class="btn primary" data-nav="signup">${t('signup')}</button></div><p class="muted">${t('guest')}: ${esc(state.guestName)}</p>`)}
function bindAccount(){root.querySelector('#logout')?.addEventListener('click',()=>{state.user=null;sessionStorage.removeItem('rbf.token');render()});root.querySelector('#deleteAccount')?.addEventListener('click',async()=>{if(!confirm('Delete account?'))return;try{await fetch('/api/account',{method:'DELETE',headers:{Authorization:`Bearer ${sessionStorage.getItem('rbf.token')||''}`}})}catch{}state.user=null;sessionStorage.removeItem('rbf.token');render()})}

function customizePage(){const templates=state.custom.templates.map((x,i)=>`<button class="btn" data-template="${i}">Template ${i+1}</button>`).join('');return page(t('customize'),`<div class="custom-grid"><div class="draw-wrap"><canvas id="avatarCanvas" class="avatar-canvas" width="512" height="512"></canvas><p class="muted">Base: round character with two eyes. Draw freely or add stickers.</p></div><aside><h3>${t('newTemplate')}</h3><div class="sticker-grid">${['★','♥','⚙','✦','▲','●','◆','☁'].map(s=>`<button class="btn sticker" data-sticker="${s}">${s}</button>`).join('')}</div><div class="row" style="margin-top:10px"><input id="drawColor" type="color" value="#74d3ff"><button id="clearAvatar" class="btn">Clear</button><button id="saveAvatar" class="btn primary">${t('save')}</button></div><hr style="border-color:var(--line)"><button id="adUnlock" class="btn">${state.custom.adUploadUnlocked?t('uploadImage'):t('watchAd')}</button><input id="imageUpload" class="hidden" type="file" accept="image/png,image/jpeg,image/webp"><h3>Templates</h3><div class="row">${templates||'<span class="muted">No saved templates.</span>'}</div></aside></div>`)}
function bindCustomize(){const cv=root.querySelector('#avatarCanvas');if(!cv)return;const ctx=cv.getContext('2d');drawBase(ctx);let drawing=false;const pos=e=>{const r=cv.getBoundingClientRect();return{x:(e.clientX-r.left)*cv.width/r.width,y:(e.clientY-r.top)*cv.height/r.height}};cv.onpointerdown=e=>{drawing=true;const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y)};cv.onpointermove=e=>{if(!drawing)return;const p=pos(e);ctx.strokeStyle=root.querySelector('#drawColor').value;ctx.lineWidth=12;ctx.lineCap='round';ctx.lineTo(p.x,p.y);ctx.stroke()};window.addEventListener('pointerup',()=>drawing=false,{once:false});root.querySelectorAll('[data-sticker]').forEach(b=>b.onclick=()=>{ctx.font='72px sans-serif';ctx.textAlign='center';ctx.fillText(b.dataset.sticker,256,290)});root.querySelector('#clearAvatar').onclick=()=>drawBase(ctx);root.querySelector('#saveAvatar').onclick=()=>{const data=cv.toDataURL('image/png');state.custom.templates.push(data);state.custom.active=data;if(state.user)localStorage.setItem('rbf.templates',JSON.stringify(state.custom.templates));render()};root.querySelector('#adUnlock').onclick=async()=>{if(!state.custom.adUploadUnlocked){try{await fetch('/api/ad/reward',{method:'POST'});}catch{}state.custom.adUploadUnlocked=true;render();return}root.querySelector('#imageUpload').click()};root.querySelector('#imageUpload').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const img=new Image();img.onload=()=>{ctx.drawImage(img,96,96,320,320)};img.src=URL.createObjectURL(f)};root.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>{const data=state.custom.templates[Number(b.dataset.template)];state.custom.active=data;const img=new Image();img.onload=()=>{ctx.clearRect(0,0,512,512);ctx.drawImage(img,0,0)};img.src=data})}
function drawBase(ctx){ctx.clearRect(0,0,512,512);ctx.fillStyle='#dceaf5';ctx.beginPath();ctx.arc(256,256,150,0,Math.PI*2);ctx.fill();ctx.fillStyle='#15202b';ctx.beginPath();ctx.arc(210,230,16,0,Math.PI*2);ctx.arc(302,230,16,0,Math.PI*2);ctx.fill()}

function settingsPage(){return page(t('settings'),`<div class="settings-grid"><div class="field"><label>${t('volume')} <span id="volText">${Math.round(state.settings.volume*100)}%</span></label><input id="volume" type="range" min="0" max="1" step="0.01" value="${state.settings.volume}"></div><div class="field"><label>${t('language')}</label><select id="language">${SUPPORTED_LANGUAGES.map(l=>`<option value="${l}" ${l===i18n.lang?'selected':''}>${{en:'English',ko:'한국어',ja:'日本語',zh:'中文'}[l]}</option>`).join('')}</select></div><label><input id="motion" type="checkbox" ${state.settings.reducedMotion?'checked':''}> ${t('reducedMotion')}</label><button class="btn" data-nav="account">${t('account')}</button></div>`)}
function bindSettings(){root.querySelector('#volume')?.addEventListener('input',e=>{state.settings.volume=Number(e.target.value);localStorage.setItem('rbf.volume',state.settings.volume);root.querySelector('#volText').textContent=`${Math.round(state.settings.volume*100)}%`});root.querySelector('#language')?.addEventListener('change',e=>{i18n.set(e.target.value);render()});root.querySelector('#motion')?.addEventListener('change',e=>{state.settings.reducedMotion=e.target.checked;localStorage.setItem('rbf.motion',e.target.checked?'reduced':'full')})}

function render(){root.classList.remove('hidden');gameRoot.classList.add('hidden');if(state.page==='home')root.innerHTML=home();else if(state.page==='play')root.innerHTML=playPage();else if(state.page==='lobby')root.innerHTML=lobby();else if(state.page==='login'||state.page==='signup')root.innerHTML=authPage(state.page);else if(state.page==='account')root.innerHTML=accountPage();else if(state.page==='customize')root.innerHTML=customizePage();else if(state.page==='settings')root.innerHTML=settingsPage();bindNav();if(state.page==='play')bindPlay();if(state.page==='lobby')bindLobby();if(state.page==='login'||state.page==='signup')root.querySelector('#authSubmit').onclick=()=>submitAuth(state.page);if(state.page==='account')bindAccount();if(state.page==='customize')bindCustomize();if(state.page==='settings')bindSettings()}
window.addEventListener('rbf-language',render);window.addEventListener('rbf-exit-game',()=>navigate('play'));render();
