import {createI18n,SUPPORTED_LANGUAGES} from './i18n.js';
import {MAPS,DIFFICULTIES,ROOM_SEED,MAX_ROOM_PLAYERS} from './data.js';
const root=document.getElementById('appRoot'),gameRoot=document.getElementById('gameRoot'),i18n=createI18n();
const t=k=>i18n.t(k),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const X={
 en:{hero:'Build a world worth defending.',heroBody:'Explore, craft, build and defend HEART together.',leaveTitle:'Leave this room?',leaveBody:'You will leave the current room and lose its local lobby state.',stay:'Stay',leave:'Leave room',customError:'Customization could not be opened.',cancelStart:'Cancel start',starting:'Starting in',server:'Room service connected',local:'Local prototype',search:'Search rooms',max:'Max players',full:'Full',rewardFail:'Reward service is unavailable.',confirmDelete:'Delete this account?',ok:'OK'},
 ko:{hero:'지킬 가치가 있는 세계를 건설하라.',heroBody:'탐험하고 제작하고 건설하며 HEART를 함께 방어하세요.',leaveTitle:'방에서 나가시겠습니까?',leaveBody:'현재 방에서 나가며 이 브라우저의 로비 상태가 사라집니다.',stay:'취소',leave:'방 나가기',customError:'커스터마이즈 메뉴를 열 수 없습니다.',cancelStart:'게임 시작 중단',starting:'게임 시작까지',server:'방 서버 연결됨',local:'로컬 프로토타입',search:'방 검색',max:'최대 인원',full:'가득 참',rewardFail:'광고 보상 서버에 연결할 수 없습니다.',confirmDelete:'계정을 삭제하시겠습니까?',ok:'확인'},
 ja:{hero:'守る価値のある世界を築こう。',heroBody:'探索・クラフト・建築し、HEARTを守ろう。',leaveTitle:'ルームから退出しますか？',leaveBody:'現在のロビー状態は失われます。',stay:'キャンセル',leave:'退出',customError:'カスタマイズを開けません。',cancelStart:'開始を中止',starting:'開始まで',server:'サーバー接続済み',local:'ローカル',search:'ルーム検索',max:'最大人数',full:'満員',rewardFail:'報酬サービスに接続できません。',confirmDelete:'アカウントを削除しますか？',ok:'OK'},
 zh:{hero:'建造一个值得守护的世界。',heroBody:'探索、制作、建造并共同守护HEART。',leaveTitle:'离开房间？',leaveBody:'当前本地大厅状态将丢失。',stay:'取消',leave:'离开',customError:'无法打开自定义菜单。',cancelStart:'取消开始',starting:'开始倒计时',server:'房间服务已连接',local:'本地原型',search:'搜索房间',max:'最大人数',full:'已满',rewardFail:'无法连接奖励服务。',confirmDelete:'删除账户？',ok:'确定'}
};
const x=k=>X[i18n.lang]?.[k]??X.en[k]??t(k),parse=(v,d)=>{try{return JSON.parse(v)}catch{return d}};
const guest=sessionStorage.getItem('rbf.guest')||`User${Math.floor(Math.random()*900+100)}`;sessionStorage.setItem('rbf.guest',guest);
const state={page:'home',user:parse(sessionStorage.getItem('rbf.user'),null),guestName:guest,rooms:[],room:parse(sessionStorage.getItem('rbf.room'),null),backend:false,countdown:null,settings:{volume:Number(localStorage.getItem('rbf.volume')??.8),reducedMotion:localStorage.getItem('rbf.motion')==='reduced',showTips:localStorage.getItem('rbf.tips')!=='off',highContrast:localStorage.getItem('rbf.contrast')==='high'},custom:{templates:parse(localStorage.getItem('rbf.templates'),[]),active:localStorage.getItem('rbf.activeAvatar')||null,uploadUnlocked:false}};
if(state.room)state.page='lobby';const name=()=>state.user?.username||state.guestName;
function persist(){state.room?sessionStorage.setItem('rbf.room',JSON.stringify(state.room)):sessionStorage.removeItem('rbf.room')}
function cancelCountdown(renderNow=true){if(state.countdown){clearInterval(state.countdown.timer);state.countdown=null}if(renderNow&&state.page==='lobby')render()}
function clearRoom(){cancelCountdown(false);state.room=null;persist()}
function prefs(){document.body.classList.toggle('reduce-motion',state.settings.reducedMotion);document.body.classList.toggle('high-contrast',state.settings.highContrast)}prefs();
async function backend(){const c=new AbortController(),timer=setTimeout(()=>c.abort(),900);try{state.backend=(await fetch('/health',{signal:c.signal,cache:'no-store'})).ok}catch{state.backend=false}finally{clearTimeout(timer)}return state.backend}
window.rbfModal=function({title,body='',primary=x('ok'),secondary='',danger=false,onPrimary,onSecondary}={}){return new Promise(resolve=>{document.getElementById('rbfModal')?.remove();const box=document.createElement('div');box.id='rbfModal';box.className='app-modal';box.innerHTML=`<div class="overlay-card"><h2>${esc(title||'')}</h2><p>${esc(body)}</p><div class="row">${secondary?`<button class="btn" data-m="secondary">${esc(secondary)}</button>`:''}<button class="btn ${danger?'danger':'primary'}" data-m="primary">${esc(primary)}</button></div></div>`;document.body.appendChild(box);const done=(v)=>{box.remove();resolve(v);if(v)onPrimary?.();else onSecondary?.()};box.querySelector('[data-m="primary"]').onclick=()=>done(true);box.querySelector('[data-m="secondary"]')?.addEventListener('click',()=>done(false))})};
const top=()=>`<header class="site-top"><button class="brand brand-button" data-nav="home"><small>RERIDY PRESENTS</small><strong>RE:BUILDFRONT</strong></button><div class="auth-actions">${state.room?`<span class="status-pill active">● ${esc(state.room.name)}</span>`:''}${state.user?`<span>${esc(state.user.username)}</span><button class="btn" data-nav="account">${t('account')}</button>`:`<button class="btn" data-nav="login">${t('login')}</button><button class="btn primary" data-nav="signup">${t('signup')}</button>`}</div></header>`;
const shell=b=>`<main class="shell">${top()}${b}</main>`,side=()=>`<aside class="panel side-nav"><button class="btn" data-nav="home">RE:BUILDFRONT</button><button class="btn" data-nav="play">${t('play')}</button><button class="btn" data-nav="account">${t('account')}</button><button class="btn" data-nav="customize">${t('customize')}</button><button class="btn" data-nav="settings">${t('settings')}</button></aside>`,page=(title,b)=>shell(`<div class="page-grid">${side()}<section class="panel content"><h2>${title}</h2>${b}</section></div>`);
async function leaveThen(p){if(!state.room){state.page=p;return render()}const yes=await window.rbfModal({title:x('leaveTitle'),body:x('leaveBody'),primary:x('leave'),secondary:x('stay'),danger:true});if(!yes)return;clearRoom();state.page=p;render()}
function go(p){if(state.room&&p==='play')p='lobby';if(state.room&&['home','account','settings','login','signup'].includes(p))return leaveThen(p);state.page=p;render()}
function nav(){root.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>go(b.dataset.nav))}
function home(){return shell(`<section class="hero panel"><div><span class="eyebrow">BUILD • CRAFT • DEFEND</span><h1>${x('hero')}</h1><p>${x('heroBody')}</p><button class="btn primary hero-cta" data-nav="${state.room?'lobby':'play'}">${state.room?'방으로 돌아가기':t('play')}</button></div><div class="hero-mark">RE</div></section><div class="menu-grid"><button class="menu-tile" data-nav="play"><span class="tile-icon">▶</span><strong>${t('play')}</strong></button><button class="menu-tile" data-nav="account"><span class="tile-icon">◎</span><strong>${t('account')}</strong></button><button class="menu-tile" data-nav="customize"><span class="tile-icon">✦</span><strong>${t('customize')}</strong></button><button class="menu-tile" data-nav="settings"><span class="tile-icon">⚙</span><strong>${t('settings')}</strong></button></div>`)}
async function loadRooms(){if(await backend())try{const r=await fetch('/api/rooms',{cache:'no-store'});if(r.ok){state.rooms=await r.json();return}}catch{}state.rooms=ROOM_SEED.map(r=>({...r}))}
function cards(q='',d='all'){const a=state.rooms.filter(r=>(!q||`${r.name} ${r.description}`.toLowerCase().includes(q.toLowerCase()))&&(d==='all'||r.difficulty===d));return a.length?a.map(r=>`<article class="room-card"><div><b>${esc(r.name)}</b><p>${esc(r.description||'—')}</p><small>${r.players}/${r.maxPlayers} · ${r.difficulty} · ${String(r.language||'en').toUpperCase()}</small></div><button class="btn ${r.players>=r.maxPlayers?'':'primary'}" data-join="${r.id}" ${r.players>=r.maxPlayers?'disabled':''}>${r.players>=r.maxPlayers?x('full'):t('join')}</button></article>`).join(''):`<div class="empty-state">${t('noRooms')}</div>`}
function play(){return page(t('play'),`<div class="play-toolbar"><button id="quick" class="btn primary">${t('quickPlay')}</button><button id="createToggle" class="btn">+ ${t('createRoom')}</button><span class="status-pill">${state.backend?x('server'):x('local')}</span></div><div class="room-filters"><input id="roomSearch" class="input" placeholder="${x('search')}"><select id="diffFilter" class="input"><option value="all">All</option>${DIFFICULTIES.map(d=>`<option>${d}</option>`).join('')}</select></div><div id="roomList" class="room-list">${cards()}</div><section id="createPanel" class="panel create-panel hidden"><div class="form-grid"><div class="field"><label>${t('roomName')}</label><input id="roomName"></div><div class="field"><label>${t('map')}</label><select id="roomMap">${MAPS.map(m=>`<option value="${m.id}">${m.name}</option>`).join('')}</select></div><div class="field"><label>${t('difficulty')}</label><select id="roomDiff">${DIFFICULTIES.map(d=>`<option>${d}</option>`).join('')}</select></div><div class="field"><label>${x('max')}</label><input id="roomMax" type="number" min="1" max="15" value="4"></div><div class="field span-2"><label>${t('description')}</label><textarea id="roomDesc"></textarea></div></div><button id="createRoom" class="btn primary">${t('create')}</button></section>`)}
function makeRoom(r){return{...r,host:name(),members:[{name:name(),host:true,ready:true,ai:false}],aiCount:0,chat:[],players:1}}
async function createRoom(){const max=Math.max(1,Math.min(MAX_ROOM_PLAYERS,Math.round(Number(root.querySelector('#roomMax').value)||4))),body={name:root.querySelector('#roomName').value.trim()||`${name()}'s room`,description:root.querySelector('#roomDesc').value.trim(),map:root.querySelector('#roomMap').value,difficulty:root.querySelector('#roomDiff').value,maxPlayers:max,language:i18n.lang};let raw={id:`local-${Date.now()}`,...body,players:1};if(state.backend)try{const r=await fetch('/api/rooms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(r.ok)raw=await r.json()}catch{}state.room=makeRoom(raw);persist();state.page='lobby';render()}
function join(id){const r=state.rooms.find(x=>x.id===id);if(!r||r.players>=r.maxPlayers)return;state.room={...r,host:r.hostName||'Host',members:[{name:r.hostName||'Host',host:true,ready:true,ai:false},{name:name(),host:false,ready:false,ai:false}],aiCount:0,chat:[]};persist();state.page='lobby';render()}
function bindPlay(){root.querySelector('#createToggle').onclick=()=>root.querySelector('#createPanel').classList.toggle('hidden');root.querySelector('#createRoom').onclick=createRoom;const refresh=()=>{root.querySelector('#roomList').innerHTML=cards(root.querySelector('#roomSearch').value,root.querySelector('#diffFilter').value);root.querySelectorAll('[data-join]').forEach(b=>b.onclick=()=>join(b.dataset.join))};root.querySelector('#roomSearch').oninput=refresh;root.querySelector('#diffFilter').onchange=refresh;root.querySelector('#quick').onclick=()=>{const r=state.rooms.find(r=>r.players<r.maxPlayers);if(r)join(r.id)};refresh()}
const humans=()=>state.room?.members?.filter(m=>!m.ai)||[];function syncAI(){const r=state.room,real=humans();if(!r)return;r.aiCount=Math.max(0,Math.min(r.aiCount||0,14,r.maxPlayers-real.length));r.members=[...real,...Array.from({length:r.aiCount},(_,i)=>({name:['MIKA','RON','EVE','NOVA','ALTO','KITE','LYRA','PICO','ARIA','NOX','MILO','LUMA','ORBIT','TESS'][i],ready:true,ai:true}))];r.players=r.members.length;persist()}
const allReady=()=>humans().filter(m=>!m.host).every(m=>m.ready);
function lobby(){const r=state.room;if(!r)return play();syncAI();const self=humans().find(m=>m.name===name()),host=!!self?.host;return page(esc(r.name),`<div class="lobby-grid"><section><div class="lobby-status"><span class="badge">${esc(r.id)}</span><span class="badge">${r.members.length}/${r.maxPlayers}</span></div><div class="form-grid"><div class="field"><label>${t('roomName')}</label><input id="lName" value="${esc(r.name)}" ${host?'':'disabled'}></div><div class="field"><label>${t('map')}</label><select id="lMap" ${host?'':'disabled'}>${MAPS.map(m=>`<option value="${m.id}" ${m.id===r.map?'selected':''}>${m.name}</option>`).join('')}</select></div><div class="field"><label>${t('difficulty')}</label><select id="lDiff" ${host?'':'disabled'}>${DIFFICULTIES.map(d=>`<option ${d===r.difficulty?'selected':''}>${d}</option>`).join('')}</select></div><div class="field"><label>${x('max')}</label><input id="lMax" type="number" min="1" max="15" value="${r.maxPlayers}" ${host?'':'disabled'}></div></div>${host?`<button id="saveRoom" class="btn">${t('save')}</button>`:''}<section class="panel lobby-chat"><h3>${t('chat')}</h3><div id="lobbyChatLog" class="chat-log">${(r.chat||[]).slice(-30).map(m=>`<div class="chat-row"><b>${esc(m.name)}</b><span>${esc(m.text)}</span></div>`).join('')}</div><div class="row"><input id="lobbyChatInput" class="input"><button id="lobbyChatSend" class="btn">${t('send')}</button></div></section><button id="leaveRoom" class="btn danger">${x('leave')}</button></section><aside class="panel lobby-people"><h3>${t('players')}</h3>${r.members.map(m=>`<div class="player-row"><span>${esc(m.name)} ${m.host?'★':''}${m.ai?' · AI':''}</span><span class="${m.ready?'ready':''}">${m.host?t('host'):(m.ready?t('ready'):t('unready'))}</span></div>`).join('')}${host?`<div class="row"><button id="addAI" class="btn">+ AI</button><button id="removeAI" class="btn">− AI</button></div>`:''}<div class="lobby-start">${host?`<button id="startGame" class="btn primary" ${allReady()?'':'disabled'}>${t('startGame')}</button><button id="cancelStart" class="btn danger hidden">${x('cancelStart')}</button>`:`<button id="readyBtn" class="btn primary">${self?.ready?'준비 취소':t('ready')}</button>`}<div id="countdown" class="countdown hidden"></div></div></aside></div>`)}
function startCountdown(){if(state.countdown||!allReady())return;let left=5;const tick=()=>{const c=root.querySelector('#countdown'),s=root.querySelector('#startGame'),cancel=root.querySelector('#cancelStart');if(!c||!s)return;c.classList.remove('hidden');cancel?.classList.remove('hidden');c.textContent=`${x('starting')} ${left}`;s.textContent=String(left);s.disabled=true};tick();const timer=setInterval(()=>{left--;if(left<=0){clearInterval(timer);state.countdown=null;startGame()}else tick()},1000);state.countdown={timer}}
function bindLobby(){const r=state.room,self=humans().find(m=>m.name===name()),host=!!self?.host;root.querySelector('#leaveRoom').onclick=()=>leaveThen('play');root.querySelector('#readyBtn')?.addEventListener('click',()=>{self.ready=!self.ready;persist();render()});root.querySelector('#addAI')?.addEventListener('click',()=>{r.aiCount++;syncAI();render()});root.querySelector('#removeAI')?.addEventListener('click',()=>{r.aiCount=Math.max(0,r.aiCount-1);syncAI();render()});root.querySelector('#saveRoom')?.addEventListener('click',()=>{r.name=root.querySelector('#lName').value.trim()||r.name;r.map=root.querySelector('#lMap').value;r.difficulty=root.querySelector('#lDiff').value;r.maxPlayers=Math.max(r.members.length,Math.min(MAX_ROOM_PLAYERS,Math.round(Number(root.querySelector('#lMax').value)||r.maxPlayers)));syncAI();render()});root.querySelector('#startGame')?.addEventListener('click',startCountdown);root.querySelector('#cancelStart')?.addEventListener('click',()=>cancelCountdown());const send=()=>{const input=root.querySelector('#lobbyChatInput'),v=input.value.trim();if(!v)return;r.chat=r.chat||[];r.chat.push({name:name(),text:v.slice(0,180)});persist();render()};root.querySelector('#lobbyChatSend').onclick=send;root.querySelector('#lobbyChatInput').onkeydown=e=>{if(e.key==='Enter')send()}}
function startGame(){if(!state.room)return;root.classList.add('hidden');gameRoot.classList.remove('hidden');window.dispatchEvent(new CustomEvent('rbf-start-game',{detail:{room:{...state.room,aiCount:state.room.aiCount||0},playerName:name(),language:i18n.lang,settings:state.settings,custom:state.custom.active}}))}
function authPage(mode){return page(mode==='signup'?t('signup'):t('login'),`<div class="login-card"><input id="authUser" class="input" placeholder="${t('username')}"><input id="authPass" class="input" type="password" placeholder="${t('password')}"><button id="authSubmit" class="btn primary">${mode==='signup'?t('signup'):t('login')}</button><p id="authStatus"></p></div>`)}
async function authSubmit(mode){const u=root.querySelector('#authUser').value.trim(),p=root.querySelector('#authPass').value,status=root.querySelector('#authStatus');try{const r=await fetch(`/api/auth/${mode}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u,password:p,language:i18n.lang})}),d=await r.json();if(!r.ok)throw 0;state.user=d.user;sessionStorage.setItem('rbf.user',JSON.stringify(d.user));sessionStorage.setItem('rbf.token',d.token);go('home')}catch{status.textContent=t('backendRequired')}}
function account(){return page(t('account'),state.user?`<h3>${esc(state.user.username)}</h3><div class="row"><button id="logout" class="btn">${t('logout')}</button><button id="deleteAccount" class="btn danger">${t('deleteAccount')}</button></div>`:`<div class="empty-state">${t('accountRequired')}</div>`)}
function bindAccount(){root.querySelector('#logout')?.addEventListener('click',()=>{state.user=null;sessionStorage.removeItem('rbf.user');sessionStorage.removeItem('rbf.token');render()});root.querySelector('#deleteAccount')?.addEventListener('click',async()=>{const yes=await window.rbfModal({title:x('confirmDelete'),primary:t('delete'),secondary:x('stay'),danger:true});if(!yes)return;try{await fetch('/api/account',{method:'DELETE',headers:{Authorization:`Bearer ${sessionStorage.getItem('rbf.token')||''}`}})}catch{}state.user=null;sessionStorage.clear();render()})}
function customize(){return page(t('customize'),`<div class="custom-grid"><div class="draw-wrap"><canvas id="avatarCanvas" class="avatar-canvas" width="512" height="512"></canvas></div><aside><div class="row"><input id="drawColor" type="color" value="#74d3ff"><button id="clearAvatar" class="btn">${t('clear')}</button><button id="saveAvatar" class="btn primary">${t('save')}</button></div><div class="sticker-grid">${['★','♥','⚙','✦','▲','●','◆','☁'].map(s=>`<button class="btn sticker" data-sticker="${s}">${s}</button>`).join('')}</div><button id="uploadUnlock" class="btn full">${state.custom.uploadUnlocked?t('uploadImage'):t('watchAd')}</button>${state.room?`<button class="btn primary full" data-nav="lobby">방으로 돌아가기</button>`:''}</aside></div>`)}
function bindCustomize(){try{const cv=root.querySelector('#avatarCanvas'),c=cv.getContext('2d');if(!c)throw new Error('canvas context unavailable');c.fillStyle='#dceaf5';c.beginPath();c.arc(256,256,150,0,Math.PI*2);c.fill();if(state.custom.active){const img=new Image();img.onload=()=>c.drawImage(img,0,0,512,512);img.src=state.custom.active}let draw=false,sticker='';const pos=e=>{const r=cv.getBoundingClientRect();return{x:(e.clientX-r.left)*512/r.width,y:(e.clientY-r.top)*512/r.height}};cv.onpointerdown=e=>{const p=pos(e);if(sticker){c.font='72px sans-serif';c.textAlign='center';c.fillText(sticker,p.x,p.y);sticker='';return}draw=true;c.beginPath();c.moveTo(p.x,p.y)};cv.onpointermove=e=>{if(!draw)return;const p=pos(e);c.strokeStyle=root.querySelector('#drawColor').value;c.lineWidth=12;c.lineCap='round';c.lineTo(p.x,p.y);c.stroke()};cv.onpointerup=()=>draw=false;cv.onpointerleave=()=>draw=false;root.querySelectorAll('[data-sticker]').forEach(b=>b.onclick=()=>sticker=b.dataset.sticker);root.querySelector('#clearAvatar').onclick=()=>c.clearRect(0,0,512,512);root.querySelector('#saveAvatar').onclick=()=>{state.custom.active=cv.toDataURL('image/png');localStorage.setItem('rbf.activeAvatar',state.custom.active)};root.querySelector('#uploadUnlock').onclick=async()=>{if(state.custom.uploadUnlocked)return;try{const r=await fetch('/api/ad/reward',{method:'POST'});if(!r.ok)throw 0;state.custom.uploadUnlocked=true;render()}catch{window.rbfModal({title:x('rewardFail')})}}}catch(err){console.error(err);window.rbfModal({title:x('customError'),body:String(err?.message||err)})}}
function settings(){return page(t('settings'),`<div class="settings-grid"><label>${t('volume')} <input id="volume" type="range" min="0" max="1" step=".01" value="${state.settings.volume}"></label><select id="language">${SUPPORTED_LANGUAGES.map(l=>`<option value="${l}" ${l===i18n.lang?'selected':''}>${l.toUpperCase()}</option>`).join('')}</select><label><input id="motion" type="checkbox" ${state.settings.reducedMotion?'checked':''}> ${t('reducedMotion')}</label><label><input id="contrast" type="checkbox" ${state.settings.highContrast?'checked':''}> High contrast</label></div>`)}
function bindSettings(){root.querySelector('#volume').oninput=e=>{state.settings.volume=Number(e.target.value);localStorage.setItem('rbf.volume',state.settings.volume)};root.querySelector('#language').onchange=e=>i18n.set(e.target.value);root.querySelector('#motion').onchange=e=>{state.settings.reducedMotion=e.target.checked;localStorage.setItem('rbf.motion',e.target.checked?'reduced':'full');prefs()};root.querySelector('#contrast').onchange=e=>{state.settings.highContrast=e.target.checked;localStorage.setItem('rbf.contrast',e.target.checked?'high':'normal');prefs()}}
async function render(){root.classList.remove('hidden');gameRoot.classList.add('hidden');if(['home','play'].includes(state.page))await backend();if(state.page==='play')await loadRooms();root.innerHTML=state.page==='home'?home():state.page==='play'?play():state.page==='lobby'?lobby():state.page==='account'?account():state.page==='customize'?customize():state.page==='settings'?settings():authPage(state.page);nav();if(state.page==='play')bindPlay();if(state.page==='lobby')bindLobby();if(state.page==='account')bindAccount();if(state.page==='customize')bindCustomize();if(state.page==='settings')bindSettings();if(['login','signup'].includes(state.page))root.querySelector('#authSubmit').onclick=()=>authSubmit(state.page);prefs()}
window.addEventListener('rbf-language',render);window.addEventListener('rbf-return-lobby',()=>{state.page=state.room?'lobby':'play';render()});window.addEventListener('rbf-leave-room',()=>{clearRoom();state.page='play';render()});render();
