import {createI18n,SUPPORTED_LANGUAGES} from './i18n.js';
import {MAPS,DIFFICULTIES,ROOM_SEED,MAX_ROOM_PLAYERS} from './data.js';
const root=document.getElementById('appRoot'),gameRoot=document.getElementById('gameRoot'),i18n=createI18n();
const base=k=>i18n.t(k),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const EXTRA={
 en:{hero:'Build a world worth defending.',heroBody:'Explore distinct regions, recover resources, fortify HEART and survive together.',continueRoom:'Return to room',searchRooms:'Search rooms',allDifficulties:'All difficulties',maxPlayers:'Max players',maxNotice:'Maximum players is 15.',server:'Room service connected',local:'Local prototype',leaveWarn:'You will leave the room. Continue?',leave:'Leave room',chat:'Lobby chat',send:'Send',addAI:'Add AI',removeAI:'Remove AI',auto:'Auto ready',code:'Room code',copy:'Copy',copied:'Copied',starting:'Starting in',full:'Full',tips:'Show gameplay tips',contrast:'High contrast',roomSaved:'Room settings saved',cancelReady:'Cancel ready',rewardUnavailable:'Reward service is unavailable.'},
 ko:{hero:'지킬 가치가 있는 세계를 건설하라.',heroBody:'서로 다른 구역을 탐험하고 자원을 회수해 HEART를 요새화한 뒤 함께 침공을 버티세요.',continueRoom:'방으로 돌아가기',searchRooms:'방 검색',allDifficulties:'모든 난이도',maxPlayers:'최대 인원',maxNotice:'최대 인원은 15명입니다.',server:'방 서버 연결됨',local:'로컬 프로토타입',leaveWarn:'방에서 나가게 됩니다. 계속하시겠습니까?',leave:'방 나가기',chat:'방 채팅',send:'보내기',addAI:'AI 플레이어 추가',removeAI:'AI 제거',auto:'자동 준비 완료',code:'방 코드',copy:'복사',copied:'복사됨',starting:'게임 시작까지',full:'가득 참',tips:'게임 도움말 표시',contrast:'고대비 UI',roomSaved:'방 설정이 저장되었습니다.',cancelReady:'준비 취소',rewardUnavailable:'광고 보상 서버에 연결할 수 없습니다.'},
 ja:{hero:'守る価値のある世界を築こう。',heroBody:'地域を探索し、資源を回収してHEARTを要塞化し、仲間と襲撃を生き延びよう。',continueRoom:'ルームへ戻る',searchRooms:'ルーム検索',allDifficulties:'すべての難易度',maxPlayers:'最大人数',maxNotice:'最大人数は15人です。',server:'ルームサービス接続済み',local:'ローカルプロトタイプ',leaveWarn:'ルームから退出します。続けますか？',leave:'ルーム退出',chat:'ロビーチャット',send:'送信',addAI:'AIを追加',removeAI:'AIを削除',auto:'自動準備完了',code:'ルームコード',copy:'コピー',copied:'コピーしました',starting:'ゲーム開始まで',full:'満員',tips:'ゲームヒントを表示',contrast:'ハイコントラスト',roomSaved:'ルーム設定を保存しました。',cancelReady:'準備解除',rewardUnavailable:'広告報酬サービスに接続できません。'},
 zh:{hero:'建造一个值得守护的世界。',heroBody:'探索不同区域、回收资源、强化HEART，并与队友共同抵御入侵。',continueRoom:'返回房间',searchRooms:'搜索房间',allDifficulties:'全部难度',maxPlayers:'最大人数',maxNotice:'最大人数为15人。',server:'房间服务已连接',local:'本地原型',leaveWarn:'你将离开房间。是否继续？',leave:'离开房间',chat:'房间聊天',send:'发送',addAI:'添加AI',removeAI:'移除AI',auto:'自动准备',code:'房间代码',copy:'复制',copied:'已复制',starting:'游戏开始倒计时',full:'已满',tips:'显示游戏提示',contrast:'高对比度',roomSaved:'房间设置已保存。',cancelReady:'取消准备',rewardUnavailable:'无法连接广告奖励服务。'}
};
const lang=()=>i18n.lang,tx=k=>EXTRA[lang()]?.[k]??EXTRA.en[k]??base(k),parse=(v,d)=>{try{return JSON.parse(v)}catch{return d}};
const guest=sessionStorage.getItem('rbf.guest')||`User${Math.floor(Math.random()*900+100)}`;sessionStorage.setItem('rbf.guest',guest);
const state={page:'home',user:parse(sessionStorage.getItem('rbf.user'),null),guestName:guest,rooms:[],room:parse(sessionStorage.getItem('rbf.room'),null),backend:false,settings:{volume:Number(localStorage.getItem('rbf.volume')??.8),reducedMotion:localStorage.getItem('rbf.motion')==='reduced',showTips:localStorage.getItem('rbf.tips')!=='off',highContrast:localStorage.getItem('rbf.contrast')==='high'},custom:{templates:parse(localStorage.getItem('rbf.templates'),[]),active:localStorage.getItem('rbf.activeAvatar')||null,uploadUnlocked:false},countdown:null};
if(state.room)state.page='lobby';
const name=()=>state.user?.username||state.guestName;
function persistRoom(){state.room?sessionStorage.setItem('rbf.room',JSON.stringify(state.room)):sessionStorage.removeItem('rbf.room')}
function clearRoom(){state.room=null;clearInterval(state.countdown);state.countdown=null;sessionStorage.removeItem('rbf.room')}
function applyPrefs(){document.body.classList.toggle('reduce-motion',state.settings.reducedMotion);document.body.classList.toggle('high-contrast',state.settings.highContrast)}
applyPrefs();
async function backend(){const c=new AbortController(),timer=setTimeout(()=>c.abort(),900);try{state.backend=(await fetch('/health',{signal:c.signal,cache:'no-store'})).ok}catch{state.backend=false}finally{clearTimeout(timer)}return state.backend}
function top(){return `<header class="site-top"><button class="brand brand-button" data-nav="home"><small>RERIDY PRESENTS</small><strong>RE:BUILDFRONT</strong></button><div class="auth-actions">${state.room?`<span class="status-pill active">● ${esc(state.room.name)}</span>`:''}${state.user?`<span>${esc(state.user.username)}</span><button class="btn" data-nav="account">${base('account')}</button>`:`<button class="btn" data-nav="login">${base('login')}</button><button class="btn primary" data-nav="signup">${base('signup')}</button>`}</div></header>`}
function shell(body){return `<main class="shell">${top()}${body}</main>`}
function side(){return `<aside class="panel side-nav"><button class="btn" data-nav="home">RE:BUILDFRONT</button><button class="btn" data-nav="play">${base('play')}</button><button class="btn" data-nav="account">${base('account')}</button><button class="btn" data-nav="customize">${base('customize')}</button><button class="btn" data-nav="settings">${base('settings')}</button></aside>`}
function page(title,body){return shell(`<div class="page-grid">${side()}<section class="panel content"><h2>${title}</h2>${body}</section></div>`)}
function go(p){if(state.room&&(state.page==='lobby'||state.page==='customize')){if(p==='play'||p==='lobby'){state.page='lobby';render();return}if(p==='customize'){state.page=p;render();return}if(!confirm(tx('leaveWarn')))return;clearRoom()}state.page=p;render()}
function nav(){root.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>go(b.dataset.nav))}
function home(){return shell(`<section class="hero panel"><div><span class="eyebrow">BUILD • HOLD • EXPAND</span><h1>${tx('hero')}</h1><p>${tx('heroBody')}</p><div class="row"><button class="btn primary hero-cta" data-nav="${state.room?'lobby':'play'}">${state.room?tx('continueRoom'):base('play')}</button><span class="status-pill ${state.backend?'online':''}">${state.backend?tx('server'):tx('local')}</span></div></div><div class="hero-mark">RE</div></section><div class="menu-grid"><button class="menu-tile" data-nav="play"><span class="tile-icon">▶</span><strong>${base('play')}</strong><span>${base('roomInfo')}</span></button><button class="menu-tile" data-nav="account"><span class="tile-icon">◎</span><strong>${base('account')}</strong><span>${base('accountInfo')}</span></button><button class="menu-tile" data-nav="customize"><span class="tile-icon">✦</span><strong>${base('customize')}</strong><span>${base('customInfo')}</span></button><button class="menu-tile" data-nav="settings"><span class="tile-icon">⚙</span><strong>${base('settings')}</strong><span>${base('settingsInfo')}</span></button></div>`)}
async function loadRooms(){if(await backend())try{const r=await fetch('/api/rooms',{cache:'no-store'});if(r.ok){state.rooms=await r.json();return}}catch{}state.rooms=ROOM_SEED.map(x=>({...x}))}
function roomCards(q='',difficulty='all'){const list=state.rooms.filter(r=>(!q||`${r.name} ${r.description}`.toLowerCase().includes(q.toLowerCase()))&&(difficulty==='all'||r.difficulty===difficulty));return list.length?list.map(r=>{const full=r.players>=r.maxPlayers;return `<article class="room-card"><div><div class="room-title-row"><b>${esc(r.name)}</b><span class="badge">${esc(r.map)}</span><span class="badge">${base(`difficulty${r.difficulty[0].toUpperCase()+r.difficulty.slice(1)}`)}</span><span class="badge">${String(r.language||'en').toUpperCase()}</span></div><p>${esc(r.description||'—')}</p><div class="capacity"><i style="width:${Math.min(100,r.players/r.maxPlayers*100)}%"></i></div><small>${r.players}/${r.maxPlayers}</small></div><button class="btn ${full?'':'primary'}" data-join="${r.id}" ${full?'disabled':''}>${full?tx('full'):base('join')}</button></article>`}).join(''):`<div class="empty-state">${base('noRooms')}</div>`}
function play(){return page(base('play'),`<div class="play-toolbar"><button id="quick" class="btn primary">${base('quickPlay')}</button><label class="check"><input id="sameLang" type="checkbox"> ${base('sameLanguage')}</label><button id="createToggle" class="btn">+ ${base('createRoom')}</button><span class="status-pill">${state.backend?tx('server'):tx('local')}</span></div><div class="room-filters"><input id="roomSearch" class="input" placeholder="${tx('searchRooms')}"><select id="diffFilter" class="input"><option value="all">${tx('allDifficulties')}</option>${DIFFICULTIES.map(d=>`<option value="${d}">${base(`difficulty${d[0].toUpperCase()+d.slice(1)}`)}</option>`).join('')}</select></div><div id="roomList" class="room-list">${roomCards()}</div><section id="createPanel" class="panel create-panel hidden"><div class="form-grid"><div class="field"><label>${base('roomName')}</label><input id="roomName" maxlength="40"></div><div class="field"><label>${base('map')}</label><select id="roomMap">${MAPS.map(m=>`<option value="${m.id}">${m.name}</option>`).join('')}</select></div><div class="field"><label>${base('difficulty')}</label><select id="roomDiff">${DIFFICULTIES.map(d=>`<option value="${d}">${base(`difficulty${d[0].toUpperCase()+d.slice(1)}`)}</option>`).join('')}</select></div><div class="field"><label>${tx('maxPlayers')}</label><input id="roomMax" type="number" min="1" max="15" value="4"><small id="maxNotice" class="field-notice hidden">${tx('maxNotice')}</small></div><div class="field span-2"><label>${base('description')}</label><textarea id="roomDesc" maxlength="160"></textarea></div></div><button id="createRoom" class="btn primary">${base('create')}</button></section>`)}
function clampMax(el,notify=true){let n=Math.round(Number(el.value)||4);if(n>MAX_ROOM_PLAYERS){n=MAX_ROOM_PLAYERS;if(notify)root.querySelector('#maxNotice')?.classList.remove('hidden')}else root.querySelector('#maxNotice')?.classList.add('hidden');n=Math.max(1,n);el.value=n;return n}
function makeRoom(seed){return{...seed,host:name(),members:[{name:name(),host:true,ready:true,ai:false}],aiCount:0,chat:[],players:1}}
async function createRoom(){const max=clampMax(root.querySelector('#roomMax')),body={name:root.querySelector('#roomName').value.trim()||`${name()}'s room`,description:root.querySelector('#roomDesc').value.trim(),map:root.querySelector('#roomMap').value,difficulty:root.querySelector('#roomDiff').value,maxPlayers:max,language:i18n.lang};let raw={id:`local-${Date.now()}`,...body,players:1};if(state.backend)try{const r=await fetch('/api/rooms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(r.ok)raw=await r.json()}catch{}state.room=makeRoom(raw);persistRoom();state.page='lobby';render()}
function joinRoom(id){const r=state.rooms.find(x=>x.id===id);if(!r||r.players>=r.maxPlayers)return;state.room={...r,host:r.hostName||'Host',members:[{name:r.hostName||'Host',host:true,ready:true,ai:false},{name:name(),host:false,ready:false,ai:false}],aiCount:0,chat:[]};persistRoom();state.page='lobby';render()}
function bindJoins(){root.querySelectorAll('[data-join]').forEach(b=>b.onclick=()=>joinRoom(b.dataset.join))}
function bindPlay(){const max=root.querySelector('#roomMax');root.querySelector('#createToggle').onclick=()=>root.querySelector('#createPanel').classList.toggle('hidden');max.oninput=()=>clampMax(max,true);max.onblur=()=>clampMax(max,false);root.querySelector('#createRoom').onclick=createRoom;const refresh=()=>{root.querySelector('#roomList').innerHTML=roomCards(root.querySelector('#roomSearch').value,root.querySelector('#diffFilter').value);bindJoins()};root.querySelector('#roomSearch').oninput=refresh;root.querySelector('#diffFilter').onchange=refresh;root.querySelector('#quick').onclick=()=>{const same=root.querySelector('#sameLang').checked,choices=state.rooms.filter(r=>r.players<r.maxPlayers&&(!same||r.language===i18n.lang));const pick=choices.sort((a,b)=>b.players/b.maxPlayers-a.players/a.maxPlayers)[0];if(pick)joinRoom(pick.id)};bindJoins()}
function humans(){return state.room?.members?.filter(m=>!m.ai)||[]}
function syncAi(){const r=state.room;if(!r)return;const real=humans(),maxAi=Math.max(0,r.maxPlayers-real.length);r.aiCount=Math.max(0,Math.min(r.aiCount||0,maxAi,14));r.members=[...real,...Array.from({length:r.aiCount},(_,i)=>({name:['MIKA','RON','EVE','NOVA','ALTO','KITE','LYRA','PICO','ARIA','NOX','MILO','LUMA','ORBIT','TESS'][i],host:false,ready:true,ai:true}))];r.players=r.members.length;persistRoom()}
function allReady(){return humans().filter(m=>!m.host).every(m=>m.ready)}
function lobby(){const r=state.room;if(!r)return play();syncAi();const self=humans().find(m=>m.name===name()),host=!!self?.host,cap=Math.max(0,r.maxPlayers-humans().length);return page(esc(r.name),`<div class="lobby-grid"><section><div class="lobby-status"><span class="badge">${tx('code')}: <b>${esc(r.id)}</b></span><button id="copyCode" class="btn">${tx('copy')}</button><span class="badge">${r.members.length}/${r.maxPlayers}</span></div><div class="form-grid"><div class="field"><label>${base('roomName')}</label><input id="lName" value="${esc(r.name)}" ${host?'':'disabled'}></div><div class="field"><label>${base('map')}</label><select id="lMap" ${host?'':'disabled'}>${MAPS.map(m=>`<option value="${m.id}" ${m.id===r.map?'selected':''}>${m.name}</option>`).join('')}</select></div><div class="field"><label>${base('difficulty')}</label><select id="lDiff" ${host?'':'disabled'}>${DIFFICULTIES.map(d=>`<option value="${d}" ${d===r.difficulty?'selected':''}>${base(`difficulty${d[0].toUpperCase()+d.slice(1)}`)}</option>`).join('')}</select></div><div class="field"><label>${tx('maxPlayers')}</label><input id="lMax" type="number" min="1" max="15" value="${r.maxPlayers}" ${host?'':'disabled'}></div><div class="field span-2"><label>${base('description')}</label><textarea id="lDesc" ${host?'':'disabled'}>${esc(r.description||'')}</textarea></div></div>${host?`<button id="saveRoom" class="btn">${base('save')}</button>`:''}<section class="panel lobby-chat"><h3>${tx('chat')}</h3><div id="lobbyChatLog" class="chat-log">${(r.chat||[]).slice(-40).map(m=>`<div class="chat-row"><b>${esc(m.name)}</b> ${esc(m.text)}</div>`).join('')}</div><div class="row"><input id="lobbyChatInput" class="input" maxlength="180"><button id="lobbyChatSend" class="btn">${tx('send')}</button></div></section><button id="leaveRoom" class="btn danger">${tx('leave')}</button></section><aside class="panel lobby-people"><h3>${base('players')}</h3>${r.members.map(m=>`<div class="player-row"><span>${esc(m.name)} ${m.host?'★':''}${m.ai?' <small>AI</small>':''}</span><span class="${m.ready?'ready':''}">${m.host?base('host'):(m.ai?tx('auto'):(m.ready?base('ready'):base('unready')))}</span></div>`).join('')}${host?`<div class="row"><button id="addAI" class="btn" ${r.aiCount>=cap?'disabled':''}>+ ${tx('addAI')}</button><button id="removeAI" class="btn" ${!r.aiCount?'disabled':''}>− ${tx('removeAI')}</button></div>`:''}<div class="lobby-start">${host?`<button id="startGame" class="btn primary" ${allReady()?'':'disabled'}>${base('startGame')}</button>${!allReady()?`<p class="muted">${base('waitingReady')}</p>`:''}`:`<button id="readyBtn" class="btn primary">${self?.ready?tx('cancelReady'):base('ready')}</button>`}<div id="countdown" class="countdown hidden"></div></div></aside></div>`)}
function bindLobby(){const r=state.room,self=humans().find(m=>m.name===name()),host=!!self?.host;root.querySelector('#copyCode').onclick=async()=>{try{await navigator.clipboard.writeText(r.id);root.querySelector('#copyCode').textContent=tx('copied')}catch{}};root.querySelector('#leaveRoom').onclick=()=>{if(confirm(tx('leaveWarn'))){clearRoom();state.page='play';render()}};root.querySelector('#readyBtn')?.addEventListener('click',()=>{self.ready=!self.ready;persistRoom();render()});root.querySelector('#addAI')?.addEventListener('click',()=>{r.aiCount=(r.aiCount||0)+1;syncAi();render()});root.querySelector('#removeAI')?.addEventListener('click',()=>{r.aiCount=Math.max(0,(r.aiCount||0)-1);syncAi();render()});root.querySelector('#saveRoom')?.addEventListener('click',()=>{r.name=root.querySelector('#lName').value.trim()||r.name;r.description=root.querySelector('#lDesc').value.trim();r.map=root.querySelector('#lMap').value;r.difficulty=root.querySelector('#lDiff').value;const requested=Math.round(Number(root.querySelector('#lMax').value)||r.maxPlayers);if(requested>MAX_ROOM_PLAYERS)alert(tx('maxNotice'));r.maxPlayers=Math.max(r.members.length,Math.min(MAX_ROOM_PLAYERS,requested));syncAi();persistRoom();render()});const send=()=>{const input=root.querySelector('#lobbyChatInput'),text=input.value.trim();if(!text)return;r.chat=r.chat||[];r.chat.push({name:name(),text:text.slice(0,180)});r.chat=r.chat.slice(-40);persistRoom();render()};root.querySelector('#lobbyChatSend').onclick=send;root.querySelector('#lobbyChatInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();send()}};root.querySelector('#startGame')?.addEventListener('click',()=>startCountdown())}
function startCountdown(){if(state.countdown||!allReady())return;let left=5,constBox=root.querySelector('#countdown'),button=root.querySelector('#startGame');button.disabled=true;const paint=()=>{constBox.textContent=`${tx('starting')} ${left}`;constBox.classList.remove('hidden');button.textContent=String(left)};paint();state.countdown=setInterval(()=>{left--;if(left>0)return paint();clearInterval(state.countdown);state.countdown=null;startGame()},1000)}
function startGame(){const r=state.room;if(!r)return;root.classList.add('hidden');gameRoot.classList.remove('hidden');window.dispatchEvent(new CustomEvent('rbf-start-game',{detail:{room:{...r,aiCount:r.aiCount||0},playerName:name(),language:i18n.lang,settings:state.settings,custom:state.custom.active}}))}
function authPage(mode){const signup=mode==='signup';return shell(`<div class="login-card panel"><button class="btn" data-nav="home">← ${base('back')}</button><h2>${signup?base('signup'):base('login')}</h2><div class="field"><label>${base('username')}</label><input id="authUser" maxlength="20" autocomplete="username"></div><div class="field"><label>${base('password')}</label><input id="authPass" type="password" minlength="8"></div><button id="authSubmit" class="btn primary full">${signup?base('signup'):base('login')}</button><p id="authStatus" class="muted"></p><button class="btn full" data-nav="${signup?'login':'signup'}">${signup?base('login'):base('signup')}</button><p class="muted">${base('oauthPlanned')}</p></div>`)}
async function authSubmit(mode){const u=root.querySelector('#authUser').value.trim(),p=root.querySelector('#authPass').value,status=root.querySelector('#authStatus');if(u.length<3||p.length<8){status.textContent=base('credentialsRule');return}try{const r=await fetch(`/api/auth/${mode}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u,password:p,language:i18n.lang})}),d=await r.json();if(!r.ok)throw 0;state.user=d.user;sessionStorage.setItem('rbf.user',JSON.stringify(d.user));sessionStorage.setItem('rbf.token',d.token);state.page='home';render()}catch{status.textContent=base('backendRequired')}}
function account(){return page(base('account'),state.user?`<div class="account-card"><div class="avatar-preview">${esc(state.user.username.slice(0,2).toUpperCase())}</div><div><h3>${esc(state.user.username)}</h3><p class="muted">${base('language')}: ${i18n.lang.toUpperCase()}</p></div></div><div class="row"><button id="logout" class="btn">${base('logout')}</button><button id="deleteAccount" class="btn danger">${base('deleteAccount')}</button></div>`:`<div class="empty-state"><b>${base('accountRequired')}</b><div class="row"><button class="btn" data-nav="login">${base('login')}</button><button class="btn primary" data-nav="signup">${base('signup')}</button></div><span>${base('guest')}: ${esc(state.guestName)}</span></div>`)}
function bindAccount(){root.querySelector('#logout')?.addEventListener('click',()=>{state.user=null;sessionStorage.removeItem('rbf.user');sessionStorage.removeItem('rbf.token');render()});root.querySelector('#deleteAccount')?.addEventListener('click',async()=>{if(!confirm(base('deleteAccount')))return;try{await fetch('/api/account',{method:'DELETE',headers:{Authorization:`Bearer ${sessionStorage.getItem('rbf.token')||''}`}})}catch{}state.user=null;sessionStorage.removeItem('rbf.user');sessionStorage.removeItem('rbf.token');render()})}
function customize(){const saved=state.custom.templates.map((_,i)=>`<button class="btn" data-template="${i}">${base('templates')} ${i+1}</button>`).join('');return page(base('customize'),`<div class="custom-grid"><div class="draw-wrap"><canvas id="avatarCanvas" class="avatar-canvas" width="512" height="512"></canvas></div><aside><div class="sticker-grid">${['★','♥','⚙','✦','▲','●','◆','☁'].map(s=>`<button class="btn sticker" data-sticker="${s}">${s}</button>`).join('')}</div><div class="row"><input id="drawColor" type="color" value="#74d3ff"><button id="clearAvatar" class="btn">${base('clear')}</button><button id="saveAvatar" class="btn primary">${base('save')}</button></div><button id="uploadUnlock" class="btn full">${state.custom.uploadUnlocked?base('uploadImage'):base('watchAd')}</button><input id="imageUpload" class="hidden" type="file" accept="image/png,image/jpeg,image/webp"><div class="row">${saved||`<span class="muted">${base('noTemplates')}</span>`}</div>${state.room?`<button class="btn primary full" data-nav="play">${tx('continueRoom')}</button>`:''}</aside></div>`)}
function baseAvatar(c){c.clearRect(0,0,512,512);c.fillStyle='#dceaf5';c.beginPath();c.arc(256,256,150,0,Math.PI*2);c.fill();c.fillStyle='#15202b';c.beginPath();c.arc(210,230,16,0,Math.PI*2);c.arc(302,230,16,0,Math.PI*2);c.fill()}
function bindCustomize(){const cv=root.querySelector('#avatarCanvas'),c=cv.getContext('2d');if(state.custom.active){const img=new Image();img.onload=()=>c.drawImage(img,0,0,512,512);img.src=state.custom.active}else baseAvatar(c);let drawing=false,sticker='';const pos=e=>{const r=cv.getBoundingClientRect();return{x:(e.clientX-r.left)*512/r.width,y:(e.clientY-r.top)*512/r.height}};cv.onpointerdown=e=>{const p=pos(e);if(sticker){c.font='72px sans-serif';c.textAlign='center';c.fillText(sticker,p.x,p.y);sticker='';return}drawing=true;c.beginPath();c.moveTo(p.x,p.y)};cv.onpointermove=e=>{if(!drawing)return;const p=pos(e);c.strokeStyle=root.querySelector('#drawColor').value;c.lineWidth=12;c.lineCap='round';c.lineTo(p.x,p.y);c.stroke()};cv.onpointerup=()=>drawing=false;root.querySelectorAll('[data-sticker]').forEach(b=>b.onclick=()=>sticker=b.dataset.sticker);root.querySelector('#clearAvatar').onclick=()=>baseAvatar(c);root.querySelector('#saveAvatar').onclick=()=>{const d=cv.toDataURL('image/png');state.custom.templates.push(d);state.custom.templates=state.custom.templates.slice(-12);state.custom.active=d;localStorage.setItem('rbf.templates',JSON.stringify(state.custom.templates));localStorage.setItem('rbf.activeAvatar',d);render()};root.querySelector('#uploadUnlock').onclick=async()=>{if(!state.custom.uploadUnlocked){try{const r=await fetch('/api/ad/reward',{method:'POST'});if(!r.ok)throw 0;const d=await r.json();if(!d.ok)throw 0;state.custom.uploadUnlocked=true}catch{alert(tx('rewardUnavailable'));return}render();return}root.querySelector('#imageUpload').click()};root.querySelector('#imageUpload').onchange=e=>{const f=e.target.files?.[0];if(!f||!/^image\/(png|jpeg|webp)$/.test(f.type)||f.size>3e6)return;const img=new Image();img.onload=()=>{c.drawImage(img,76,76,360,360);URL.revokeObjectURL(img.src)};img.src=URL.createObjectURL(f)};root.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>{state.custom.active=state.custom.templates[Number(b.dataset.template)];localStorage.setItem('rbf.activeAvatar',state.custom.active);render()})}
function settings(){return page(base('settings'),`<div class="settings-grid"><div class="field"><label>${base('volume')} <span id="volText">${Math.round(state.settings.volume*100)}%</span></label><input id="volume" type="range" min="0" max="1" step=".01" value="${state.settings.volume}"></div><div class="field"><label>${base('language')}</label><select id="language">${SUPPORTED_LANGUAGES.map(l=>`<option value="${l}" ${l===i18n.lang?'selected':''}>${{en:'English',ko:'한국어',ja:'日本語',zh:'中文'}[l]}</option>`).join('')}</select></div><label class="setting-row"><input id="motion" type="checkbox" ${state.settings.reducedMotion?'checked':''}> ${base('reducedMotion')}</label><label class="setting-row"><input id="tips" type="checkbox" ${state.settings.showTips?'checked':''}> ${tx('tips')}</label><label class="setting-row"><input id="contrast" type="checkbox" ${state.settings.highContrast?'checked':''}> ${tx('contrast')}</label><button class="btn" data-nav="account">${base('account')}</button>${state.room?`<button class="btn primary" data-nav="play">${tx('continueRoom')}</button>`:''}</div>`)}
function bindSettings(){root.querySelector('#volume').oninput=e=>{state.settings.volume=Number(e.target.value);localStorage.setItem('rbf.volume',state.settings.volume);root.querySelector('#volText').textContent=`${Math.round(state.settings.volume*100)}%`};root.querySelector('#language').onchange=e=>i18n.set(e.target.value);root.querySelector('#motion').onchange=e=>{state.settings.reducedMotion=e.target.checked;localStorage.setItem('rbf.motion',e.target.checked?'reduced':'full');applyPrefs()};root.querySelector('#tips').onchange=e=>{state.settings.showTips=e.target.checked;localStorage.setItem('rbf.tips',e.target.checked?'on':'off')};root.querySelector('#contrast').onchange=e=>{state.settings.highContrast=e.target.checked;localStorage.setItem('rbf.contrast',e.target.checked?'high':'normal');applyPrefs()}}
async function render(){root.classList.remove('hidden');gameRoot.classList.add('hidden');if(state.page==='home'||state.page==='play')await backend();if(state.page==='play')await loadRooms();root.innerHTML=state.page==='home'?home():state.page==='play'?play():state.page==='lobby'?lobby():state.page==='account'?account():state.page==='customize'?customize():state.page==='settings'?settings():authPage(state.page);nav();if(state.page==='play')bindPlay();if(state.page==='lobby')bindLobby();if(state.page==='account')bindAccount();if(state.page==='customize')bindCustomize();if(state.page==='settings')bindSettings();if(state.page==='login'||state.page==='signup')root.querySelector('#authSubmit').onclick=()=>authSubmit(state.page);applyPrefs()}
window.addEventListener('rbf-language',render);window.addEventListener('rbf-return-lobby',()=>{state.page=state.room?'lobby':'play';render()});window.addEventListener('rbf-leave-room',()=>{clearRoom();state.page='play';render()});window.addEventListener('rbf-exit-game',()=>{state.page=state.room?'lobby':'play';render()});render();
