const STORAGE='rbf.customProjects.v1',ACTIVE='rbf.customProject.active';
const lang=()=>{const l=(document.documentElement.lang||'en').toLowerCase();return l.startsWith('ko')?'ko':l.startsWith('ja')?'ja':l.startsWith('zh')?'zh':'en'};
const L={en:{newProject:'New',save:'Save',duplicate:'Duplicate',delete:'Delete',exportPng:'PNG',exportJson:'Project JSON',importJson:'Import JSON',importImage:'Import image',layers:'Layers',addLayer:'Add layer',dupLayer:'Duplicate',delLayer:'Delete',brush:'Brush',eraser:'Eraser',eyedropper:'Eyedropper',undo:'Undo',redo:'Redo',zoom:'Zoom',size:'Size',opacity:'Opacity',visible:'Visible',locked:'Locked',active:'Active look',confirmDelete:'Delete this saved look?',base:'Base',paint:'Paint',autosaved:'Autosaved'},ko:{newProject:'새로 만들기',save:'저장',duplicate:'복제',delete:'삭제',exportPng:'PNG 내보내기',exportJson:'프로젝트 내보내기',importJson:'프로젝트 불러오기',importImage:'이미지 불러오기',layers:'레이어',addLayer:'레이어 추가',dupLayer:'복제',delLayer:'삭제',brush:'브러시',eraser:'지우개',eyedropper:'스포이드',undo:'실행 취소',redo:'다시 실행',zoom:'확대',size:'크기',opacity:'불투명도',visible:'표시',locked:'잠금',active:'게임에 적용 중',confirmDelete:'이 외형 프로젝트를 삭제하시겠습니까?',base:'기본',paint:'그림',autosaved:'자동 저장됨'},ja:{newProject:'新規',save:'保存',duplicate:'複製',delete:'削除',exportPng:'PNG書き出し',exportJson:'JSON書き出し',importJson:'JSON読込',importImage:'画像読込',layers:'レイヤー',addLayer:'追加',dupLayer:'複製',delLayer:'削除',brush:'ブラシ',eraser:'消しゴム',eyedropper:'スポイト',undo:'元に戻す',redo:'やり直す',zoom:'ズーム',size:'サイズ',opacity:'不透明度',visible:'表示',locked:'ロック',active:'使用中',confirmDelete:'この外見を削除しますか？',base:'ベース',paint:'ペイント',autosaved:'自動保存'},zh:{newProject:'新建',save:'保存',duplicate:'复制',delete:'删除',exportPng:'导出PNG',exportJson:'导出项目',importJson:'导入项目',importImage:'导入图片',layers:'图层',addLayer:'添加图层',dupLayer:'复制',delLayer:'删除',brush:'画笔',eraser:'橡皮擦',eyedropper:'吸管',undo:'撤销',redo:'重做',zoom:'缩放',size:'大小',opacity:'不透明度',visible:'显示',locked:'锁定',active:'正在使用',confirmDelete:'删除这个外观项目？',base:'基础',paint:'绘画',autosaved:'已自动保存'}};
const t=k=>L[lang()]?.[k]||L.en[k]||k,uid=()=>`c_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`,okData=v=>typeof v==='string'&&v.startsWith('data:image/'),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const read=()=>{try{const v=JSON.parse(localStorage.getItem(STORAGE)||'[]');return Array.isArray(v)?v:[]}catch{return[]}},write=v=>{try{localStorage.setItem(STORAGE,JSON.stringify(v));return true}catch{return false}};
function canvasData(draw){const c=document.createElement('canvas');c.width=c.height=512;draw?.(c.getContext('2d'));return c.toDataURL('image/webp',.9)}
const blank=()=>canvasData(),base=()=>canvasData(x=>{x.fillStyle='#dceaf5';x.beginPath();x.arc(256,256,150,0,Math.PI*2);x.fill();x.fillStyle='#15202b';x.beginPath();x.arc(210,230,16,0,Math.PI*2);x.arc(302,230,16,0,Math.PI*2);x.fill();x.strokeStyle='#60778a';x.lineWidth=7;x.beginPath();x.arc(256,272,58,.15*Math.PI,.85*Math.PI);x.stroke()});
function normalize(p){if(!p||typeof p!=='object')return null;const layers=(Array.isArray(p.layers)?p.layers:[]).filter(x=>x&&okData(x.bitmap)).map((x,i)=>({id:x.id||uid(),name:String(x.name||`Layer ${i+1}`).slice(0,40),visible:x.visible!==false,locked:!!x.locked,opacity:Math.max(0,Math.min(1,Number(x.opacity??1))),bitmap:x.bitmap}));if(!layers.length)layers.push({id:uid(),name:t('base'),visible:true,locked:false,opacity:1,bitmap:base()});return{id:p.id||uid(),name:String(p.name||'My Look').slice(0,40),updatedAt:Number(p.updatedAt)||Date.now(),preview:okData(p.preview)?p.preview:null,layers,selectedLayer:layers.some(x=>x.id===p.selectedLayer)?p.selectedLayer:layers.at(-1).id}}
function fresh(){const a={id:uid(),name:t('base'),visible:true,locked:false,opacity:1,bitmap:base()},b={id:uid(),name:t('paint'),visible:true,locked:false,opacity:1,bitmap:blank()};return{id:uid(),name:'My Look',updatedAt:Date.now(),preview:null,layers:[a,b],selectedLayer:b.id}}
const image=src=>new Promise(resolve=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>resolve(null);i.src=src});
let mounted=null;
async function mount(host){if(mounted===host)return;const old=host.querySelector('.custom-grid');if(!old)return;mounted=host;let projects=read().map(normalize).filter(Boolean),current=projects.find(p=>p.id===localStorage.getItem(ACTIVE))||projects[0]||fresh();if(!projects.some(p=>p.id===current.id)){projects.push(current);write(projects)};
old.outerHTML=`<div class="ps-editor" id="rbfPsEditor"><header class="ps-toolbar"><div class="ps-project"><input id="psProjectName" class="input" maxlength="40"><button class="btn" data-act="new">${t('newProject')}</button><button class="btn primary" data-act="save">${t('save')}</button><button class="btn" data-act="duplicate">${t('duplicate')}</button><button class="btn danger" data-act="delete">${t('delete')}</button></div><div class="ps-tools"><button class="btn primary" data-tool="brush">✎ ${t('brush')}</button><button class="btn" data-tool="eraser">⌫ ${t('eraser')}</button><button class="btn" data-tool="eyedropper">◉ ${t('eyedropper')}</button><button class="btn" data-act="undo">↶ ${t('undo')}</button><button class="btn" data-act="redo">↷ ${t('redo')}</button></div><div class="ps-controls"><input id="psColor" type="color" value="#74d3ff"><label>${t('size')} <input id="psSize" type="range" min="1" max="80" value="12"></label><label>${t('zoom')} <input id="psZoom" type="range" min="50" max="300" value="100"></label><span id="psZoomText">100%</span></div><div class="ps-stickers">${['★','♥','⚙','✦','▲','●','◆','☁'].map(s=>`<button class="btn tiny" data-sticker="${s}">${s}</button>`).join('')}</div></header><div class="ps-main"><aside class="ps-projects"><div id="psProjectList" class="ps-project-list"></div><button class="btn full" data-act="importImage">${t('importImage')}</button><button class="btn full" data-act="importJson">${t('importJson')}</button><button class="btn full" data-act="exportJson">${t('exportJson')}</button><button class="btn full" data-act="exportPng">${t('exportPng')}</button><input id="psImageImport" type="file" accept="image/png,image/jpeg,image/webp" hidden><input id="psJsonImport" type="file" accept="application/json" hidden></aside><section class="ps-stage"><div class="ps-checker"><div id="psCanvasStack" class="ps-canvas-stack"><canvas id="psComposite" width="512" height="512"></canvas><canvas id="psPaint" width="512" height="512"></canvas></div></div><div id="psStatus" class="muted"></div></section><aside class="ps-layers"><div class="section-heading"><h3>${t('layers')}</h3><button class="btn tiny" data-act="addLayer">+ ${t('addLayer')}</button></div><div id="psLayerList" class="ps-layer-list"></div><div class="ps-layer-actions"><button class="btn" data-act="dupLayer">${t('dupLayer')}</button><button class="btn danger" data-act="delLayer">${t('delLayer')}</button><button class="btn" data-act="up">↑</button><button class="btn" data-act="down">↓</button></div><label>${t('opacity')} <input id="psOpacity" type="range" min="0" max="100" value="100"></label></aside></div></div>`;
const E=id=>host.querySelector(`#${id}`),comp=E('psComposite'),paint=E('psPaint'),cx=comp.getContext('2d'),px=paint.getContext('2d'),stack=E('psCanvasStack'),status=E('psStatus'),imgs=new Map();let tool='brush',sticker='',drawing=false,last=null,zoom=1,history=[],redo=[],timer=null;
const selected=()=>current.layers.find(x=>x.id===current.selectedLayer)||current.layers.at(-1),serial=()=>JSON.stringify(current,(k,v)=>k==='_img'?undefined:v);
async function loadCurrent(){imgs.clear();await Promise.all(current.layers.map(async l=>imgs.set(l.id,await image(l.bitmap))));renderAll()}
function snapshot(){history.push(serial());if(history.length>30)history.shift();redo=[]}
async function restore(raw){current=normalize(JSON.parse(raw));await loadCurrent()}
function commit(){const l=selected();if(!l)return;l.bitmap=paint.toDataURL('image/webp',.9);const i=new Image();i.src=l.bitmap;imgs.set(l.id,i)}
function renderComposite(){cx.clearRect(0,0,512,512);const sel=selected();for(const l of current.layers){if(!l.visible||l.id===sel?.id)continue;const i=imgs.get(l.id);if(i?.complete){cx.globalAlpha=l.opacity;cx.drawImage(i,0,0,512,512)}}cx.globalAlpha=1}
function renderSelected(){const l=selected();px.clearRect(0,0,512,512);paint.style.opacity=l?.visible?String(l.opacity):'0';const i=l&&imgs.get(l.id);if(i?.complete)px.drawImage(i,0,0,512,512)}
function flatten(){commit();const out=document.createElement('canvas'),x=out.getContext('2d');out.width=out.height=512;for(const l of current.layers){if(!l.visible)continue;const i=imgs.get(l.id);if(i?.complete){x.globalAlpha=l.opacity;x.drawImage(i,0,0,512,512)}}x.globalAlpha=1;return out}
function renderProjects(){E('psProjectList').innerHTML=projects.map(p=>`<button class="ps-project-card ${p.id===current.id?'active':''}" data-project="${p.id}"><img src="${esc(p.preview||p.layers.at(-1)?.bitmap||'')}" alt=""><span>${esc(p.name)}</span>${p.id===localStorage.getItem(ACTIVE)?`<em>${t('active')}</em>`:''}</button>`).join('');host.querySelectorAll('[data-project]').forEach(b=>b.onclick=async()=>{commit();const p=projects.find(x=>x.id===b.dataset.project);if(!p)return;current=normalize(p);history=[];redo=[];await loadCurrent()})}
function renderLayers(){E('psLayerList').innerHTML=[...current.layers].reverse().map(l=>`<div class="ps-layer ${l.id===current.selectedLayer?'active':''}" data-layer="${l.id}"><button class="ps-icon" data-vis>${l.visible?'◉':'○'}</button><button class="ps-icon" data-lock>${l.locked?'🔒':'🔓'}</button><input class="ps-layer-name input" data-name maxlength="40" value="${esc(l.name)}"></div>`).join('');host.querySelectorAll('[data-layer]').forEach(row=>{const l=current.layers.find(x=>x.id===row.dataset.layer);row.onclick=e=>{if(e.target.matches('[data-vis],[data-lock],[data-name]'))return;commit();current.selectedLayer=l.id;renderAll()};row.querySelector('[data-vis]').onclick=()=>{snapshot();l.visible=!l.visible;renderAll();queue()};row.querySelector('[data-lock]').onclick=()=>{l.locked=!l.locked;renderLayers()};row.querySelector('[data-name]').onchange=e=>{l.name=e.target.value.trim()||'Layer';queue()}});E('psOpacity').value=Math.round((selected()?.opacity??1)*100)}
function renderAll(){E('psProjectName').value=current.name;renderComposite();renderSelected();renderLayers();renderProjects();stack.style.transform=`scale(${zoom})`;E('psZoomText').textContent=`${Math.round(zoom*100)}%`}
function compat(preview){localStorage.setItem('rbf.activeAvatar',preview);let old=[];try{const v=JSON.parse(localStorage.getItem('rbf.templates')||'[]');if(Array.isArray(v))old=v}catch{}localStorage.setItem('rbf.templates',JSON.stringify([...old.filter(x=>x!==preview),preview].slice(-12)));localStorage.setItem(ACTIVE,current.id);window.dispatchEvent(new CustomEvent('rbf-custom-active',{detail:{preview,projectId:current.id}}))}
function save(show=false){commit();current.name=E('psProjectName').value.trim()||'Untitled';current.updatedAt=Date.now();current.preview=flatten().toDataURL('image/webp',.75);const clean=normalize(JSON.parse(serial()));clean.preview=current.preview;const i=projects.findIndex(p=>p.id===current.id);if(i<0)projects.push(clean);else projects[i]=clean;projects=projects.slice(-20);write(projects);compat(current.preview);status.textContent=show?t('save'):t('autosaved');setTimeout(()=>status.textContent='',1000);renderProjects()}
function queue(){clearTimeout(timer);timer=setTimeout(()=>save(false),650)}
async function addLayer(bitmap=blank(),name=`Layer ${current.layers.length+1}`){snapshot();commit();const l={id:uid(),name,visible:true,locked:false,opacity:1,bitmap};current.layers.push(l);current.selectedLayer=l.id;imgs.set(l.id,await image(bitmap));renderAll();queue()}
async function newProject(){commit();current=fresh();projects.push(current);history=[];redo=[];await loadCurrent();save(true)}
async function duplicateProject(){commit();const p=JSON.parse(serial());p.id=uid();p.name=`${current.name} Copy`;p.layers=p.layers.map(l=>({...l,id:uid()}));p.selectedLayer=p.layers.at(-1).id;current=normalize(p);projects.push(current);await loadCurrent();save(true)}
async function deleteProject(){const yes=window.rbfModal?await window.rbfModal({title:t('confirmDelete'),primary:t('delete'),secondary:'Cancel',danger:true}):true;if(!yes)return;projects=projects.filter(p=>p.id!==current.id);current=normalize(projects[0])||fresh();if(!projects.length)projects=[current];await loadCurrent();save(true)}
function move(dir){const l=selected(),i=current.layers.indexOf(l),j=i+dir;if(j<0||j>=current.layers.length)return;snapshot();[current.layers[i],current.layers[j]]=[current.layers[j],current.layers[i]];renderAll();queue()}
function pnt(e){const r=paint.getBoundingClientRect();return{x:(e.clientX-r.left)*512/r.width,y:(e.clientY-r.top)*512/r.height}}
paint.onpointerdown=e=>{const l=selected();if(!l||l.locked||!l.visible)return;const p=pnt(e);if(sticker){snapshot();px.fillStyle=E('psColor').value;px.font=`${Math.max(24,Number(E('psSize').value)*4)}px sans-serif`;px.textAlign='center';px.fillText(sticker,p.x,p.y);sticker='';commit();queue();return}if(tool==='eyedropper'){const d=flatten().getContext('2d').getImageData(Math.max(0,Math.min(511,p.x|0)),Math.max(0,Math.min(511,p.y|0)),1,1).data;E('psColor').value='#'+[d[0],d[1],d[2]].map(v=>v.toString(16).padStart(2,'0')).join('');return}snapshot();drawing=true;last=p;paint.setPointerCapture?.(e.pointerId)};
paint.onpointermove=e=>{if(!drawing)return;const p=pnt(e);px.save();px.lineCap='round';px.lineJoin='round';px.lineWidth=Number(E('psSize').value);px.globalCompositeOperation=tool==='eraser'?'destination-out':'source-over';px.strokeStyle=E('psColor').value;px.beginPath();px.moveTo(last.x,last.y);px.lineTo(p.x,p.y);px.stroke();px.restore();last=p};paint.onpointerup=paint.onpointercancel=()=>{if(!drawing)return;drawing=false;commit();queue()};
host.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;sticker='';host.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('primary',x===b))});host.querySelectorAll('[data-sticker]').forEach(b=>b.onclick=()=>{sticker=b.dataset.sticker});
host.querySelector('[data-act="save"]').onclick=()=>save(true);host.querySelector('[data-act="new"]').onclick=newProject;host.querySelector('[data-act="duplicate"]').onclick=duplicateProject;host.querySelector('[data-act="delete"]').onclick=deleteProject;host.querySelector('[data-act="addLayer"]').onclick=()=>addLayer();host.querySelector('[data-act="dupLayer"]').onclick=async()=>{const l=selected();if(l)await addLayer(l.bitmap,`${l.name} Copy`)};host.querySelector('[data-act="delLayer"]').onclick=()=>{if(current.layers.length<=1)return;snapshot();const i=current.layers.indexOf(selected());current.layers.splice(i,1);current.selectedLayer=current.layers[Math.max(0,i-1)].id;renderAll();queue()};host.querySelector('[data-act="up"]').onclick=()=>move(1);host.querySelector('[data-act="down"]').onclick=()=>move(-1);
host.querySelector('[data-act="undo"]').onclick=async()=>{if(!history.length)return;redo.push(serial());await restore(history.pop())};host.querySelector('[data-act="redo"]').onclick=async()=>{if(!redo.length)return;history.push(serial());await restore(redo.pop())};E('psOpacity').oninput=e=>{const l=selected();if(!l)return;l.opacity=Number(e.target.value)/100;paint.style.opacity=l.visible?String(l.opacity):'0';renderComposite();queue()};E('psProjectName').onchange=()=>queue();E('psZoom').oninput=e=>{zoom=Number(e.target.value)/100;stack.style.transform=`scale(${zoom})`;E('psZoomText').textContent=`${e.target.value}%`};
host.querySelector('[data-act="exportPng"]').onclick=()=>{const a=document.createElement('a');a.href=flatten().toDataURL('image/png');a.download=`${current.name||'look'}.png`;a.click()};host.querySelector('[data-act="exportJson"]').onclick=()=>{commit();const blob=new Blob([serial()],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${current.name||'look'}.rbf-look.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
host.querySelector('[data-act="importJson"]').onclick=()=>E('psJsonImport').click();E('psJsonImport').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=async()=>{try{const p=normalize(JSON.parse(r.result));if(!p)throw 0;p.id=uid();current=p;projects.push(p);await loadCurrent();save(true)}catch{status.textContent='Invalid project'}};r.readAsText(f)};
host.querySelector('[data-act="importImage"]').onclick=()=>E('psImageImport').click();E('psImageImport').onchange=e=>{const f=e.target.files?.[0];if(!f||!/^image\/(png|jpeg|webp)$/.test(f.type)||f.size>5e6)return;const r=new FileReader();r.onload=async()=>{const i=await image(r.result);if(!i)return;const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d'),s=Math.min(512/i.width,512/i.height),w=i.width*s,h=i.height*s;x.drawImage(i,(512-w)/2,(512-h)/2,w,h);await addLayer(c.toDataURL('image/webp',.9),f.name.replace(/\.[^.]+$/,''))};r.readAsDataURL(f)};
window.addEventListener('keydown',function keys(e){if(!document.getElementById('rbfPsEditor'))return;const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==='z'){e.preventDefault();(e.shiftKey?host.querySelector('[data-act="redo"]'):host.querySelector('[data-act="undo"]')).click()}else if(mod&&e.key.toLowerCase()==='s'){e.preventDefault();save(true)}else if(!mod&&!/INPUT|TEXTAREA/.test(document.activeElement?.tagName||'')){if(e.key.toLowerCase()==='b')host.querySelector('[data-tool="brush"]').click();if(e.key.toLowerCase()==='e')host.querySelector('[data-tool="eraser"]').click();if(e.key.toLowerCase()==='i')host.querySelector('[data-tool="eyedropper"]').click()}});
await loadCurrent();save(false)}
const obs=new MutationObserver(()=>{const grid=document.querySelector('.custom-grid');if(grid&&!document.getElementById('rbfPsEditor'))mount(grid.closest('.content')||document)});obs.observe(document.getElementById('appRoot'),{childList:true,subtree:true});
window.addEventListener('rbf-start-game',e=>{const active=localStorage.getItem('rbf.activeAvatar');if(e.detail&&okData(active))e.detail.custom=active});