const STORAGE='rbf.customProjects.v1',ACTIVE='rbf.customProject.active';
const lang=()=>{const l=(document.documentElement.lang||'en').toLowerCase();return l.startsWith('ko')?'ko':l.startsWith('ja')?'ja':l.startsWith('zh')?'zh':'en'};
const L={en:{title:'Character Studio',project:'Project',newProject:'New',save:'Save',duplicate:'Duplicate',delete:'Delete',exportPng:'PNG',exportJson:'Project JSON',importJson:'Import JSON',layers:'Layers',addLayer:'Add layer',dupLayer:'Duplicate layer',delLayer:'Delete layer',brush:'Brush',eraser:'Eraser',eyedropper:'Eyedropper',undo:'Undo',redo:'Redo',zoom:'Zoom',size:'Size',opacity:'Opacity',visible:'Visible',locked:'Locked',moveUp:'Up',moveDown:'Down',rename:'Rename layer',autosaved:'Autosaved',active:'Active look',empty:'No saved projects yet.',confirmDelete:'Delete this saved look?',base:'Base',paint:'Paint'},ko:{title:'캐릭터 스튜디오',project:'프로젝트',newProject:'새로 만들기',save:'저장',duplicate:'복제',delete:'삭제',exportPng:'PNG 내보내기',exportJson:'프로젝트 내보내기',importJson:'프로젝트 불러오기',layers:'레이어',addLayer:'레이어 추가',dupLayer:'레이어 복제',delLayer:'레이어 삭제',brush:'브러시',eraser:'지우개',eyedropper:'스포이드',undo:'실행 취소',redo:'다시 실행',zoom:'확대',size:'크기',opacity:'불투명도',visible:'표시',locked:'잠금',moveUp:'위로',moveDown:'아래로',rename:'레이어 이름',autosaved:'자동 저장됨',active:'게임에 적용 중',empty:'저장된 프로젝트가 없습니다.',confirmDelete:'이 외형 프로젝트를 삭제하시겠습니까?',base:'기본',paint:'그림'},ja:{title:'キャラクタースタジオ',project:'プロジェクト',newProject:'新規',save:'保存',duplicate:'複製',delete:'削除',exportPng:'PNG書き出し',exportJson:'JSON書き出し',importJson:'JSON読込',layers:'レイヤー',addLayer:'追加',dupLayer:'複製',delLayer:'削除',brush:'ブラシ',eraser:'消しゴム',eyedropper:'スポイト',undo:'元に戻す',redo:'やり直す',zoom:'ズーム',size:'サイズ',opacity:'不透明度',visible:'表示',locked:'ロック',moveUp:'上へ',moveDown:'下へ',rename:'レイヤー名',autosaved:'自動保存',active:'使用中',empty:'保存プロジェクトなし',confirmDelete:'この外見を削除しますか？',base:'ベース',paint:'ペイント'},zh:{title:'角色工作室',project:'项目',newProject:'新建',save:'保存',duplicate:'复制',delete:'删除',exportPng:'导出PNG',exportJson:'导出项目',importJson:'导入项目',layers:'图层',addLayer:'添加图层',dupLayer:'复制图层',delLayer:'删除图层',brush:'画笔',eraser:'橡皮擦',eyedropper:'吸管',undo:'撤销',redo:'重做',zoom:'缩放',size:'大小',opacity:'不透明度',visible:'显示',locked:'锁定',moveUp:'上移',moveDown:'下移',rename:'图层名称',autosaved:'已自动保存',active:'正在使用',empty:'暂无保存项目',confirmDelete:'删除这个外观项目？',base:'基础',paint:'绘画'}};
const t=k=>L[lang()]?.[k]||L.en[k]||k;
const uid=()=>`p_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`;
const read=()=>{try{const v=JSON.parse(localStorage.getItem(STORAGE)||'[]');return Array.isArray(v)?v:[]}catch{return[]}};
const write=v=>{try{localStorage.setItem(STORAGE,JSON.stringify(v));return true}catch{return false}};
const dataOk=v=>typeof v==='string'&&v.startsWith('data:image/');
function baseBitmap(){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d');x.fillStyle='#dceaf5';x.beginPath();x.arc(256,256,150,0,Math.PI*2);x.fill();x.fillStyle='#15202b';x.beginPath();x.arc(210,230,16,0,Math.PI*2);x.arc(302,230,16,0,Math.PI*2);x.fill();x.strokeStyle='#60778a';x.lineWidth=7;x.beginPath();x.arc(256,272,58,.15*Math.PI,.85*Math.PI);x.stroke();return c.toDataURL('image/webp',.9)}
function blankBitmap(){const c=document.createElement('canvas');c.width=c.height=512;return c.toDataURL('image/png')}
function normalizeProject(p){if(!p||typeof p!=='object')return null;const layers=Array.isArray(p.layers)?p.layers.filter(x=>x&&dataOk(x.bitmap)).map((x,i)=>({id:x.id||uid(),name:String(x.name||`Layer ${i+1}`).slice(0,40),visible:x.visible!==false,locked:!!x.locked,opacity:Math.max(0,Math.min(1,Number(x.opacity??1))),bitmap:x.bitmap})):[];if(!layers.length)layers.push({id:uid(),name:t('base'),visible:true,locked:false,opacity:1,bitmap:baseBitmap()});return{id:p.id||uid(),name:String(p.name||'Untitled').slice(0,40),updatedAt:Number(p.updatedAt)||Date.now(),layers,selectedLayer:layers.some(x=>x.id===p.selectedLayer)?p.selectedLayer:layers.at(-1).id}}
function defaultProject(){const base={id:uid(),name:t('base'),visible:true,locked:false,opacity:1,bitmap:baseBitmap()},paint={id:uid(),name:t('paint'),visible:true,locked:false,opacity:1,bitmap:blankBitmap()};return{id:uid(),name:'My Look',updatedAt:Date.now(),layers:[base,paint],selectedLayer:paint.id}}
let mounted=null;
function projectThumb(p){return flattenProject(p,160).toDataURL('image/webp',.72)}
function flattenProject(p,size=512){const out=document.createElement('canvas');out.width=out.height=size;const x=out.getContext('2d');for(const l of p.layers){if(!l.visible||!dataOk(l.bitmap))continue;const img=new Image();img.src=l.bitmap;try{x.globalAlpha=l.opacity;x.drawImage(img,0,0,size,size)}catch{}}x.globalAlpha=1;return out}
function loadImages(p,done){let left=p.layers.length;if(!left)return done();for(const l of p.layers){const img=new Image();img.onload=img.onerror=()=>{l._img=img;if(!--left)done()};img.src=l.bitmap}}
function mount(host){if(mounted===host)return;mounted=host;const old=host.querySelector('.custom-grid');if(!old)return;const projects=read().map(normalizeProject).filter(Boolean);let activeId=localStorage.getItem(ACTIVE),current=projects.find(p=>p.id===activeId)||projects[0]||defaultProject();if(!projects.some(p=>p.id===current.id)){projects.push(current);write(projects)}activeId=current.id;localStorage.setItem(ACTIVE,activeId);
 old.outerHTML=`<div class="ps-editor" id="rbfPsEditor"><header class="ps-toolbar"><div class="ps-project"><input id="psProjectName" class="input" maxlength="40"><button class="btn" data-act="new">${t('newProject')}</button><button class="btn primary" data-act="save">${t('save')}</button><button class="btn" data-act="duplicate">${t('duplicate')}</button><button class="btn danger" data-act="delete">${t('delete')}</button></div><div class="ps-tools"><button class="btn primary" data-tool="brush">✎ ${t('brush')}</button><button class="btn" data-tool="eraser">⌫ ${t('eraser')}</button><button class="btn" data-tool="eyedropper">◉ ${t('eyedropper')}</button><button class="btn" data-act="undo">↶ ${t('undo')}</button><button class="btn" data-act="redo">↷ ${t('redo')}</button></div><div class="ps-controls"><input id="psColor" type="color" value="#74d3ff"><label>${t('size')} <input id="psSize" type="range" min="1" max="80" value="12"></label><label>${t('zoom')} <input id="psZoom" type="range" min="50" max="300" value="100"></label><span id="psZoomText">100%</span></div></header><div class="ps-main"><aside class="ps-projects"><div class="section-heading"><h3>${t('project')}</h3><button class="btn tiny" data-act="import">${t('importJson')}</button></div><div id="psProjectList" class="ps-project-list"></div><button class="btn full" data-act="exportJson">${t('exportJson')}</button><button class="btn full" data-act="exportPng">${t('exportPng')}</button><input id="psImport" type="file" accept="application/json" hidden></aside><section class="ps-stage"><div class="ps-checker"><div id="psCanvasStack" class="ps-canvas-stack"><canvas id="psComposite" width="512" height="512"></canvas><canvas id="psPaint" width="512" height="512"></canvas></div></div><div id="psStatus" class="muted"></div></section><aside class="ps-layers"><div class="section-heading"><h3>${t('layers')}</h3><button class="btn tiny" data-act="addLayer">+ ${t('addLayer')}</button></div><div id="psLayerList" class="ps-layer-list"></div><div class="ps-layer-actions"><button class="btn" data-act="dupLayer">${t('dupLayer')}</button><button class="btn danger" data-act="delLayer">${t('delLayer')}</button><button class="btn" data-act="up">↑</button><button class="btn" data-act="down">↓</button></div><label>${t('opacity')} <input id="psOpacity" type="range" min="0" max="100" value="100"></label></aside></div></div>`;
 const E=id=>host.querySelector(`#${id}`),comp=E('psComposite'),paint=E('psPaint'),cx=comp.getContext('2d'),px=paint.getContext('2d'),stack=E('psCanvasStack'),status=E('psStatus');let tool='brush',drawing=false,last=null,zoom=1,history=[],redo=[],saveTimer=null;
 function selected(){return current.layers.find(l=>l.id===current.selectedLayer)||current.layers.at(-1)}
 function snap(){history.push(JSON.stringify(current));if(history.length>30)history.shift();redo=[]}
 function restore(raw){const p=normalizeProject(JSON.parse(raw));if(!p)return;current=p;loadImages(current,renderAll)}
 function renderComposite(){cx.clearRect(0,0,512,512);for(const l of current.layers){if(!l.visible)continue;cx.globalAlpha=l.opacity;if(l._img?.complete)cx.drawImage(l._img,0,0,512,512)}cx.globalAlpha=1}
 function renderProjectList(){const list=E('psProjectList');list.innerHTML=projects.map(p=>`<button class="ps-project-card ${p.id===current.id?'active':''}" data-project="${p.id}"><img src="${projectThumb(p)}" alt=""><span>${String(p.name).replace(/[<>]/g,'')}</span>${p.id===localStorage.getItem(ACTIVE)?`<em>${t('active')}</em>`:''}</button>`).join('')||`<p class="muted">${t('empty')}</p>`;list.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>{commitLayer();const p=projects.find(x=>x.id===b.dataset.project);if(p){current=normalizeProject(p);history=[];redo=[];loadImages(current,renderAll)}})}
 function renderLayers(){const list=E('psLayerList');list.innerHTML=[...current.layers].reverse().map(l=>`<div class="ps-layer ${l.id===current.selectedLayer?'active':''}" data-layer="${l.id}"><button class="ps-icon" data-vis title="${t('visible')}">${l.visible?'◉':'○'}</button><button class="ps-icon" data-lock title="${t('locked')}">${l.locked?'🔒':'🔓'}</button><button class="ps-layer-name" data-select>${String(l.name).replace(/[<>]/g,'')}</button></div>`).join('');list.querySelectorAll('[data-layer]').forEach(row=>{const id=row.dataset.layer;row.querySelector('[data-select]').onclick=()=>{commitLayer();current.selectedLayer=id;renderLayers();loadSelected()};row.querySelector('[data-vis]').onclick=()=>{snap();const l=current.layers.find(x=>x.id===id);l.visible=!l.visible;renderAll();queueSave()};row.querySelector('[data-lock]').onclick=()=>{const l=current.layers.find(x=>x.id===id);l.locked=!l.locked;renderLayers()}});const l=selected();E('psOpacity').value=Math.round((l?.opacity??1)*100)}
 function loadSelected(){const l=selected();px.clearRect(0,0,512,512);if(l?._img?.complete)px.drawImage(l._img,0,0,512,512)}
 function renderAll(){E('psProjectName').value=current.name;renderComposite();renderLayers();renderProjectList();loadSelected();stack.style.transform=`scale(${zoom})`;E('psZoomText').textContent=`${Math.round(zoom*100)}%`}
 function commitLayer(){const l=selected();if(!l)return;l.bitmap=paint.toDataURL('image/webp',.9);const img=new Image();img.src=l.bitmap;l._img=img;renderComposite()}
 function queueSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>save(false),700)}
 function syncCompat(){commitLayer();const flat=flattenProject(current).toDataURL('image/webp',.86);localStorage.setItem('rbf.activeAvatar',flat);const old=(()=>{try{const v=JSON.parse(localStorage.getItem('rbf.templates')||'[]');return Array.isArray(v)?v:[]}catch{return[]}})();const next=[...old.filter(x=>x!==flat),flat].slice(-12);localStorage.setItem('rbf.templates',JSON.stringify(next));localStorage.setItem(ACTIVE,current.id);window.dispatchEvent(new CustomEvent('rbf-custom-active',{detail:{preview:flat,projectId:current.id}}))}
 function save(show=true){commitLayer();current.name=E('psProjectName').value.trim()||'Untitled';current.updatedAt=Date.now();const i=projects.findIndex(p=>p.id===current.id);if(i>=0)projects[i]=JSON.parse(JSON.stringify(current,(k,v)=>k==='_img'?undefined:v));else projects.push(current);write(projects.slice(-20));syncCompat();if(show){status.textContent=t('save');setTimeout(()=>status.textContent='',1200)}renderProjectList()}
 function newProject(){commitLayer();current=defaultProject();projects.push(current);history=[];redo=[];loadImages(current,renderAll);save()}
 function duplicateProject(){commitLayer();const copy=JSON.parse(JSON.stringify(current,(k,v)=>k==='_img'?undefined:v));copy.id=uid();copy.name=`${current.name} Copy`;copy.updatedAt=Date.now();current=normalizeProject(copy);projects.push(current);loadImages(current,()=>{renderAll();save()})}
 async function deleteProject(){if(projects.length<=1){newProject();projects.splice(0,1);return}const ok=window.rbfModal?await window.rbfModal({title:t('confirmDelete'),primary:t('delete'),secondary:'Cancel',danger:true}):true;if(!ok)return;projects.splice(projects.findIndex(p=>p.id===current.id),1);current=normalizeProject(projects[0]);write(projects);loadImages(current,()=>{renderAll();save()})}
 function addLayer(){snap();commitLayer();const l={id:uid(),name:`Layer ${current.layers.length+1}`,visible:true,locked:false,opacity:1,bitmap:blankBitmap()};current.layers.push(l);current.selectedLayer=l.id;loadImages(current,()=>{renderAll();queueSave()})}
 function dupLayer(){const l=selected();if(!l)return;snap();commitLayer();const c={...l,id:uid(),name:`${l.name} Copy`,locked:false};current.layers.splice(current.layers.indexOf(l)+1,0,c);current.selectedLayer=c.id;loadImages(current,()=>{renderAll();queueSave()})}
 function delLayer(){if(current.layers.length<=1)return;const l=selected();snap();current.layers.splice(current.layers.indexOf(l),1);current.selectedLayer=current.layers.at(-1).id;renderAll();queueSave()}
 function moveLayer(dir){const l=selected(),i=current.layers.indexOf(l),j=i+dir;if(!l||j<0||j>=current.layers.length)return;snap();[current.layers[i],current.layers[j]]=[current.layers[j],current.layers[i]];renderAll();queueSave()}
 function pos(e){const r=paint.getBoundingClientRect();return{x:(e.clientX-r.left)*512/r.width,y:(e.clientY-r.top)*512/r.height}}
 paint.onpointerdown=e=>{const l=selected();if(!l||l.locked)return;const p=pos(e);if(tool==='eyedropper'){const d=comp.getContext('2d').getImageData(Math.max(0,Math.min(511,p.x|0)),Math.max(0,Math.min(511,p.y|0)),1,1).data;E('psColor').value='#'+[d[0],d[1],d[2]].map(x=>x.toString(16).padStart(2,'0')).join('');return}snap();drawing=true;last=p;paint.setPointerCapture?.(e.pointerId)};
 paint.onpointermove=e=>{if(!drawing)return;const p=pos(e),l=selected();if(!l||l.locked)return;px.save();px.lineCap='round';px.lineJoin='round';px.lineWidth=Number(E('psSize').value);px.globalCompositeOperation=tool==='eraser'?'destination-out':'source-over';px.strokeStyle=E('psColor').value;px.beginPath();px.moveTo(last.x,last.y);px.lineTo(p.x,p.y);px.stroke();px.restore();last=p;renderComposite();cx.globalAlpha=l.opacity;cx.drawImage(paint,0,0);cx.globalAlpha=1};
 paint.onpointerup=paint.onpointercancel=()=>{if(!drawing)return;drawing=false;commitLayer();queueSave()};
 host.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;host.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('primary',x===b))});
 host.querySelector('[data-act="save"]').onclick=()=>save();host.querySelector('[data-act="new"]').onclick=newProject;host.querySelector('[data-act="duplicate"]').onclick=duplicateProject;host.querySelector('[data-act="delete"]').onclick=deleteProject;host.querySelector('[data-act="addLayer"]').onclick=addLayer;host.querySelector('[data-act="dupLayer"]').onclick=dupLayer;host.querySelector('[data-act="delLayer"]').onclick=delLayer;host.querySelector('[data-act="up"]').onclick=()=>moveLayer(1);host.querySelector('[data-act="down"]').onclick=()=>moveLayer(-1);
 host.querySelector('[data-act="undo"]').onclick=()=>{if(!history.length)return;redo.push(JSON.stringify(current));restore(history.pop())};host.querySelector('[data-act="redo"]').onclick=()=>{if(!redo.length)return;history.push(JSON.stringify(current));restore(redo.pop())};
 E('psOpacity').oninput=e=>{const l=selected();if(!l)return;l.opacity=Number(e.target.value)/100;renderComposite();queueSave()};E('psProjectName').onchange=()=>save(false);E('psZoom').oninput=e=>{zoom=Number(e.target.value)/100;stack.style.transform=`scale(${zoom})`;E('psZoomText').textContent=`${e.target.value}%`};
 host.querySelector('[data-act="exportPng"]').onclick=()=>{commitLayer();const a=document.createElement('a');a.href=flattenProject(current).toDataURL('image/png');a.download=`${current.name||'look'}.png`;a.click()};host.querySelector('[data-act="exportJson"]').onclick=()=>{commitLayer();const blob=new Blob([JSON.stringify(current,(k,v)=>k==='_img'?undefined:v,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${current.name||'look'}.rbf-look.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};host.querySelector('[data-act="import"]').onclick=()=>E('psImport').click();E('psImport').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=normalizeProject(JSON.parse(r.result));if(!p)throw 0;p.id=uid();projects.push(p);current=p;loadImages(current,()=>{renderAll();save()})}catch{status.textContent='Invalid project'}};r.readAsText(f)};
 window.addEventListener('keydown',function keys(e){if(!document.getElementById('rbfPsEditor'))return;const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?host.querySelector('[data-act="redo"]').click():host.querySelector('[data-act="undo"]').click()}if(mod&&e.key.toLowerCase()==='s'){e.preventDefault();save()}if(!mod&&document.activeElement?.tagName!=='INPUT'){if(e.key.toLowerCase()==='b')host.querySelector('[data-tool="brush"]').click();if(e.key.toLowerCase()==='e')host.querySelector('[data-tool="eraser"]').click();if(e.key.toLowerCase()==='i')host.querySelector('[data-tool="eyedropper"]').click()}});
 loadImages(current,()=>{renderAll();syncCompat()});
}
const obs=new MutationObserver(()=>{const c=document.querySelector('.custom-grid');if(c&&!c.closest('#rbfPsEditor'))mount(c.closest('.content')||document)});obs.observe(document.getElementById('appRoot'),{childList:true,subtree:true});
window.addEventListener('rbf-start-game',e=>{const active=localStorage.getItem('rbf.activeAvatar');if(e.detail&&dataOk(active))e.detail.custom=active});
