import {WORLD,PLAYER,BUILDINGS,ENEMIES,AI_ROLES} from './config.js';

const canvas=document.getElementById('gameCanvas');
const ctx=canvas.getContext('2d');
const ui={heartHp:document.getElementById('heartHp'),heartBar:document.getElementById('heartBar'),waveText:document.getElementById('waveText'),phaseText:document.getElementById('phaseText'),woodText:document.getElementById('woodText'),stoneText:document.getElementById('stoneText'),crystalText:document.getElementById('crystalText'),teamText:document.getElementById('teamText'),scoreText:document.getElementById('scoreText'),dashText:document.getElementById('dashText'),dashBar:document.getElementById('dashBar'),buildList:document.getElementById('buildList'),buildInfo:document.getElementById('buildInfo'),squadList:document.getElementById('squadList'),banner:document.getElementById('banner'),toast:document.getElementById('toast')};
const state={time:0,last:performance.now(),keys:new Set(),mouse:{x:0,y:0,down:false},camera:{x:0,y:0},phase:'prep',phaseTime:WORLD.prepSeconds,wave:0,score:0,resources:{wood:90,stone:70,crystal:15},selectedBuild:null,gameOver:false,weaponLevel:1,aiLevel:1,heart:{...WORLD.heart,hp:WORLD.heart.maxHp},bullets:[],enemyBullets:[],enemies:[],buildings:[],nodes:[],particles:[],ais:[],player:null};

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const rand=(a,b)=>a+Math.random()*(b-a);
const norm=(x,y)=>{const m=Math.hypot(x,y)||1;return{x:x/m,y:y/m};};
const grid=()=>WORLD.gridSize;

function makePlayer(){return{x:WORLD.heart.x,y:WORLD.heart.y+120,radius:PLAYER.radius,hp:PLAYER.maxHp,maxHp:PLAYER.maxHp,angle:0,shootCd:0,dashCd:0,dashT:0,dashTrailCd:0,color:'#e9f4ff'};}
function makeAI(i){const spec=AI_ROLES[i];return{x:WORLD.heart.x+rand(-100,100),y:WORLD.heart.y+rand(-100,100),radius:12,hp:115,maxHp:115,shootCd:0,role:spec.role,name:spec.name,color:spec.accent,gatherCd:0,repairCd:0};}
function seedWorld(){state.nodes=[];for(let i=0;i<62;i++){const ang=Math.random()*Math.PI*2,r=rand(250,980);state.nodes.push({type:Math.random()<.58?'tree':'rock',x:clamp(WORLD.heart.x+Math.cos(ang)*r,70,WORLD.width-70),y:clamp(WORLD.heart.y+Math.sin(ang)*r,70,WORLD.height-70),radius:Math.random()<.58?24:22,hp:85,maxHp:85});}}
function reset(){state.time=0;state.last=performance.now();state.phase='prep';state.phaseTime=WORLD.prepSeconds;state.wave=0;state.score=0;state.gameOver=false;state.weaponLevel=1;state.aiLevel=1;state.heart={...WORLD.heart,hp:WORLD.heart.maxHp};state.resources={wood:90,stone:70,crystal:15};state.selectedBuild=null;state.bullets=[];state.enemyBullets=[];state.enemies=[];state.buildings=[];state.particles=[];state.player=makePlayer();state.ais=AI_ROLES.map((_,i)=>makeAI(i));seedWorld();showBanner('BUILD PHASE',1500);renderBuildButtons();updateBuildInfo();}

function showBanner(text,ms=1600){ui.banner.textContent=text;ui.banner.classList.remove('hidden');clearTimeout(showBanner.t);showBanner.t=setTimeout(()=>ui.banner.classList.add('hidden'),ms);}
function toast(text){ui.toast.textContent=text;ui.toast.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>ui.toast.classList.add('hidden'),1400);}
function toggleBuildSelection(key){state.selectedBuild=state.selectedBuild===key?null:key;renderBuildButtons();updateBuildInfo();}
function renderBuildButtons(){ui.buildList.innerHTML='';Object.entries(BUILDINGS).forEach(([key,b],i)=>{const btn=document.createElement('button');btn.className='build-item'+(state.selectedBuild===key?' active':'');btn.innerHTML=`<span>${i+1}. ${b.label}</span><small>${b.wood||0}W ${b.stone||0}S ${b.crystal||0}C</small>`;btn.addEventListener('click',()=>toggleBuildSelection(key));ui.buildList.appendChild(btn);});}
function updateBuildInfo(){const b=BUILDINGS[state.selectedBuild];if(!b){ui.buildInfo.className='build-info empty';ui.buildInfo.innerHTML='<strong>건물 선택 없음</strong><p>건물을 선택하면 토대 크기와 기능 설명이 표시됩니다.</p>';return;}ui.buildInfo.className='build-info';ui.buildInfo.innerHTML=`<strong>${b.label}</strong><p>${b.description}</p><span class="footprint">토대 ${b.gridW}×${b.gridH} · ${b.gridW*b.gridH}칸</span>`;}
function renderSquad(){const p=state.player;ui.squadList.innerHTML=`<div class="squad-member player-self"><b style="color:#e9f4ff">YOU</b><small>Player · ${Math.max(0,Math.ceil(p.hp))}/${p.maxHp}</small></div>`;for(const ai of state.ais){const el=document.createElement('div');el.className='squad-member';el.innerHTML=`<b style="color:${ai.color}">${ai.name}</b><small>${ai.role} · ${Math.max(0,Math.ceil(ai.hp))}/${ai.maxHp}</small>`;ui.squadList.appendChild(el);}}

function canAfford(b){return state.resources.wood>=(b.wood||0)&&state.resources.stone>=(b.stone||0)&&state.resources.crystal>=(b.crystal||0);}
function spend(b){state.resources.wood-=b.wood||0;state.resources.stone-=b.stone||0;state.resources.crystal-=b.crystal||0;}
function footprintFromWorld(type,x,y){const b=BUILDINGS[type],g=grid();return{gx:Math.floor(x/g),gy:Math.floor(y/g),gw:b.gridW,gh:b.gridH};}
function footprintCells(fp){const cells=[];for(let y=0;y<fp.gh;y++)for(let x=0;x<fp.gw;x++)cells.push(`${fp.gx+x},${fp.gy+y}`);return cells;}
function occupiedCells(){const set=new Set();for(const b of state.buildings)for(const c of footprintCells(b))set.add(c);return set;}
function rectCircleHit(rx,ry,rw,rh,cx,cy,cr){const nx=clamp(cx,rx,rx+rw),ny=clamp(cy,ry,ry+rh);return Math.hypot(cx-nx,cy-ny)<cr;}
function buildingRect(b){const g=grid();return{x:b.gx*g,y:b.gy*g,w:b.gw*g,h:b.gh*g};}
function footprintTouchesEntity(fp,e,pad=2){const g=grid();return rectCircleHit(fp.gx*g,fp.gy*g,fp.gw*g,fp.gh*g,e.x,e.y,e.radius+pad);}
function footprintNearHeart(fp){const g=grid();return rectCircleHit(fp.gx*g,fp.gy*g,fp.gw*g,fp.gh*g,state.heart.x,state.heart.y,state.heart.radius+42);}
function placeBuilding(type,x,y,free=false,silent=false){const spec=BUILDINGS[type];if(!spec)return false;if(!free&&!canAfford(spec)){if(!silent)toast('자원이 부족합니다.');return false;}const fp=footprintFromWorld(type,x,y),g=grid();if(fp.gx<0||fp.gy<0||(fp.gx+fp.gw)*g>WORLD.width||(fp.gy+fp.gh)*g>WORLD.height){if(!silent)toast('월드 밖에는 설치할 수 없습니다.');return false;}const occupied=occupiedCells();if(footprintCells(fp).some(c=>occupied.has(c))||footprintNearHeart(fp)){if(!silent)toast('이 슬롯은 사용할 수 없습니다.');return false;}if(type==='wall'&&[state.player,...state.ais].some(e=>e.hp>0&&footprintTouchesEntity(fp,e))){if(!silent)toast('분대원이 서 있는 칸에는 벽을 설치할 수 없습니다.');return false;}if(!free)spend(spec);const visualPad=4,w=fp.gw*g+visualPad,h=fp.gh*g+visualPad;state.buildings.push({type,...fp,x:(fp.gx+fp.gw/2)*g,y:(fp.gy+fp.gh/2)*g,width:w,height:h,radius:Math.hypot(w,h)/2,hp:spec.hp,maxHp:spec.hp,powered:false,cooldown:0,color:spec.color});burst((fp.gx+fp.gw/2)*g,(fp.gy+fp.gh/2)*g,spec.color,10);return true;}
function removeAt(x,y){for(let i=state.buildings.length-1;i>=0;i--){const b=state.buildings[i],r=buildingRect(b);if(x>=r.x&&x<=r.x+r.w&&y>=r.y&&y<=r.y+r.h){const spec=BUILDINGS[b.type];state.resources.wood+=Math.floor((spec.wood||0)*.35);state.resources.stone+=Math.floor((spec.stone||0)*.35);state.buildings.splice(i,1);return;}}}
function wallBlocksCircle(x,y,radius){for(const b of state.buildings){if(b.type!=='wall'||b.hp<=0)continue;const r=buildingRect(b);if(rectCircleHit(r.x,r.y,r.w,r.h,x,y,radius))return true;}return false;}
function moveWithWalls(e,dx,dy,speed,dt,avoid=true){const d=norm(dx,dy),step=speed*dt;let moved=false;const tryMove=(mx,my)=>{let ok=false;const nx=clamp(e.x+mx*step,e.radius,WORLD.width-e.radius);if(!wallBlocksCircle(nx,e.y,e.radius)){e.x=nx;ok=true;}const ny=clamp(e.y+my*step,e.radius,WORLD.height-e.radius);if(!wallBlocksCircle(e.x,ny,e.radius)){e.y=ny;ok=true;}return ok;};moved=tryMove(d.x,d.y);if(!moved&&avoid){const side=Math.sin(state.time*3+e.x*.01)>0?1:-1;moved=tryMove(-d.y*side,d.x*side);if(!moved)tryMove(d.y*side,-d.x*side);}return moved;}
function moveToward(e,target,speed,dt){if(!target)return;moveWithWalls(e,target.x-e.x,target.y-e.y,speed,dt,true);}

function fire(origin,tx,ty,team='friendly',damage=PLAYER.damage,speed=PLAYER.bulletSpeed){const d=norm(tx-origin.x,ty-origin.y),list=team==='enemy'?state.enemyBullets:state.bullets;list.push({x:origin.x+d.x*(origin.radius||10),y:origin.y+d.y*(origin.radius||10),vx:d.x*speed,vy:d.y*speed,radius:4,life:1.5,damage,team});}
function hurt(target,amount){target.hp=Math.max(0,target.hp-amount);}
function burst(x,y,color,count=6,speed=90){for(let i=0;i<count;i++)state.particles.push({x,y,vx:rand(-speed,speed),vy:rand(-speed,speed),life:rand(.25,.7),maxLife:.7,color,size:rand(2,5),kind:'spark'});}
function dashBurst(){const p=state.player;for(let i=0;i<16;i++){const a=Math.PI*2*i/16;state.particles.push({x:p.x,y:p.y,vx:Math.cos(a)*rand(80,210),vy:Math.sin(a)*rand(80,210),life:.35,maxLife:.35,color:'#74d3ff',size:rand(3,7),kind:'dash'});} }
function dashTrail(){const p=state.player;state.particles.push({x:p.x,y:p.y,vx:0,vy:0,life:.24,maxLife:.24,color:'#74d3ff',size:p.radius*1.6,kind:'ghost'});}

function spawnWave(){state.wave++;state.phase='wave';state.phaseTime=WORLD.baseWaveSeconds+state.wave*2;const count=6+state.wave*3;for(let i=0;i<count;i++)spawnEnemy(i<Math.floor(state.wave/2)&&Math.random()<.25?'runner':Math.random()<Math.min(.12+state.wave*.02,.35)?'brute':Math.random()<.18?'spitter':'grunt',i*.35);if(state.wave%5===0)spawnEnemy('boss',2);showBanner(state.wave%5===0?`WAVE ${state.wave} · BOSS INBOUND`:`WAVE ${state.wave}`,2200);}
function spawnEnemy(type,delay=0){const edge=Math.floor(Math.random()*4);let x,y;if(edge===0){x=rand(0,WORLD.width);y=-30}else if(edge===1){x=WORLD.width+30;y=rand(0,WORLD.height)}else if(edge===2){x=rand(0,WORLD.width);y=WORLD.height+30}else{x=-30;y=rand(0,WORLD.height)}const base=ENEMIES[type],scale=1+state.wave*.09;state.enemies.push({type,x,y,spawnDelay:delay,hp:base.hp*scale,maxHp:base.hp*scale,speed:base.speed*(1+state.wave*.012),damage:base.damage*(1+state.wave*.06),radius:base.radius,reward:base.reward,color:base.color,attackCd:rand(0,.5),shootCd:rand(.2,1.1)});}
function nearestEnemy(entity,range=Infinity){let best=null,bd=range;for(const e of state.enemies){if(e.spawnDelay>0||e.hp<=0)continue;const d=dist(entity,e);if(d<bd){bd=d;best=e;}}return best;}
function nearestNode(entity,range=Infinity){let best=null,bd=range;for(const n of state.nodes){if(n.hp<=0)continue;const d=dist(entity,n);if(d<bd){bd=d;best=n;}}return best;}
function nearestDamagedBuilding(entity,range=Infinity){let best=null,bd=range;for(const b of state.buildings){if(b.hp>=b.maxHp)continue;const d=dist(entity,b);if(d<bd){bd=d;best=b;}}return best;}

function updatePlayer(dt){const p=state.player;if(p.hp<=0){p.hp=Math.min(p.maxHp,p.hp+30*dt);if(p.hp>=p.maxHp*.5){p.x=state.heart.x;p.y=state.heart.y+100;toast('전선에 복귀했습니다.');}return;}p.dashCd=Math.max(0,p.dashCd-dt);p.dashT=Math.max(0,p.dashT-dt);p.dashTrailCd=Math.max(0,p.dashTrailCd-dt);let dx=(state.keys.has('d')?1:0)-(state.keys.has('a')?1:0),dy=(state.keys.has('s')?1:0)-(state.keys.has('w')?1:0);if(dx||dy)moveWithWalls(p,dx,dy,p.dashT>0?PLAYER.dashSpeed:PLAYER.speed,dt,false);if(p.dashT>0&&p.dashTrailCd<=0){dashTrail();p.dashTrailCd=.025;}p.shootCd=Math.max(0,p.shootCd-dt);const aim=screenToWorld(state.mouse.x,state.mouse.y);p.angle=Math.atan2(aim.y-p.y,aim.x-p.x);if(state.mouse.down&&!state.selectedBuild&&p.shootCd<=0){fire(p,aim.x,aim.y,'friendly',PLAYER.damage*(1+(state.weaponLevel-1)*.28));p.shootCd=PLAYER.fireRate/(1+(state.weaponLevel-1)*.08);}}
function updateAI(dt){for(const ai of state.ais){if(ai.hp<=0){ai.hp+=18*dt;if(ai.hp>=ai.maxHp*.55){ai.x=state.heart.x+rand(-65,65);ai.y=state.heart.y+rand(-65,65);}continue;}ai.shootCd=Math.max(0,ai.shootCd-dt);ai.gatherCd=Math.max(0,ai.gatherCd-dt);ai.repairCd=Math.max(0,ai.repairCd-dt);const threatRange=ai.role==='Vanguard'?520:330+state.aiLevel*25;const enemy=nearestEnemy(ai,threatRange);if(enemy){const d=dist(ai,enemy);if(d>210)moveToward(ai,enemy,ai.role==='Vanguard'?160:130,dt);if(d<300&&ai.shootCd<=0){fire(ai,enemy.x,enemy.y,'friendly',18*(1+(state.aiLevel-1)*.25),620);ai.shootCd=.5/(1+(state.aiLevel-1)*.09);}continue;}if(ai.role==='Builder'){const damaged=nearestDamagedBuilding(ai,480);if(damaged){moveToward(ai,damaged,120,dt);if(dist(ai,damaged)<55&&ai.repairCd<=0){damaged.hp=Math.min(damaged.maxHp,damaged.hp+15+state.aiLevel*3);ai.repairCd=.22;}continue;}const node=nearestNode(ai,360);if(node&&state.phase!=='wave'){moveToward(ai,node,115,dt);if(dist(ai,node)<45&&ai.gatherCd<=0){node.hp-=18;ai.gatherCd=.5;if(node.hp<=0)harvestNode(node,ai);}continue;}}if(ai.role==='Gatherer'&&state.phase!=='wave'){const node=nearestNode(ai,650);if(node){moveToward(ai,node,128,dt);if(dist(ai,node)<45&&ai.gatherCd<=0){node.hp-=25;ai.gatherCd=.42;if(node.hp<=0)harvestNode(node,ai);}continue;}}const idx=state.ais.indexOf(ai),guard={x:state.heart.x+Math.cos(idx*2.1)*120,y:state.heart.y+Math.sin(idx*2.1)*120};moveToward(ai,guard,115,dt);}}
function harvestNode(n,who){if(n.type==='tree')state.resources.wood+=22;else state.resources.stone+=18;if(Math.random()<.18)state.resources.crystal+=1+Math.floor(Math.random()*2);burst(n.x,n.y,n.type==='tree'?'#5e9a67':'#8b929a',12);n.hp=0;setTimeout(()=>{n.x=rand(80,WORLD.width-80);n.y=rand(80,WORLD.height-80);n.hp=n.maxHp;},12000+Math.random()*9000);if(who===state.player)state.score+=2;}
function updateNodes(dt){for(const n of state.nodes){if(n.hp<=0)continue;if(state.player.hp>0&&state.mouse.down&&!state.selectedBuild&&dist(state.player,n)<76&&Math.random()<dt*4){n.hp-=14;if(n.hp<=0)harvestNode(n,state.player);}}}
function updateBuildings(dt){for(const b of state.buildings)b.powered=b.type==='generator'||state.buildings.some(g=>g.type==='generator'&&g.hp>0&&dist(b,g)<300);for(const b of state.buildings){if(b.hp<=0)continue;b.cooldown=Math.max(0,b.cooldown-dt);if(b.type==='turret'){const e=nearestEnemy(b,b.powered?370:270);if(e&&b.cooldown<=0){fire({...b,radius:10},e.x,e.y,'friendly',b.powered?25:17,700);b.cooldown=b.powered?.36:.58;}}else if(b.type==='trap'){for(const e of state.enemies)if(e.spawnDelay<=0&&dist(b,e)<42+e.radius)e.hp-=(b.powered?62:38)*dt;}}state.buildings=state.buildings.filter(b=>{if(b.hp>0)return true;burst(b.x,b.y,'#8b7b70',16);return false;});}
function chooseEnemyTarget(e){let target=state.heart,bd=dist(e,state.heart);for(const b of state.buildings){if(b.hp<=0)continue;const d=dist(e,b);if(d<105&&d<bd){target=b;bd=d;}}for(const c of [state.player,...state.ais])if(c.hp>0){const d=dist(e,c);if(d<80&&d<bd){target=c;bd=d;}}return target;}
function updateEnemies(dt){for(const e of state.enemies){if(e.spawnDelay>0){e.spawnDelay-=dt;continue;}e.attackCd=Math.max(0,e.attackCd-dt);e.shootCd=Math.max(0,e.shootCd-dt);const target=chooseEnemyTarget(e),d=dist(e,target);if(e.type==='spitter'&&d<300&&e.shootCd<=0){fire(e,target.x,target.y,'enemy',e.damage,380);e.shootCd=1.45;}else if(d<(target.radius||35)+e.radius+10){if(e.attackCd<=0){hurt(target,e.damage);e.attackCd=e.type==='boss'?.65:.9;burst(target.x,target.y,e.color,4);}}else{const dir=norm(target.x-e.x,target.y-e.y);e.x+=dir.x*e.speed*dt;e.y+=dir.y*e.speed*dt;}}for(let i=state.enemies.length-1;i>=0;i--){const e=state.enemies[i];if(e.hp<=0){state.resources.crystal+=e.reward;state.score+=e.reward*10;burst(e.x,e.y,e.color,e.type==='boss'?30:10);state.enemies.splice(i,1);}}}
function updateBullets(list,dt,isEnemy=false){for(let i=list.length-1;i>=0;i--){const b=list[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;let hit=false;if(isEnemy){for(const t of [state.player,...state.ais])if(t.hp>0&&dist(b,t)<b.radius+t.radius){hurt(t,b.damage);hit=true;break;}if(!hit&&dist(b,state.heart)<b.radius+state.heart.radius){hurt(state.heart,b.damage);hit=true;}}else for(const e of state.enemies)if(e.spawnDelay<=0&&dist(b,e)<b.radius+e.radius){hurt(e,b.damage);hit=true;break;}if(hit||b.life<=0||b.x<0||b.y<0||b.x>WORLD.width||b.y>WORLD.height){if(hit)burst(b.x,b.y,isEnemy?'#e87e7e':'#d9f6ff',3);list.splice(i,1);}}}
function updatePhase(dt){state.phaseTime-=dt;if(state.gameOver)return;if(state.heart.hp<=0){state.gameOver=true;showBanner(`HEART LOST · SCORE ${state.score}`,100000);return;}if(state.phase==='prep'&&state.phaseTime<=0){state.phase='warning';state.phaseTime=WORLD.warningSeconds;showBanner('⚠ MASS MOVEMENT DETECTED',2500);}else if(state.phase==='warning'&&state.phaseTime<=0)spawnWave();else if(state.phase==='wave'&&(state.phaseTime<=0||state.enemies.length===0)){state.phase='prep';state.phaseTime=Math.max(22,WORLD.prepSeconds-state.wave*.8);state.resources.wood+=15;state.resources.stone+=12;state.resources.crystal+=3;showBanner('WAVE CLEARED · REBUILD',1700);}}
function updateCamera(){state.camera.x=clamp(state.player.x-canvas.width/2,0,WORLD.width-canvas.width);state.camera.y=clamp(state.player.y-canvas.height/2,0,WORLD.height-canvas.height);}
function screenToWorld(sx,sy){const r=canvas.getBoundingClientRect();return{x:(sx-r.left)*(canvas.width/r.width)+state.camera.x,y:(sy-r.top)*(canvas.height/r.height)+state.camera.y};}
function updateUI(){ui.heartHp.textContent=`${Math.ceil(state.heart.hp)} / ${state.heart.maxHp}`;ui.heartBar.style.width=`${clamp(state.heart.hp/state.heart.maxHp*100,0,100)}%`;ui.waveText.textContent=state.wave?`Wave ${state.wave}`:'준비 중';ui.phaseText.textContent=`${state.phase==='prep'?'탐색/건축':state.phase==='warning'?'경고':'침공'} · ${Math.max(0,Math.ceil(state.phaseTime))}s`;ui.woodText.textContent=Math.floor(state.resources.wood);ui.stoneText.textContent=Math.floor(state.resources.stone);ui.crystalText.textContent=Math.floor(state.resources.crystal);ui.scoreText.textContent=`Score ${state.score}`;const ratio=clamp(1-state.player.dashCd/PLAYER.dashCooldown,0,1);ui.dashBar.style.width=`${ratio*100}%`;ui.dashText.textContent=state.player.dashCd<=0?'READY':`${state.player.dashCd.toFixed(1)}s`;ui.dashText.closest('.dash-card')?.classList.toggle('ready',state.player.dashCd<=0);renderSquad();}

function drawGrid(){ctx.fillStyle='#0e1820';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.save();ctx.translate(-state.camera.x,-state.camera.y);ctx.strokeStyle='rgba(91,125,142,.08)';ctx.lineWidth=1;for(let x=0;x<WORLD.width;x+=grid()){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,WORLD.height);ctx.stroke();}for(let y=0;y<WORLD.height;y+=grid()){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(WORLD.width,y);ctx.stroke();}ctx.restore();}
function drawCircle(o,color,outline=null){ctx.beginPath();ctx.arc(o.x-state.camera.x,o.y-state.camera.y,o.radius,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();if(outline){ctx.strokeStyle=outline;ctx.lineWidth=2;ctx.stroke();}}
function drawHealth(o){if(o.hp>=o.maxHp)return;const w=(o.radius||20)*2,x=o.x-state.camera.x-w/2,y=o.y-state.camera.y-(o.radius||20)-10;ctx.fillStyle='#371d22';ctx.fillRect(x,y,w,4);ctx.fillStyle='#77df9d';ctx.fillRect(x,y,w*clamp(o.hp/o.maxHp,0,1),4);}
function render(){drawGrid();ctx.save();ctx.translate(-state.camera.x,-state.camera.y);for(const n of state.nodes){if(n.hp<=0)continue;ctx.fillStyle=n.type==='tree'?'#395d43':'#68717a';ctx.beginPath();ctx.arc(n.x,n.y,n.radius,0,Math.PI*2);ctx.fill();if(n.type==='tree'){ctx.fillStyle='#644b39';ctx.fillRect(n.x-4,n.y+12,8,18);}}for(const b of state.buildings){const r=buildingRect(b),pad=2;ctx.fillStyle=b.color;ctx.fillRect(r.x-pad,r.y-pad,r.w+pad*2,r.h+pad*2);ctx.strokeStyle=b.powered?'#b7f1ff':'#2f3d4b';ctx.lineWidth=b.powered?2:1;ctx.strokeRect(r.x-pad,r.y-pad,r.w+pad*2,r.h+pad*2);if(b.type==='turret'){ctx.fillStyle='#20313e';ctx.beginPath();ctx.arc(b.x,b.y,8,0,Math.PI*2);ctx.fill();}if(b.type==='generator'){ctx.fillStyle='rgba(130,210,255,.08)';ctx.beginPath();ctx.arc(b.x,b.y,300,0,Math.PI*2);ctx.fill();}}ctx.restore();drawCircle(state.heart,'#77d7ff','#d9f6ff');ctx.font='bold 12px system-ui';ctx.textAlign='center';ctx.fillStyle='#e9fbff';ctx.fillText('HEART',state.heart.x-state.camera.x,state.heart.y-state.camera.y+4);for(const e of state.enemies){if(e.spawnDelay>0)continue;drawCircle(e,e.color,e.type==='boss'?'#ffd0df':null);drawHealth(e);}for(const ai of state.ais){if(ai.hp<=0)continue;drawCircle(ai,ai.color);ctx.fillStyle='#dce9f5';ctx.font='10px system-ui';ctx.fillText(ai.name,ai.x-state.camera.x,ai.y-state.camera.y-20);drawHealth(ai);}if(state.player.hp>0){drawCircle(state.player,state.player.color,'#74d3ff');ctx.strokeStyle='#74d3ff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(state.player.x-state.camera.x,state.player.y-state.camera.y);ctx.lineTo(state.player.x-state.camera.x+Math.cos(state.player.angle)*25,state.player.y-state.camera.y+Math.sin(state.player.angle)*25);ctx.stroke();drawHealth(state.player);}for(const b of state.bullets)drawCircle(b,'#d9f6ff');for(const b of state.enemyBullets)drawCircle(b,'#ff9d9d');for(const p of state.particles){const alpha=clamp(p.life/(p.maxLife||.7),0,1);ctx.globalAlpha=p.kind==='ghost'?alpha*.3:alpha;ctx.fillStyle=p.color;if(p.kind==='ghost'){ctx.beginPath();ctx.arc(p.x-state.camera.x,p.y-state.camera.y,p.size,0,Math.PI*2);ctx.fill();}else ctx.fillRect(p.x-state.camera.x,p.y-state.camera.y,p.size,p.size);ctx.globalAlpha=1;}if(state.selectedBuild){const w=screenToWorld(state.mouse.x,state.mouse.y),fp=footprintFromWorld(state.selectedBuild,w.x,w.y),spec=BUILDINGS[state.selectedBuild],g=grid(),occupied=occupiedCells(),valid=!footprintCells(fp).some(c=>occupied.has(c))&&!footprintNearHeart(fp);ctx.globalAlpha=.38;ctx.fillStyle=valid?spec.color:'#d95e66';ctx.fillRect(fp.gx*g-state.camera.x,fp.gy*g-state.camera.y,fp.gw*g,fp.gh*g);ctx.globalAlpha=1;}if(state.gameOver){ctx.fillStyle='rgba(0,0,0,.45)';ctx.fillRect(0,0,canvas.width,canvas.height);}}
function step(now){const dt=Math.min((now-state.last)/1000,.033);state.last=now;if(!state.gameOver){state.time+=dt;updatePlayer(dt);updateAI(dt);updateNodes(dt);updateBuildings(dt);updateEnemies(dt);updateBullets(state.bullets,dt,false);updateBullets(state.enemyBullets,dt,true);updatePhase(dt);for(let i=state.particles.length-1;i>=0;i--){const p=state.particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.life<=0)state.particles.splice(i,1);}updateCamera();updateUI();}render();requestAnimationFrame(step);}

window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();state.keys.add(k);if(['1','2','3','4'].includes(k))toggleBuildSelection(Object.keys(BUILDINGS)[Number(k)-1]);if(e.code==='Space'&&state.player.dashCd<=0&&state.player.hp>0){state.player.dashCd=PLAYER.dashCooldown;state.player.dashT=PLAYER.dashDuration;dashBurst();e.preventDefault();}});window.addEventListener('keyup',e=>state.keys.delete(e.key.toLowerCase()));
canvas.addEventListener('mousemove',e=>{state.mouse.x=e.clientX;state.mouse.y=e.clientY;});canvas.addEventListener('mousedown',e=>{state.mouse.x=e.clientX;state.mouse.y=e.clientY;if(e.button===0){if(state.selectedBuild){const w=screenToWorld(e.clientX,e.clientY);placeBuilding(state.selectedBuild,w.x,w.y);}else state.mouse.down=true;}else if(e.button===2){const w=screenToWorld(e.clientX,e.clientY);removeAt(w.x,w.y);}});window.addEventListener('mouseup',e=>{if(e.button===0)state.mouse.down=false;});canvas.addEventListener('contextmenu',e=>e.preventDefault());
document.getElementById('helpButton').addEventListener('click',()=>document.getElementById('helpDialog').showModal());document.getElementById('restartButton').addEventListener('click',reset);document.getElementById('upgradeWeapon').addEventListener('click',()=>{if(state.resources.crystal<25)return toast('Crystal이 부족합니다.');state.resources.crystal-=25;state.weaponLevel++;toast(`무기 Lv.${state.weaponLevel}`);});document.getElementById('upgradeHeart').addEventListener('click',()=>{if(state.resources.crystal<40)return toast('Crystal이 부족합니다.');state.resources.crystal-=40;state.heart.maxHp+=220;state.heart.hp=Math.min(state.heart.maxHp,state.heart.hp+220);toast(`HEART 최대 체력 ${state.heart.maxHp}`);});document.getElementById('upgradeTeam').addEventListener('click',()=>{if(state.resources.crystal<30)return toast('Crystal이 부족합니다.');state.resources.crystal-=30;state.aiLevel++;toast(`AI 훈련 Lv.${state.aiLevel}`);});

reset();requestAnimationFrame(step);
