import {WORLD,PLAYER,BUILDINGS,ENEMIES,AI_PLAYERS,RESEARCH} from './config.js';

const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d'),$=id=>document.getElementById(id);
const ui={heartHp:$('heartHp'),heartBar:$('heartBar'),waveText:$('waveText'),phaseText:$('phaseText'),woodText:$('woodText'),stoneText:$('stoneText'),crystalText:$('crystalText'),teamText:$('teamText'),scoreText:$('scoreText'),dashText:$('dashText'),dashBar:$('dashBar'),weaponText:$('weaponText'),buildList:$('buildList'),buildInfo:$('buildInfo'),squadList:$('squadList'),researchList:$('researchList'),banner:$('banner'),toast:$('toast')};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),rand=(a,b)=>a+Math.random()*(b-a),norm=(x,y)=>{const m=Math.hypot(x,y)||1;return{x:x/m,y:y/m};},grid=()=>WORLD.gridSize;
const state={last:performance.now(),time:0,keys:new Set(),mouse:{x:0,y:0,down:false},camera:{x:0,y:0},phase:'prep',phaseTime:WORLD.prepSeconds,wave:0,score:0,resources:{wood:90,stone:70,crystal:15},selectedBuild:null,research:new Set(),weapon:'sword',gameOver:false,heart:null,player:null,ais:[],buildings:[],nodes:[],enemies:[],bullets:[],enemyBullets:[],particles:[]};

const hasResearch=id=>state.research.has(id);
const wallHpMultiplier=()=>1+(hasResearch('wallI')?.35:0)+(hasResearch('wallII')?.35:0);
const structureDamage=amount=>amount*(hasResearch('fortify')?.8:1);
function makePlayer(){return{x:WORLD.heart.x,y:WORLD.heart.y+120,radius:PLAYER.radius,hp:PLAYER.maxHp,maxHp:PLAYER.maxHp,angle:0,attackCd:0,dashCd:0,dashT:0,dashTrailCd:0,color:'#e9f4ff',name:'YOU'};}
function makeAI(i){const s=AI_PLAYERS[i];return{x:WORLD.heart.x+rand(-100,100),y:WORLD.heart.y+rand(-100,100),radius:12,hp:115,maxHp:115,attackCd:rand(0,.4),repairCd:0,gatherCd:0,color:s.accent,name:s.name,aim:{x:1,y:0}};}
function seedWorld(){state.nodes=[];for(let i=0;i<64;i++){const a=Math.random()*Math.PI*2,r=rand(260,990),tree=Math.random()<.58;state.nodes.push({type:tree?'tree':'rock',x:clamp(WORLD.heart.x+Math.cos(a)*r,70,WORLD.width-70),y:clamp(WORLD.heart.y+Math.sin(a)*r,70,WORLD.height-70),radius:tree?24:22,hp:85,maxHp:85});}}
function reset(){Object.assign(state,{time:0,last:performance.now(),phase:'prep',phaseTime:WORLD.prepSeconds,wave:0,score:0,resources:{wood:90,stone:70,crystal:15},selectedBuild:null,research:new Set(),weapon:'sword',gameOver:false,heart:{...WORLD.heart,hp:WORLD.heart.maxHp,maxHp:WORLD.heart.maxHp},player:makePlayer(),ais:AI_PLAYERS.map((_,i)=>makeAI(i)),buildings:[],enemies:[],bullets:[],enemyBullets:[],particles:[]});seedWorld();renderBuildButtons();renderResearch();updateBuildInfo();showBanner('BUILD PHASE',1400);}
function showBanner(t,ms=1500){ui.banner.textContent=t;ui.banner.classList.remove('hidden');clearTimeout(showBanner.t);showBanner.t=setTimeout(()=>ui.banner.classList.add('hidden'),ms);}
function toast(t){ui.toast.textContent=t;ui.toast.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>ui.toast.classList.add('hidden'),1300);}

function buildingUnlocked(key){const r=BUILDINGS[key].research;return !r||hasResearch(r);}
function toggleBuild(key){if(!buildingUnlocked(key))return toast(`${BUILDINGS[key].label}: 연구가 필요합니다.`);state.selectedBuild=state.selectedBuild===key?null:key;renderBuildButtons();updateBuildInfo();}
function renderBuildButtons(){ui.buildList.innerHTML='';Object.entries(BUILDINGS).forEach(([key,b],i)=>{const locked=!buildingUnlocked(key),btn=document.createElement('button');btn.className='build-item'+(state.selectedBuild===key?' active':'')+(locked?' locked':'');btn.disabled=locked;btn.innerHTML=`<span>${i+1}. ${b.label}${locked?' 🔒':''}</span><small>${b.wood||0}W ${b.stone||0}S ${b.crystal||0}C</small>`;btn.addEventListener('click',()=>toggleBuild(key));ui.buildList.appendChild(btn);});}
function updateBuildInfo(){const b=BUILDINGS[state.selectedBuild];if(!b){ui.buildInfo.className='build-info empty';ui.buildInfo.innerHTML='<strong>건물 선택 없음</strong><p>벽과 함정은 처음부터, 터렛과 발전기는 연구 후 사용할 수 있습니다.</p>';return;}ui.buildInfo.className='build-info';ui.buildInfo.innerHTML=`<strong>${b.label}</strong><p>${b.description}</p><span class="footprint">토대 ${b.gridW}×${b.gridH} · ${b.gridW*b.gridH}칸</span>`;}
function renderSquad(){ui.squadList.innerHTML='';for(const m of[state.player,...state.ais]){const d=document.createElement('div');d.className='squad-member'+(m===state.player?' player-self':'');d.innerHTML=`<b style="color:${m.color}">${m.name}</b><small>${Math.max(0,Math.ceil(m.hp))}/${m.maxHp}</small>`;ui.squadList.appendChild(d);}}
function renderResearch(){ui.researchList.innerHTML='';for(const[id,r]of Object.entries(RESEARCH)){const done=hasResearch(id),ready=(r.requires||[]).every(hasResearch),btn=document.createElement('button');btn.className='research-item'+(done?' done':'');btn.disabled=done||!ready;btn.innerHTML=`<span><b>${r.label}</b><small>${r.branch}</small></span><em>${done?'완료':`${r.cost}C`}</em><p>${r.description}</p>`;btn.addEventListener('click',()=>buyResearch(id));ui.researchList.appendChild(btn);}}
function buyResearch(id){const r=RESEARCH[id];if(!r||hasResearch(id))return;if((r.requires||[]).some(x=>!hasResearch(x)))return toast('선행 연구가 필요합니다.');if(state.resources.crystal<r.cost)return toast('Crystal이 부족합니다.');state.resources.crystal-=r.cost;state.research.add(id);if(id==='wallI'||id==='wallII')for(const b of state.buildings){if(b.type==='wall'){const ratio=b.hp/b.maxHp;b.maxHp=BUILDINGS.wall.hp*wallHpMultiplier();b.hp=b.maxHp*ratio;}}if(id==='corePlating'){state.heart.maxHp+=350;state.heart.hp=Math.min(state.heart.maxHp,state.heart.hp+350);}if(id==='squadTraining')for(const a of state.ais){a.maxHp+=35;a.hp+=35;}renderResearch();renderBuildButtons();updateBuildInfo();toast(`${r.label} 연구 완료`);}

function footprint(type,x,y){const b=BUILDINGS[type];return{gx:Math.floor(x/grid()),gy:Math.floor(y/grid()),gw:b.gridW,gh:b.gridH};}
function cells(fp){const out=[];for(let y=0;y<fp.gh;y++)for(let x=0;x<fp.gw;x++)out.push(`${fp.gx+x},${fp.gy+y}`);return out;}
function rect(b){return{x:b.gx*grid(),y:b.gy*grid(),w:b.gw*grid(),h:b.gh*grid()};}
function circleRectHit(cx,cy,cr,r){const nx=clamp(cx,r.x,r.x+r.w),ny=clamp(cy,r.y,r.y+r.h);return Math.hypot(cx-nx,cy-ny)<cr;}
function occupied(){const s=new Set();for(const b of state.buildings)for(const c of cells(b))s.add(c);return s;}
function nearHeart(fp){return circleRectHit(state.heart.x,state.heart.y,state.heart.radius+42,{x:fp.gx*grid(),y:fp.gy*grid(),w:fp.gw*grid(),h:fp.gh*grid()});}
function placeBuilding(type,x,y,silent=false){const spec=BUILDINGS[type];if(!spec||!buildingUnlocked(type))return false;if(state.resources.wood<(spec.wood||0)||state.resources.stone<(spec.stone||0)||state.resources.crystal<(spec.crystal||0)){if(!silent)toast('자원이 부족합니다.');return false;}const fp=footprint(type,x,y),used=occupied();if(fp.gx<0||fp.gy<0||(fp.gx+fp.gw)*grid()>WORLD.width||(fp.gy+fp.gh)*grid()>WORLD.height||nearHeart(fp)||cells(fp).some(c=>used.has(c))){if(!silent)toast('이 슬롯은 사용할 수 없습니다.');return false;}if(type==='wall'&&[state.player,...state.ais].some(e=>e.hp>0&&circleRectHit(e.x,e.y,e.radius+2,{x:fp.gx*grid(),y:fp.gy*grid(),w:fp.gw*grid(),h:fp.gh*grid()}))){if(!silent)toast('플레이어가 서 있는 칸입니다.');return false;}state.resources.wood-=spec.wood||0;state.resources.stone-=spec.stone||0;state.resources.crystal-=spec.crystal||0;const maxHp=spec.hp*(type==='wall'?wallHpMultiplier():1),w=fp.gw*grid()+4,h=fp.gh*grid()+4;state.buildings.push({type,...fp,x:(fp.gx+fp.gw/2)*grid(),y:(fp.gy+fp.gh/2)*grid(),radius:Math.hypot(w,h)/2,hp:maxHp,maxHp,powered:false,cooldown:0,color:spec.color});burst((fp.gx+fp.gw/2)*grid(),(fp.gy+fp.gh/2)*grid(),spec.color,10);return true;}
function removeAt(x,y){for(let i=state.buildings.length-1;i>=0;i--){const b=state.buildings[i],r=rect(b);if(x>=r.x&&x<=r.x+r.w&&y>=r.y&&y<=r.y+r.h){const s=BUILDINGS[b.type];state.resources.wood+=Math.floor((s.wood||0)*.35);state.resources.stone+=Math.floor((s.stone||0)*.35);state.buildings.splice(i,1);return;}}}
function structureAtCircle(x,y,radius){for(const b of state.buildings)if(b.hp>0&&circleRectHit(x,y,radius,rect(b)))return b;return null;}
function wallBlocksCircle(x,y,radius){for(const b of state.buildings)if(b.type==='wall'&&b.hp>0&&circleRectHit(x,y,radius,rect(b)))return true;return false;}
function moveWithWalls(e,dx,dy,speed,dt,avoid=true){const d=norm(dx,dy),step=speed*dt;const move=(mx,my)=>{let ok=false,nx=clamp(e.x+mx*step,e.radius,WORLD.width-e.radius);if(!wallBlocksCircle(nx,e.y,e.radius)){e.x=nx;ok=true;}let ny=clamp(e.y+my*step,e.radius,WORLD.height-e.radius);if(!wallBlocksCircle(e.x,ny,e.radius)){e.y=ny;ok=true;}return ok;};if(move(d.x,d.y)||!avoid)return;const side=Math.sin(state.time*2.7+e.x*.013)>0?1:-1;if(!move(-d.y*side,d.x*side))move(d.y*side,-d.x*side);}

function burst(x,y,color,count=6,speed=90){for(let i=0;i<count;i++)state.particles.push({x,y,vx:rand(-speed,speed),vy:rand(-speed,speed),life:rand(.2,.65),maxLife:.65,color,size:rand(2,5),kind:'spark'});}
function dashBurst(){const p=state.player;for(let i=0;i<16;i++){const a=Math.PI*2*i/16;state.particles.push({x:p.x,y:p.y,vx:Math.cos(a)*rand(80,210),vy:Math.sin(a)*rand(80,210),life:.35,maxLife:.35,color:'#74d3ff',size:rand(3,7),kind:'dash'});}}
function dashTrail(){const p=state.player;state.particles.push({x:p.x,y:p.y,vx:0,vy:0,life:.24,maxLife:.24,color:'#74d3ff',size:p.radius*1.6,kind:'ghost'});}
function fire(o,tx,ty,enemy=false,damage=PLAYER.gunDamage,speed=PLAYER.bulletSpeed){const d=norm(tx-o.x,ty-o.y),shot={x:o.x+d.x*(o.radius||10),y:o.y+d.y*(o.radius||10),vx:d.x*speed,vy:d.y*speed,radius:4,life:1.5,damage};(enemy?state.enemyBullets:state.bullets).push(shot);}
function swordAttack(a,damage=PLAYER.swordDamage){const aim=a===state.player?{x:Math.cos(a.angle),y:Math.sin(a.angle)}:a.aim;for(const e of state.enemies){if(e.spawnDelay>0||e.hp<=0)continue;const dx=e.x-a.x,dy=e.y-a.y,d=Math.hypot(dx,dy);if(d>PLAYER.swordRange+e.radius)continue;const n=norm(dx,dy);if(n.x*aim.x+n.y*aim.y<.15)continue;e.hp-=damage;burst(e.x,e.y,'#d9f6ff',4,70);}state.particles.push({x:a.x+aim.x*34,y:a.y+aim.y*34,vx:0,vy:0,life:.14,maxLife:.14,color:'#e8f4ff',size:38,kind:'slash',angle:Math.atan2(aim.y,aim.x)});}

function spawnWave(){state.wave++;state.phase='wave';state.phaseTime=WORLD.baseWaveSeconds+state.wave*2;const count=6+state.wave*3;for(let i=0;i<count;i++){const r=Math.random(),type=i<state.wave/2&&r<.22?'runner':r<Math.min(.12+state.wave*.02,.35)?'brute':r<.5?'spitter':'grunt';spawnEnemy(type,i*.34);}if(state.wave%5===0)spawnEnemy('boss',2);showBanner(state.wave%5===0?`WAVE ${state.wave} · BOSS INBOUND`:`WAVE ${state.wave}`,2000);}
function spawnEnemy(type,delay=0){const edge=Math.floor(Math.random()*4);let x,y;if(edge===0){x=rand(0,WORLD.width);y=-30}else if(edge===1){x=WORLD.width+30;y=rand(0,WORLD.height)}else if(edge===2){x=rand(0,WORLD.width);y=WORLD.height+30}else{x=-30;y=rand(0,WORLD.height)}const s=ENEMIES[type],scale=1+state.wave*.09;state.enemies.push({type,x,y,spawnDelay:delay,hp:s.hp*scale,maxHp:s.hp*scale,speed:s.speed*(1+state.wave*.012),damage:s.damage*(1+state.wave*.06),radius:s.radius,reward:s.reward,color:s.color,attackCd:rand(0,.5),shootCd:rand(.2,1.1)});}
function nearestEnemy(o,range=Infinity){let best=null,bd=range;for(const e of state.enemies){if(e.spawnDelay>0||e.hp<=0)continue;const d=dist(o,e);if(d<bd){bd=d;best=e;}}return best;}
function nearestNode(o,range=Infinity){let best=null,bd=range;for(const n of state.nodes){if(n.hp<=0)continue;const d=dist(o,n);if(d<bd){bd=d;best=n;}}return best;}
function nearestDamaged(o,range=Infinity){let best=null,bd=range;for(const b of state.buildings){if(b.hp>=b.maxHp)continue;const d=dist(o,b);if(d<bd){bd=d;best=b;}}return best;}
function blockingStructure(e){const dx=state.heart.x-e.x,dy=state.heart.y-e.y,len=Math.hypot(dx,dy)||1,ux=dx/len,uy=dy/len;let best=null,bd=110;for(const b of state.buildings){if(b.hp<=0)continue;const vx=b.x-e.x,vy=b.y-e.y,along=vx*ux+vy*uy;if(along<0||along>140)continue;const perp=Math.abs(vx*uy-vy*ux),rr=Math.max(b.gw,b.gh)*grid()/2+e.radius;if(perp<rr&&dist(e,b)<bd){bd=dist(e,b);best=b;}}return best;}
function secondaryPlayer(e){let best=null,bd=95;for(const p of[state.player,...state.ais]){if(p.hp<=0)continue;const d=dist(e,p);if(d<bd){bd=d;best=p;}}return best;}

function updatePlayer(dt){const p=state.player;if(p.hp<=0){p.hp=Math.min(p.maxHp,p.hp+28*dt);if(p.hp>=p.maxHp*.5){p.x=state.heart.x;p.y=state.heart.y+105;toast('전선에 복귀했습니다.');}return;}p.attackCd=Math.max(0,p.attackCd-dt);p.dashCd=Math.max(0,p.dashCd-dt);p.dashT=Math.max(0,p.dashT-dt);p.dashTrailCd=Math.max(0,p.dashTrailCd-dt);const dx=(state.keys.has('d')?1:0)-(state.keys.has('a')?1:0),dy=(state.keys.has('s')?1:0)-(state.keys.has('w')?1:0);if(dx||dy)moveWithWalls(p,dx,dy,p.dashT>0?PLAYER.dashSpeed:PLAYER.speed,dt,false);if(p.dashT>0&&p.dashTrailCd<=0){dashTrail();p.dashTrailCd=.025;}const aim=screenToWorld(state.mouse.x,state.mouse.y);p.angle=Math.atan2(aim.y-p.y,aim.x-p.x);if(state.mouse.down&&!state.selectedBuild&&p.attackCd<=0){if(state.weapon==='gun'&&hasResearch('ranged')){fire(p,aim.x,aim.y,false,PLAYER.gunDamage);p.attackCd=PLAYER.fireRate;}else{swordAttack(p);p.attackCd=PLAYER.swordCooldown;}}}
function updateAI(dt){for(const a of state.ais){if(a.hp<=0){a.hp+=16*dt;if(a.hp>=a.maxHp*.55){a.x=state.heart.x+rand(-70,70);a.y=state.heart.y+rand(-70,70);}continue;}a.attackCd=Math.max(0,a.attackCd-dt);a.repairCd=Math.max(0,a.repairCd-dt);a.gatherCd=Math.max(0,a.gatherCd-dt);const enemy=nearestEnemy(a,380);if(enemy){const dx=enemy.x-a.x,dy=enemy.y-a.y,d=Math.hypot(dx,dy);a.aim=norm(dx,dy);if(hasResearch('ranged')&&d>95){if(d>245)moveWithWalls(a,dx,dy,135,dt,true);if(a.attackCd<=0&&d<300){fire(a,enemy.x,enemy.y,false,18+(hasResearch('squadTraining')?6:0),620);a.attackCd=.55;}}else{if(d>55)moveWithWalls(a,dx,dy,145,dt,true);if(a.attackCd<=0&&d<76){swordAttack(a,28+(hasResearch('squadTraining')?7:0));a.attackCd=.55;}}continue;}const damaged=nearestDamaged(a,230);if(damaged){const d=dist(a,damaged);if(d>44)moveWithWalls(a,damaged.x-a.x,damaged.y-a.y,110,dt,true);else damaged.hp=Math.min(damaged.maxHp,damaged.hp+18*dt);continue;}const node=nearestNode(a,470);if(node&&state.phase!=='wave'){const d=dist(a,node);if(d>45)moveWithWalls(a,node.x-a.x,node.y-a.y,120,dt,true);else if(a.gatherCd<=0){node.hp-=20;a.gatherCd=.48;if(node.hp<=0)harvest(node);}continue;}const guard={x:state.heart.x+Math.cos(state.ais.indexOf(a)*2.1)*110,y:state.heart.y+Math.sin(state.ais.indexOf(a)*2.1)*110};moveWithWalls(a,guard.x-a.x,guard.y-a.y,105,dt,true);}}
function harvest(n){if(n.type==='tree')state.resources.wood+=22;else state.resources.stone+=18;if(Math.random()<.2)state.resources.crystal+=1+Math.floor(Math.random()*2);burst(n.x,n.y,n.type==='tree'?'#5e9a67':'#8b929a',10);n.hp=0;setTimeout(()=>{n.x=rand(80,WORLD.width-80);n.y=rand(80,WORLD.height-80);n.hp=n.maxHp;},12000+Math.random()*7000);}
function updateNodes(dt){for(const n of state.nodes)if(n.hp>0&&state.player.hp>0&&state.mouse.down&&!state.selectedBuild&&state.weapon==='sword'&&dist(state.player,n)<70&&Math.random()<dt*3.5){n.hp-=12;if(n.hp<=0)harvest(n);}}
function updateBuildings(dt){for(const b of state.buildings)b.powered=b.type==='generator'||state.buildings.some(p=>p.type==='generator'&&p.hp>0&&dist(b,p)<280);for(const b of state.buildings){if(b.hp<=0)continue;b.cooldown=Math.max(0,b.cooldown-dt);if(hasResearch('fieldRepair')&&state.phase!=='wave'&&b.hp<b.maxHp)b.hp=Math.min(b.maxHp,b.hp+3.5*dt);if(b.type==='turret'){const e=nearestEnemy(b,b.powered?370:270);if(e&&b.cooldown<=0){fire(b,e.x,e.y,false,b.powered?(hasResearch('overcharge')?36:25):17,700);b.cooldown=b.powered?.38:.58;}}if(b.type==='trap')for(const e of state.enemies)if(e.spawnDelay<=0&&dist(b,e)<b.radius+e.radius+6)e.hp-=(b.powered?(hasResearch('overcharge')?80:62):38)*dt;}state.buildings=state.buildings.filter(b=>{if(b.hp>0)return true;burst(b.x,b.y,'#9a7f6f',18);return false;});}
function damageStructure(b,amount,attacker){b.hp=Math.max(0,b.hp-structureDamage(amount));if(b.type==='wall'&&hasResearch('thorns')&&attacker)attacker.hp=Math.max(0,attacker.hp-8);}
function updateEnemies(dt){for(const e of state.enemies){if(e.spawnDelay>0){e.spawnDelay-=dt;continue;}e.attackCd=Math.max(0,e.attackCd-dt);e.shootCd=Math.max(0,e.shootCd-dt);if(dist(e,state.heart)<state.heart.radius+e.radius+8){if(e.attackCd<=0){state.heart.hp=Math.max(0,state.heart.hp-e.damage);e.attackCd=e.type==='boss'?.65:.9;}continue;}const block=blockingStructure(e);if(block){const d=dist(e,block),reach=e.radius+Math.max(block.gw,block.gh)*grid()/2+10;if(e.type==='spitter'&&d<280&&e.shootCd<=0){fire(e,block.x,block.y,true,e.damage,390);e.shootCd=1.4;}else if(d<reach){if(e.attackCd<=0){damageStructure(block,e.damage,e);e.attackCd=e.type==='boss'?.6:.85;}}else{const n=norm(block.x-e.x,block.y-e.y);e.x+=n.x*e.speed*dt;e.y+=n.y*e.speed*dt;}continue;}const player=secondaryPlayer(e);if(player){const d=dist(e,player);if(e.type==='spitter'&&d<260&&e.shootCd<=0){fire(e,player.x,player.y,true,e.damage,390);e.shootCd=1.4;}else if(d<e.radius+player.radius+7){if(e.attackCd<=0){player.hp=Math.max(0,player.hp-e.damage);e.attackCd=.9;}}else{const n=norm(player.x-e.x,player.y-e.y);e.x+=n.x*e.speed*dt;e.y+=n.y*e.speed*dt;}continue;}const n=norm(state.heart.x-e.x,state.heart.y-e.y),nx=e.x+n.x*e.speed*dt,ny=e.y+n.y*e.speed*dt,hit=structureAtCircle(nx,ny,e.radius);if(hit){if(e.attackCd<=0){damageStructure(hit,e.damage,e);e.attackCd=.85;}}else{e.x=nx;e.y=ny;}}
for(let i=state.enemies.length-1;i>=0;i--){const e=state.enemies[i];if(e.hp<=0){state.resources.crystal+=e.reward;state.score+=e.reward*10;burst(e.x,e.y,e.color,e.type==='boss'?28:9);state.enemies.splice(i,1);}}}
function updateBullets(list,dt,enemy=false){for(let i=list.length-1;i>=0;i--){const b=list[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;let hit=false;if(enemy){const s=structureAtCircle(b.x,b.y,b.radius);if(s){damageStructure(s,b.damage);hit=true;}if(!hit&&dist(b,state.heart)<b.radius+state.heart.radius){state.heart.hp=Math.max(0,state.heart.hp-b.damage);hit=true;}if(!hit)for(const p of[state.player,...state.ais])if(p.hp>0&&dist(b,p)<b.radius+p.radius){p.hp=Math.max(0,p.hp-b.damage);hit=true;break;}}else for(const e of state.enemies)if(e.spawnDelay<=0&&dist(b,e)<b.radius+e.radius){e.hp-=b.damage;hit=true;break;}if(hit||b.life<=0||b.x<0||b.y<0||b.x>WORLD.width||b.y>WORLD.height)list.splice(i,1);}}
function updatePhase(dt){state.phaseTime-=dt;if(state.heart.hp<=0&&!state.gameOver){state.gameOver=true;showBanner(`HEART LOST · SCORE ${state.score}`,100000);}if(state.gameOver)return;if(state.phase==='prep'&&state.phaseTime<=0){state.phase='warning';state.phaseTime=WORLD.warningSeconds;showBanner('⚠ MASS MOVEMENT DETECTED',2200);}else if(state.phase==='warning'&&state.phaseTime<=0)spawnWave();else if(state.phase==='wave'&&(state.phaseTime<=0||state.enemies.length===0)){state.phase='prep';state.phaseTime=Math.max(22,WORLD.prepSeconds-state.wave*.8);state.resources.wood+=15;state.resources.stone+=12;state.resources.crystal+=3;showBanner('WAVE CLEARED · REBUILD',1700);}}

function screenToWorld(sx,sy){const r=canvas.getBoundingClientRect();return{x:(sx-r.left)*(canvas.width/r.width)+state.camera.x,y:(sy-r.top)*(canvas.height/r.height)+state.camera.y};}
function updateCamera(){state.camera.x=clamp(state.player.x-canvas.width/2,0,WORLD.width-canvas.width);state.camera.y=clamp(state.player.y-canvas.height/2,0,WORLD.height-canvas.height);}
function updateUI(){ui.heartHp.textContent=`${Math.ceil(state.heart.hp)} / ${state.heart.maxHp}`;ui.heartBar.style.width=`${clamp(state.heart.hp/state.heart.maxHp*100,0,100)}%`;ui.waveText.textContent=state.wave?`Wave ${state.wave}`:'준비 중';ui.phaseText.textContent=`${state.phase==='prep'?'탐색/건축':state.phase==='warning'?'경고':'침공'} · ${Math.max(0,Math.ceil(state.phaseTime))}s`;ui.woodText.textContent=Math.floor(state.resources.wood);ui.stoneText.textContent=Math.floor(state.resources.stone);ui.crystalText.textContent=Math.floor(state.resources.crystal);ui.scoreText.textContent=`Score ${state.score}`;ui.teamText.textContent=`1 Player + ${state.ais.length} AI`;ui.dashBar.style.width=`${clamp((1-state.player.dashCd/PLAYER.dashCooldown)*100,0,100)}%`;ui.dashText.textContent=state.player.dashCd<=0?'READY':`${state.player.dashCd.toFixed(1)}s`;ui.weaponText.textContent=state.weapon==='gun'&&hasResearch('ranged')?'CARBINE':'SWORD';renderSquad();}
function drawHealth(o){if(o.hp>=o.maxHp)return;const w=(o.radius||24)*2,x=o.x-state.camera.x-w/2,y=o.y-state.camera.y-(o.radius||24)-10;ctx.fillStyle='#351f24';ctx.fillRect(x,y,w,4);ctx.fillStyle='#77df9d';ctx.fillRect(x,y,w*clamp(o.hp/o.maxHp,0,1),4);}
function drawCircle(o,color,stroke){ctx.beginPath();ctx.arc(o.x-state.camera.x,o.y-state.camera.y,o.radius,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke();}}
function render(){ctx.fillStyle='#0e1820';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.save();ctx.translate(-state.camera.x,-state.camera.y);ctx.strokeStyle='rgba(91,125,142,.07)';for(let x=0;x<WORLD.width;x+=grid()){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,WORLD.height);ctx.stroke();}for(let y=0;y<WORLD.height;y+=grid()){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(WORLD.width,y);ctx.stroke();}for(const n of state.nodes){if(n.hp<=0)continue;ctx.fillStyle=n.type==='tree'?'#395d43':'#68717a';ctx.beginPath();ctx.arc(n.x,n.y,n.radius,0,Math.PI*2);ctx.fill();}for(const b of state.buildings){const r=rect(b);ctx.fillStyle=b.color;ctx.fillRect(r.x-2,r.y-2,r.w+4,r.h+4);ctx.strokeStyle=b.powered?'#b7f1ff':'#2f3d4b';ctx.strokeRect(r.x,r.y,r.w,r.h);if(b.type==='turret'){ctx.fillStyle='#20313e';ctx.beginPath();ctx.arc(b.x,b.y,8,0,Math.PI*2);ctx.fill();}if(b.type==='generator'){ctx.fillStyle='rgba(130,210,255,.06)';ctx.beginPath();ctx.arc(b.x,b.y,280,0,Math.PI*2);ctx.fill();}if(b.hp<b.maxHp){ctx.fillStyle='#3b2025';ctx.fillRect(r.x,r.y-7,r.w,4);ctx.fillStyle='#77df9d';ctx.fillRect(r.x,r.y-7,r.w*b.hp/b.maxHp,4);}}ctx.restore();drawCircle(state.heart,'#77d7ff','#d9f6ff');for(const e of state.enemies){if(e.spawnDelay>0)continue;drawCircle(e,e.color,e.type==='boss'?'#ffd0df':null);drawHealth(e);}for(const a of state.ais)if(a.hp>0){drawCircle(a,a.color);drawHealth(a);ctx.fillStyle='#dce9f5';ctx.font='10px system-ui';ctx.textAlign='center';ctx.fillText(a.name,a.x-state.camera.x,a.y-state.camera.y-20);}if(state.player.hp>0){drawCircle(state.player,state.player.color,'#74d3ff');ctx.strokeStyle='#74d3ff';ctx.beginPath();ctx.moveTo(state.player.x-state.camera.x,state.player.y-state.camera.y);ctx.lineTo(state.player.x-state.camera.x+Math.cos(state.player.angle)*26,state.player.y-state.camera.y+Math.sin(state.player.angle)*26);ctx.stroke();drawHealth(state.player);}for(const b of state.bullets)drawCircle(b,'#d9f6ff');for(const b of state.enemyBullets)drawCircle(b,'#ff9d9d');for(const p of state.particles){ctx.globalAlpha=clamp(p.life/p.maxLife,0,1);if(p.kind==='slash'){ctx.strokeStyle=p.color;ctx.lineWidth=6;ctx.beginPath();ctx.arc(p.x-state.camera.x,p.y-state.camera.y,22,p.angle-.8,p.angle+.8);ctx.stroke();}else{ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x-state.camera.x,p.y-state.camera.y,p.size,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;}if(state.selectedBuild){const w=screenToWorld(state.mouse.x,state.mouse.y),fp=footprint(state.selectedBuild,w.x,w.y),s=BUILDINGS[state.selectedBuild];ctx.globalAlpha=.35;ctx.fillStyle=s.color;ctx.fillRect(fp.gx*grid()-state.camera.x,fp.gy*grid()-state.camera.y,fp.gw*grid(),fp.gh*grid());ctx.globalAlpha=1;}if(state.gameOver){ctx.fillStyle='rgba(0,0,0,.45)';ctx.fillRect(0,0,canvas.width,canvas.height);}}
function step(now){const dt=Math.min((now-state.last)/1000,.033);state.last=now;if(!state.gameOver){state.time+=dt;updatePlayer(dt);updateAI(dt);updateNodes(dt);updateBuildings(dt);updateEnemies(dt);updateBullets(state.bullets,dt,false);updateBullets(state.enemyBullets,dt,true);updatePhase(dt);for(let i=state.particles.length-1;i>=0;i--){const p=state.particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.life<=0)state.particles.splice(i,1);}updateCamera();updateUI();}render();requestAnimationFrame(step);}

window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();state.keys.add(k);if(['1','2','3','4'].includes(k)){const key=Object.keys(BUILDINGS)[Number(k)-1];if(key)toggleBuild(key);}if(k==='x'){state.selectedBuild=null;renderBuildButtons();updateBuildInfo();}if(k==='q'&&hasResearch('ranged')){state.weapon=state.weapon==='sword'?'gun':'sword';toast(state.weapon==='gun'?'카빈 장착':'검 장착');}if(e.code==='Space'&&state.player.dashCd<=0&&state.player.hp>0){state.player.dashCd=PLAYER.dashCooldown;state.player.dashT=PLAYER.dashDuration;dashBurst();e.preventDefault();}});window.addEventListener('keyup',e=>state.keys.delete(e.key.toLowerCase()));
canvas.addEventListener('mousemove',e=>{state.mouse.x=e.clientX;state.mouse.y=e.clientY;});canvas.addEventListener('mousedown',e=>{state.mouse.x=e.clientX;state.mouse.y=e.clientY;if(e.button===0){if(state.selectedBuild){const w=screenToWorld(e.clientX,e.clientY);if(placeBuilding(state.selectedBuild,w.x,w.y)){renderBuildButtons();updateBuildInfo();}}else state.mouse.down=true;}else if(e.button===2){const w=screenToWorld(e.clientX,e.clientY);removeAt(w.x,w.y);}});window.addEventListener('mouseup',e=>{if(e.button===0)state.mouse.down=false;});canvas.addEventListener('contextmenu',e=>e.preventDefault());
$('helpButton').addEventListener('click',()=>$('helpDialog').showModal());$('restartButton').addEventListener('click',reset);reset();requestAnimationFrame(step);
