import {WORLD,PLAYER,RESOURCES,ZONES,NODE_TYPES,BUILDINGS,ENEMIES,AI_PLAYERS,RESEARCH} from './config.js';

const canvas=document.getElementById('gameCanvas');
const ctx=canvas.getContext('2d');
const $=id=>document.getElementById(id);
const U=['heartHp','heartBar','waveText','phaseText','resourceGrid','teamText','scoreText','dashText','dashBar','weaponText','zoneText','buildList','buildInfo','squadList','researchList','mapCanvas','chatLog','chatInput','chatHint','banner','toast'].reduce((o,k)=>(o[k]=$(k),o),{});
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const rand=(a,b)=>a+Math.random()*(b-a);
const norm=(x,y)=>{const m=Math.hypot(x,y)||1;return{x:x/m,y:y/m}};
const grid=()=>WORLD.gridSize;
const resourceKeys=Object.keys(RESOURCES);

const S={last:performance.now(),time:0,keys:new Set(),mouse:{x:0,y:0,down:false},camera:{x:0,y:0},phase:'prep',phaseTime:0,wave:0,score:0,res:{},sel:null,tech:new Set(),weapon:'sword',over:false,heart:null,player:null,ais:[],buildings:[],nodes:[],enemies:[],bullets:[],enemyBullets:[],particles:[],chat:[],nextChatId:1,currentViewer:'YOU'};
const has=id=>S.tech.has(id);
const wallMul=()=>1+(has('wallI')?.35:0)+(has('wallII')?.35:0);
const fortMul=()=>has('fortify')?.8:1;

function emptyResources(){return Object.fromEntries(resourceKeys.map(k=>[k,0]));}
function human(){return{x:WORLD.heart.x,y:WORLD.heart.y+120,radius:PLAYER.radius,hp:PLAYER.maxHp,maxHp:PLAYER.maxHp,angle:0,cd:0,gatherCd:0,dashCd:0,dashT:0,trail:0,color:'#e9f4ff',name:'YOU',bubble:null}}
function bot(i){const q=AI_PLAYERS[i];return{x:WORLD.heart.x+rand(-90,90),y:WORLD.heart.y+rand(-90,90),radius:12,hp:115,maxHp:115,cd:rand(0,.4),gatherCd:0,color:q.accent,name:q.name,aim:{x:1,y:0},bubble:null}}
function allPlayers(){return[S.player,...S.ais]}
function zoneAt(x,y){return ZONES.find(z=>x>=z.x&&x<z.x+z.w&&y>=z.y&&y<z.y+z.h)||ZONES[4]}

function seedWorld(){S.nodes=[];for(const z of ZONES){const count=z.id==='heartlands'?25:19;for(let i=0;i<count;i++){const type=z.nodeTypes[Math.floor(Math.random()*z.nodeTypes.length)],spec=NODE_TYPES[type];S.nodes.push({type,zone:z.id,x:rand(z.x+45,z.x+z.w-45),y:rand(z.y+45,z.y+z.h-45),radius:spec.radius,hp:spec.hp,maxHp:spec.hp,color:spec.color})}}}
function reset(){S.time=0;S.last=performance.now();S.phase='prep';S.phaseTime=WORLD.prepSeconds;S.wave=0;S.score=0;S.res=emptyResources();Object.assign(S.res,{wood:90,stone:70,crystal:15});S.sel=null;S.tech=new Set();S.weapon='sword';S.over=false;S.heart={...WORLD.heart,hp:WORLD.heart.maxHp,maxHp:WORLD.heart.maxHp};S.player=human();S.ais=AI_PLAYERS.map((_,i)=>bot(i));S.buildings=[];S.enemies=[];S.bullets=[];S.enemyBullets=[];S.particles=[];S.chat=[];seedWorld();buildUI();researchUI();info();systemChat('지역마다 자원이 다릅니다. F로 가까운 자원을 채집할 수 있습니다.');banner('BUILD PHASE',1400)}
function banner(t,ms=1500){U.banner.textContent=t;U.banner.classList.remove('hidden');clearTimeout(banner.t);banner.t=setTimeout(()=>U.banner.classList.add('hidden'),ms)}
function toast(t){U.toast.textContent=t;U.toast.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>U.toast.classList.add('hidden'),1300)}

function unlocked(k){return !BUILDINGS[k].research||has(BUILDINGS[k].research)}
function costText(b){return resourceKeys.filter(k=>b[k]).map(k=>`${b[k]} ${RESOURCES[k].label}`).join(' · ')}
function canAfford(b){return resourceKeys.every(k=>(S.res[k]||0)>=(b[k]||0))}
function pay(b){for(const k of resourceKeys)S.res[k]-=b[k]||0}
function pick(k){if(!unlocked(k))return toast('연구가 필요합니다.');S.sel=S.sel===k?null:k;buildUI();info()}
function buildUI(){U.buildList.innerHTML='';Object.entries(BUILDINGS).forEach(([k,b],i)=>{const lock=!unlocked(k),q=document.createElement('button');q.className='build-item'+(S.sel===k?' active':'')+(lock?' locked':'');q.disabled=lock;q.innerHTML=`<span>${i+1}. ${b.label}${lock?' 🔒':''}</span><small>${costText(b)}</small>`;q.onclick=()=>pick(k);U.buildList.appendChild(q)})}
function info(){const b=BUILDINGS[S.sel];U.buildInfo.className=b?'build-info':'build-info empty';U.buildInfo.innerHTML=b?`<strong>${b.label}</strong><p>${b.description}</p><span class="footprint">토대 ${b.gridW}×${b.gridH} · ${b.gridW*b.gridH}칸</span>`:'<strong>건물 선택 없음</strong><p>각 건물은 여러 종류의 자원을 요구할 수 있습니다.</p>'}
function researchUI(){U.researchList.innerHTML='';for(const[id,r]of Object.entries(RESEARCH)){const done=has(id),ready=(r.requires||[]).every(has),q=document.createElement('button');q.className='research-item'+(done?' done':'');q.disabled=done||!ready;q.innerHTML=`<span><b>${r.label}</b><small>${r.branch}</small></span><em>${done?'완료':r.cost+'C'}</em><p>${r.description}</p>`;q.onclick=()=>research(id);U.researchList.appendChild(q)}}
function research(id){const r=RESEARCH[id];if(!r||has(id))return;if((r.requires||[]).some(v=>!has(v)))return toast('선행 연구가 필요합니다.');if(S.res.crystal<r.cost)return toast('Crystal이 부족합니다.');S.res.crystal-=r.cost;S.tech.add(id);if(id==='wallI'||id==='wallII')for(const b of S.buildings)if(b.type==='wall'){const ratio=b.hp/b.maxHp;b.maxHp=BUILDINGS.wall.hp*wallMul();b.hp=b.maxHp*ratio}if(id==='corePlating'){S.heart.maxHp+=350;S.heart.hp=Math.min(S.heart.maxHp,S.heart.hp+350)}if(id==='squadTraining')for(const a of S.ais){a.maxHp+=35;a.hp+=35}researchUI();buildUI();info();toast(r.label+' 연구 완료')}

function fp(type,wx,wy){const b=BUILDINGS[type];return{gx:Math.floor(wx/grid()),gy:Math.floor(wy/grid()),gw:b.gridW,gh:b.gridH}}
function cells(b){const out=[];for(let y=0;y<b.gh;y++)for(let x=0;x<b.gw;x++)out.push(`${b.gx+x},${b.gy+y}`);return out}
function rect(b){return{x:b.gx*grid(),y:b.gy*grid(),w:b.gw*grid(),h:b.gh*grid()}}
function hitRect(cx,cy,cr,r){const nx=clamp(cx,r.x,r.x+r.w),ny=clamp(cy,r.y,r.y+r.h);return Math.hypot(cx-nx,cy-ny)<cr}
function occupied(){const s=new Set();for(const b of S.buildings)for(const c of cells(b))s.add(c);return s}
function nearHeart(f){return hitRect(S.heart.x,S.heart.y,S.heart.radius+42,{x:f.gx*grid(),y:f.gy*grid(),w:f.gw*grid(),h:f.gh*grid()})}
function place(type,wx,wy){const b=BUILDINGS[type];if(!b||!unlocked(type))return false;if(!canAfford(b))return toast('필요한 자원이 부족합니다.');const f=fp(type,wx,wy),used=occupied();if(f.gx<0||f.gy<0||(f.gx+f.gw)*grid()>WORLD.width||(f.gy+f.gh)*grid()>WORLD.height||nearHeart(f)||cells(f).some(c=>used.has(c)))return toast('이 슬롯은 사용할 수 없습니다.');const rr={x:f.gx*grid(),y:f.gy*grid(),w:f.gw*grid(),h:f.gh*grid()};if(allPlayers().some(p=>p.hp>0&&hitRect(p.x,p.y,p.radius+2,rr)))return toast('플레이어가 서 있는 칸입니다.');pay(b);const mh=b.hp*(type==='wall'?wallMul():1),w=f.gw*grid()+4,h=f.gh*grid()+4;S.buildings.push({type,...f,x:(f.gx+f.gw/2)*grid(),y:(f.gy+f.gh/2)*grid(),radius:Math.hypot(w,h)/2,hp:mh,maxHp:mh,powered:false,cd:0,color:b.color});burst((f.gx+f.gw/2)*grid(),(f.gy+f.gh/2)*grid(),b.color,10);return true}
function remove(wx,wy){for(let i=S.buildings.length-1;i>=0;i--){const b=S.buildings[i],r=rect(b);if(wx>=r.x&&wx<=r.x+r.w&&wy>=r.y&&wy<=r.y+r.h){const q=BUILDINGS[b.type];for(const k of resourceKeys)S.res[k]+=Math.floor((q[k]||0)*.35);S.buildings.splice(i,1);return}}}
function structureAt(px,py,rad){for(const b of S.buildings)if(b.hp>0&&hitRect(px,py,rad,rect(b)))return b;return null}
function wallAt(px,py,rad){for(const b of S.buildings)if(b.type==='wall'&&b.hp>0&&hitRect(px,py,rad,rect(b)))return true;return false}

function circleBlocked(entity,nx,ny,group='player',ignore=null){if(wallAt(nx,ny,entity.radius))return true;const candidates=[...allPlayers(),...S.enemies];for(const other of candidates){if(!other||other===entity||other===ignore||other.hp<=0||other.spawnDelay>0)continue;const sameEnemy=S.enemies.includes(entity)&&S.enemies.includes(other);const samePlayer=allPlayers().includes(entity)&&allPlayers().includes(other);const cross=!sameEnemy&&!samePlayer;if(!(sameEnemy||samePlayer||cross))continue;if(Math.hypot(nx-other.x,ny-other.y)<entity.radius+other.radius+1)return true}return false}
function moveEntity(entity,dx,dy,speed,dt,avoid=true,ignore=null){const n=norm(dx,dy),step=speed*dt;const go=(mx,my)=>{let moved=false;const nx=clamp(entity.x+mx*step,entity.radius,WORLD.width-entity.radius);if(!circleBlocked(entity,nx,entity.y,'any',ignore)){entity.x=nx;moved=true}const ny=clamp(entity.y+my*step,entity.radius,WORLD.height-entity.radius);if(!circleBlocked(entity,entity.x,ny,'any',ignore)){entity.y=ny;moved=true}return moved};if(go(n.x,n.y)||!avoid)return;const side=Math.sin(S.time*2.7+entity.x*.013)>0?1:-1;if(!go(-n.y*side,n.x*side))go(n.y*side,-n.x*side)}

function burst(px,py,color,count=6,speed=90){for(let i=0;i<count;i++)S.particles.push({x:px,y:py,vx:rand(-speed,speed),vy:rand(-speed,speed),life:rand(.2,.65),max:.65,color,size:rand(2,5),kind:'spark'})}
function dashFx(){const p=S.player;for(let i=0;i<16;i++){const a=Math.PI*2*i/16;S.particles.push({x:p.x,y:p.y,vx:Math.cos(a)*rand(80,210),vy:Math.sin(a)*rand(80,210),life:.35,max:.35,color:'#74d3ff',size:rand(3,7),kind:'dash'})}}
function trail(){const p=S.player;S.particles.push({x:p.x,y:p.y,vx:0,vy:0,life:.24,max:.24,color:'#74d3ff',size:p.radius*1.6,kind:'ghost'})}
function fire(o,tx,ty,enemy=false,damage=PLAYER.gunDamage,speed=PLAYER.bulletSpeed){const n=norm(tx-o.x,ty-o.y),b={x:o.x+n.x*(o.radius||10),y:o.y+n.y*(o.radius||10),vx:n.x*speed,vy:n.y*speed,radius:4,life:1.5,damage};(enemy?S.enemyBullets:S.bullets).push(b)}
function sword(a,damage=PLAYER.swordDamage){const aim=a===S.player?{x:Math.cos(a.angle),y:Math.sin(a.angle)}:a.aim;for(const e of S.enemies){if(e.spawnDelay>0||e.hp<=0)continue;const dx=e.x-a.x,dy=e.y-a.y,d=Math.hypot(dx,dy);if(d>PLAYER.swordRange+e.radius)continue;const n=norm(dx,dy);if(n.x*aim.x+n.y*aim.y<.15)continue;e.hp-=damage;burst(e.x,e.y,'#d9f6ff',4,70)}S.particles.push({x:a.x+aim.x*34,y:a.y+aim.y*34,vx:0,vy:0,life:.14,max:.14,color:'#e8f4ff',size:38,kind:'slash',angle:Math.atan2(aim.y,aim.x)})}

function respawnNode(n){const z=ZONES.find(v=>v.id===n.zone)||zoneAt(n.x,n.y),type=z.nodeTypes[Math.floor(Math.random()*z.nodeTypes.length)],spec=NODE_TYPES[type];n.type=type;n.x=rand(z.x+45,z.x+z.w-45);n.y=rand(z.y+45,z.y+z.h-45);n.radius=spec.radius;n.hp=spec.hp;n.maxHp=spec.hp;n.color=spec.color}
function harvest(n,actor=null){const spec=NODE_TYPES[n.type];S.res[spec.resource]+=spec.amount;if(spec.secondary&&Math.random()<spec.secondaryChance)S.res[spec.secondary]+=Math.max(1,Math.floor(spec.amount*.45));burst(n.x,n.y,spec.color,10);n.hp=0;if(actor===S.player)S.score+=2;setTimeout(()=>respawnNode(n),11000+Math.random()*7000)}
function gatherHit(actor,n,damage){if(!n||n.hp<=0)return;n.hp-=damage;if(n.hp<=0)harvest(n,actor)}
function nearestNode(o,range=1e9){let z=null,d=range;for(const n of S.nodes)if(n.hp>0&&dist(o,n)<d){d=dist(o,n);z=n}return z}
function manualGather(){if(S.player.hp<=0||S.player.gatherCd>0)return;const n=nearestNode(S.player,PLAYER.gatherRange);if(!n)return toast('가까운 채집 자원이 없습니다.');gatherHit(S.player,n,34);S.player.gatherCd=.35;burst(n.x,n.y,'#eff7dc',4,55)}

function spawn(type,delay=0){const edge=Math.floor(Math.random()*4);let px,py;if(edge===0){px=rand(0,WORLD.width);py=5}else if(edge===1){px=WORLD.width-5;py=rand(0,WORLD.height)}else if(edge===2){px=rand(0,WORLD.width);py=WORLD.height-5}else{px=5;py=rand(0,WORLD.height)}const q=ENEMIES[type],sc=1+S.wave*.09;S.enemies.push({type,x:px,y:py,spawnDelay:delay,hp:q.hp*sc,maxHp:q.hp*sc,speed:q.speed*(1+S.wave*.012),damage:q.damage*(1+S.wave*.06),radius:q.radius,reward:q.reward,color:q.color,cd:rand(0,.5),shoot:rand(.2,1.1)})}
function wave(){S.wave++;S.phase='wave';S.phaseTime=WORLD.baseWaveSeconds+S.wave*2;for(let i=0;i<6+S.wave*3;i++){const r=Math.random(),t=i<S.wave/2&&r<.22?'runner':r<Math.min(.12+S.wave*.02,.35)?'brute':r<.5?'spitter':'grunt';spawn(t,i*.34)}if(S.wave%5===0)spawn('boss',2);banner(S.wave%5===0?`WAVE ${S.wave} · BOSS INBOUND`:`WAVE ${S.wave}`,2000)}
function nearestEnemy(o,range=1e9){let z=null,d=range;for(const e of S.enemies)if(e.spawnDelay<=0&&e.hp>0&&dist(o,e)<d){d=dist(o,e);z=e}return z}
function nearestDamaged(o,range=1e9){let z=null,d=range;for(const b of S.buildings)if(b.hp<b.maxHp&&dist(o,b)<d){d=dist(o,b);z=b}return z}
function blocking(e){const dx=S.heart.x-e.x,dy=S.heart.y-e.y,l=Math.hypot(dx,dy)||1,ux=dx/l,uy=dy/l;let z=null,best=120;for(const b of S.buildings){if(b.hp<=0)continue;const vx=b.x-e.x,vy=b.y-e.y,along=vx*ux+vy*uy,perp=Math.abs(vx*uy-vy*ux),rr=Math.max(b.gw,b.gh)*grid()/2+e.radius,d=dist(e,b);if(along>=0&&along<=150&&perp<rr&&d<best){best=d;z=b}}return z}
function secondary(e){let z=null,best=100;for(const p of allPlayers())if(p.hp>0&&dist(e,p)<best){best=dist(e,p);z=p}return z}

function playerTick(dt){const p=S.player;if(p.hp<=0){p.hp=Math.min(p.maxHp,p.hp+28*dt);if(p.hp>=p.maxHp*.5){p.x=S.heart.x;p.y=S.heart.y+105;toast('전선에 복귀했습니다.')}return}p.cd=Math.max(0,p.cd-dt);p.gatherCd=Math.max(0,p.gatherCd-dt);p.dashCd=Math.max(0,p.dashCd-dt);p.dashT=Math.max(0,p.dashT-dt);p.trail=Math.max(0,p.trail-dt);const dx=(S.keys.has('d')?1:0)-(S.keys.has('a')?1:0),dy=(S.keys.has('s')?1:0)-(S.keys.has('w')?1:0);if(dx||dy)moveEntity(p,dx,dy,p.dashT>0?PLAYER.dashSpeed:PLAYER.speed,dt,false);if(p.dashT>0&&p.trail<=0){trail();p.trail=.025}const a=world(S.mouse.x,S.mouse.y);p.angle=Math.atan2(a.y-p.y,a.x-p.x);if(S.mouse.down&&!S.sel&&p.cd<=0){const node=nearestNode(p,PLAYER.swordRange+12);if(S.weapon==='sword'&&node&&dist(p,node)<PLAYER.swordRange+node.radius){gatherHit(p,node,12);p.cd=PLAYER.swordCooldown}else if(S.weapon==='gun'&&has('ranged')){fire(p,a.x,a.y,false,PLAYER.gunDamage);p.cd=PLAYER.fireRate}else{sword(p);p.cd=PLAYER.swordCooldown}}}
function aiTick(dt){for(const a of S.ais){if(a.hp<=0){a.hp+=16*dt;if(a.hp>=a.maxHp*.55){a.x=S.heart.x+rand(-70,70);a.y=S.heart.y+rand(-70,70)}continue}a.cd=Math.max(0,a.cd-dt);a.gatherCd=Math.max(0,a.gatherCd-dt);const e=nearestEnemy(a,380);if(e){const dx=e.x-a.x,dy=e.y-a.y,d=Math.hypot(dx,dy);a.aim=norm(dx,dy);if(has('ranged')&&d>95){if(d>245)moveEntity(a,dx,dy,135,dt,true,e);if(a.cd<=0&&d<300){fire(a,e.x,e.y,false,18+(has('squadTraining')?6:0),620);a.cd=.55}}else{if(d>55)moveEntity(a,dx,dy,145,dt,true,e);if(a.cd<=0&&d<76){sword(a,28+(has('squadTraining')?7:0));a.cd=.55}}continue}const damaged=nearestDamaged(a,230);if(damaged){if(dist(a,damaged)>44)moveEntity(a,damaged.x-a.x,damaged.y-a.y,110,dt,true);else damaged.hp=Math.min(damaged.maxHp,damaged.hp+18*dt);continue}const n=nearestNode(a,470);if(n&&S.phase!=='wave'){if(dist(a,n)>45)moveEntity(a,n.x-a.x,n.y-a.y,120,dt,true);else if(a.gatherCd<=0){gatherHit(a,n,20);a.gatherCd=.48}continue}const i=S.ais.indexOf(a),guard={x:S.heart.x+Math.cos(i*2.1)*110,y:S.heart.y+Math.sin(i*2.1)*110};moveEntity(a,guard.x-a.x,guard.y-a.y,105,dt,true)}}
function buildingTick(dt){for(const b of S.buildings)b.powered=b.type==='generator'||S.buildings.some(q=>q.type==='generator'&&q.hp>0&&dist(b,q)<280);for(const b of S.buildings){if(b.hp<=0)continue;b.cd=Math.max(0,b.cd-dt);if(has('fieldRepair')&&S.phase!=='wave'&&b.hp<b.maxHp)b.hp=Math.min(b.maxHp,b.hp+3.5*dt);if(b.type==='turret'){const e=nearestEnemy(b,b.powered?370:270);if(e&&b.cd<=0){fire(b,e.x,e.y,false,b.powered?(has('overcharge')?36:25):17,700);b.cd=b.powered?.38:.58}}if(b.type==='trap')for(const e of S.enemies)if(e.spawnDelay<=0&&dist(b,e)<b.radius+e.radius+6)e.hp-=(b.powered?(has('overcharge')?80:62):38)*dt}S.buildings=S.buildings.filter(b=>{if(b.hp>0)return true;burst(b.x,b.y,'#9a7f6f',18);return false})}
function hurtStructure(b,amount,attacker){b.hp=Math.max(0,b.hp-amount*fortMul());if(b.type==='wall'&&has('thorns')&&attacker)attacker.hp=Math.max(0,attacker.hp-8)}
function enemyTick(dt){for(const e of S.enemies){if(e.spawnDelay>0){e.spawnDelay-=dt;continue}e.cd=Math.max(0,e.cd-dt);e.shoot=Math.max(0,e.shoot-dt);if(dist(e,S.heart)<S.heart.radius+e.radius+8){if(e.cd<=0){S.heart.hp=Math.max(0,S.heart.hp-e.damage);e.cd=e.type==='boss'?.65:.9}continue}const b=blocking(e);if(b){const d=dist(e,b),reach=e.radius+Math.max(b.gw,b.gh)*grid()/2+10;if(e.type==='spitter'&&d<280&&e.shoot<=0){fire(e,b.x,b.y,true,e.damage,390);e.shoot=1.4}else if(d<reach){if(e.cd<=0){hurtStructure(b,e.damage,e);e.cd=e.type==='boss'?.6:.85}}else moveEntity(e,b.x-e.x,b.y-e.y,e.speed,dt,true);continue}const p=secondary(e);if(p){const d=dist(e,p);if(e.type==='spitter'&&d<260&&e.shoot<=0){fire(e,p.x,p.y,true,e.damage,390);e.shoot=1.4}else if(d<e.radius+p.radius+7){if(e.cd<=0){p.hp=Math.max(0,p.hp-e.damage);e.cd=.9}}else moveEntity(e,p.x-e.x,p.y-e.y,e.speed,dt,true,p);continue}const before={x:e.x,y:e.y};moveEntity(e,S.heart.x-e.x,S.heart.y-e.y,e.speed,dt,true);if(before.x===e.x&&before.y===e.y){const ob=structureAt(e.x,e.y,e.radius+5);if(ob&&e.cd<=0){hurtStructure(ob,e.damage,e);e.cd=.85}}}for(let i=S.enemies.length-1;i>=0;i--){const e=S.enemies[i];if(e.hp<=0){S.res.crystal+=e.reward;S.score+=e.reward*10;burst(e.x,e.y,e.color,e.type==='boss'?28:9);S.enemies.splice(i,1)}}}
function bulletTick(list,dt,enemy=false){for(let i=list.length-1;i>=0;i--){const b=list[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;let h=false;if(enemy){const st=structureAt(b.x,b.y,b.radius);if(st){hurtStructure(st,b.damage);h=true}if(!h&&dist(b,S.heart)<b.radius+S.heart.radius){S.heart.hp=Math.max(0,S.heart.hp-b.damage);h=true}if(!h)for(const p of allPlayers())if(p.hp>0&&dist(b,p)<b.radius+p.radius){p.hp=Math.max(0,p.hp-b.damage);h=true;break}}else for(const e of S.enemies)if(e.spawnDelay<=0&&dist(b,e)<b.radius+e.radius){e.hp-=b.damage;h=true;break}if(h||b.life<=0||b.x<0||b.y<0||b.x>WORLD.width||b.y>WORLD.height)list.splice(i,1)}}
function phaseTick(dt){S.phaseTime-=dt;if(S.heart.hp<=0&&!S.over){S.over=true;banner(`HEART LOST · SCORE ${S.score}`,999999);return}if(S.phase==='prep'&&S.phaseTime<=0){S.phase='warning';S.phaseTime=WORLD.warningSeconds;banner('⚠ MASS MOVEMENT DETECTED',2200)}else if(S.phase==='warning'&&S.phaseTime<=0)wave();else if(S.phase==='wave'&&(S.phaseTime<=0||S.enemies.length===0)){S.phase='prep';S.phaseTime=Math.max(22,WORLD.prepSeconds-S.wave*.8);S.res.wood+=10;S.res.stone+=8;S.res.crystal+=3;banner('WAVE CLEARED · REBUILD',1500)}}

function systemChat(text){pushChat({sender:'SYSTEM',text,type:'system',audience:['YOU']})}
function pushChat(msg){const m={id:S.nextChatId++,time:S.time,...msg};S.chat.push(m);if(S.chat.length>80)S.chat.shift();renderChat();if(msg.sender&&msg.sender!=='SYSTEM'){const p=allPlayers().find(q=>q.name.toLowerCase()===msg.sender.toLowerCase());if(p)p.bubble={text:msg.text,type:msg.type||'global',until:S.time+4.5,audience:msg.audience||['*']}}}
function visibleToMe(m){return !m.audience||m.audience.includes('*')||m.audience.includes(S.currentViewer)}
function renderChat(){U.chatLog.innerHTML='';for(const m of S.chat.filter(visibleToMe).slice(-12)){const row=document.createElement('div');row.className='chat-row '+(m.type||'global');row.innerHTML=m.type==='whisper'?`<b>[귓속말] ${escapeHtml(m.sender)} → ${escapeHtml(m.target)}</b><span>${escapeHtml(m.text)}</span>`:m.type==='system'?`<span>${escapeHtml(m.text)}</span>`:`<b>${escapeHtml(m.sender)}</b><span>${escapeHtml(m.text)}</span>`;U.chatLog.appendChild(row)}U.chatLog.scrollTop=U.chatLog.scrollHeight}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function sendChat(raw){const text=raw.trim();if(!text)return;if(text.startsWith('/w ')){const match=text.match(/^\/w\s+(\S+)\s+(.+)$/i);if(!match)return toast('사용법: /w <플레이어이름> <메시지>');const target=allPlayers().find(p=>p.name.toLowerCase()===match[1].toLowerCase());if(!target)return toast('해당 플레이어를 찾을 수 없습니다.');if(target.name==='YOU')return toast('자기 자신에게는 귓속말할 수 없습니다.');pushChat({sender:'YOU',target:target.name,text:match[2].slice(0,180),type:'whisper',audience:['YOU',target.name]});return}pushChat({sender:'YOU',text:text.slice(0,180),type:'global',audience:['*']})}
function bubbleVisible(b){return b&&b.until>S.time&&(b.audience.includes('*')||b.audience.includes(S.currentViewer))}

function world(sx,sy){const r=canvas.getBoundingClientRect();return{x:(sx-r.left)*(canvas.width/r.width)+S.camera.x,y:(sy-r.top)*(canvas.height/r.height)+S.camera.y}}
function updateUI(){U.heartHp.textContent=`${Math.ceil(S.heart.hp)} / ${S.heart.maxHp}`;U.heartBar.style.width=`${clamp(S.heart.hp/S.heart.maxHp*100,0,100)}%`;U.waveText.textContent=S.wave?`Wave ${S.wave}`:'준비 중';U.phaseText.textContent=`${S.phase==='prep'?'탐색/건축':S.phase==='warning'?'경고':'침공'} · ${Math.max(0,Math.ceil(S.phaseTime))}s`;U.teamText.textContent='1 Player + 3 AI';U.scoreText.textContent=`Score ${S.score}`;U.dashText.textContent=S.player.dashCd<=0?'READY':`${S.player.dashCd.toFixed(1)}s`;U.dashBar.style.width=`${(1-clamp(S.player.dashCd/PLAYER.dashCooldown,0,1))*100}%`;U.weaponText.textContent=S.weapon==='gun'?'CARBINE':'SWORD';const z=zoneAt(S.player.x,S.player.y);U.zoneText.textContent=z.name;renderResources();squadUI();drawMiniMap()}
function renderResources(){U.resourceGrid.innerHTML='';for(const k of resourceKeys){const r=RESOURCES[k],el=document.createElement('div');el.className='resource-chip';el.innerHTML=`<span style="color:${r.color}">${r.icon}</span><b>${r.label}</b><strong>${Math.floor(S.res[k]||0)}</strong>`;U.resourceGrid.appendChild(el)}}
function squadUI(){U.squadList.innerHTML='';for(const p of allPlayers()){const q=document.createElement('div');q.className='squad-member'+(p===S.player?' player-self':'');q.innerHTML=`<b style="color:${p.color}">${p.name}</b><small>${Math.ceil(Math.max(0,p.hp))}/${p.maxHp}</small>`;U.squadList.appendChild(q)}}

function drawMiniMap(){if(!U.mapCanvas)return;const m=U.mapCanvas.getContext('2d'),w=U.mapCanvas.width,h=U.mapCanvas.height,sx=w/WORLD.width,sy=h/WORLD.height;m.clearRect(0,0,w,h);for(const z of ZONES){m.fillStyle=z.color;m.fillRect(z.x*sx,z.y*sy,z.w*sx,z.h*sy);m.strokeStyle=z.accent;m.strokeRect(z.x*sx,z.y*sy,z.w*sx,z.h*sy)}m.fillStyle='#77d7ff';m.beginPath();m.arc(S.heart.x*sx,S.heart.y*sy,4,0,Math.PI*2);m.fill();for(const p of allPlayers()){m.fillStyle=p.color;m.beginPath();m.arc(p.x*sx,p.y*sy,p===S.player?3.5:2.5,0,Math.PI*2);m.fill()}}
function drawGrid(){ctx.fillStyle='#0e1820';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.save();ctx.translate(-S.camera.x,-S.camera.y);for(const z of ZONES){ctx.fillStyle=z.color;ctx.globalAlpha=.52;ctx.fillRect(z.x,z.y,z.w,z.h);ctx.globalAlpha=1;ctx.strokeStyle=z.accent+'55';ctx.lineWidth=3;ctx.strokeRect(z.x,z.y,z.w,z.h);ctx.fillStyle='rgba(255,255,255,.18)';ctx.font='bold 22px system-ui';ctx.fillText(z.name,z.x+24,z.y+38)}ctx.strokeStyle='rgba(91,125,142,.09)';ctx.lineWidth=1;for(let gx=0;gx<WORLD.width;gx+=grid()){ctx.beginPath();ctx.moveTo(gx,0);ctx.lineTo(gx,WORLD.height);ctx.stroke()}for(let gy=0;gy<WORLD.height;gy+=grid()){ctx.beginPath();ctx.moveTo(0,gy);ctx.lineTo(WORLD.width,gy);ctx.stroke()}ctx.restore()}
function drawCircle(o,color,outline=null){ctx.beginPath();ctx.arc(o.x-S.camera.x,o.y-S.camera.y,o.radius,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();if(outline){ctx.strokeStyle=outline;ctx.lineWidth=2;ctx.stroke()}}
function drawBubble(p){if(!bubbleVisible(p.bubble))return;const text=p.bubble.text.slice(0,44),px=p.x-S.camera.x,py=p.y-S.camera.y-p.radius-34;ctx.font='12px system-ui';const width=Math.min(260,ctx.measureText(text).width+18);ctx.fillStyle=p.bubble.type==='whisper'?'rgba(86,52,112,.94)':'rgba(10,18,25,.94)';ctx.strokeStyle=p.bubble.type==='whisper'?'#c38cff':'#61798d';ctx.lineWidth=1;ctx.beginPath();ctx.roundRect(px-width/2,py-18,width,28,7);ctx.fill();ctx.stroke();ctx.fillStyle='#f2f6fb';ctx.textAlign='center';ctx.fillText(text,px,py)}
function drawHealth(o){if(o.hp>=o.maxHp)return;const w=(o.radius||20)*2,px=o.x-S.camera.x-w/2,py=o.y-S.camera.y-(o.radius||20)-10;ctx.fillStyle='#371d22';ctx.fillRect(px,py,w,4);ctx.fillStyle='#77df9d';ctx.fillRect(px,py,w*clamp(o.hp/o.maxHp,0,1),4)}
function render(){drawGrid();ctx.save();ctx.translate(-S.camera.x,-S.camera.y);for(const n of S.nodes){if(n.hp<=0)continue;ctx.fillStyle=n.color;ctx.beginPath();ctx.arc(n.x,n.y,n.radius,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(255,255,255,.35)';ctx.font='10px system-ui';ctx.textAlign='center';ctx.fillText(RESOURCES[NODE_TYPES[n.type].resource].icon,n.x,n.y+3)}for(const b of S.buildings){const r=rect(b);ctx.fillStyle=b.color;ctx.fillRect(r.x,r.y,r.w,r.h);ctx.strokeStyle=b.powered?'#b7f1ff':'#2f3d4b';ctx.strokeRect(r.x,r.y,r.w,r.h)}ctx.restore();drawCircle(S.heart,'#77d7ff','#d9f6ff');for(const e of S.enemies){if(e.spawnDelay>0)continue;drawCircle(e,e.color);drawHealth(e)}for(const p of allPlayers()){if(p.hp<=0)continue;drawCircle(p,p.color,p===S.player?'#74d3ff':null);ctx.fillStyle='#dce9f5';ctx.font='10px system-ui';ctx.textAlign='center';ctx.fillText(p.name,p.x-S.camera.x,p.y-S.camera.y-20);drawHealth(p);drawBubble(p)}for(const b of S.bullets)drawCircle(b,'#d9f6ff');for(const b of S.enemyBullets)drawCircle(b,'#ff9d9d');for(const p of S.particles){ctx.globalAlpha=clamp(p.life/(p.max||.65),0,1);ctx.save();ctx.translate(p.x-S.camera.x,p.y-S.camera.y);if(p.kind==='slash'){ctx.rotate(p.angle);ctx.strokeStyle=p.color;ctx.lineWidth=6;ctx.beginPath();ctx.arc(0,0,p.size*.65,-.8,.8);ctx.stroke()}else{ctx.fillStyle=p.color;ctx.fillRect(-p.size/2,-p.size/2,p.size,p.size)}ctx.restore();ctx.globalAlpha=1}if(S.sel){const w=world(S.mouse.x,S.mouse.y),f=fp(S.sel,w.x,w.y);ctx.fillStyle=BUILDINGS[S.sel].color;ctx.globalAlpha=.42;ctx.fillRect(f.gx*grid()-S.camera.x,f.gy*grid()-S.camera.y,f.gw*grid(),f.gh*grid());ctx.globalAlpha=1}if(S.over){ctx.fillStyle='rgba(0,0,0,.45)';ctx.fillRect(0,0,canvas.width,canvas.height)}}

function step(now){const dt=Math.min((now-S.last)/1000,.033);S.last=now;if(!S.over){S.time+=dt;playerTick(dt);aiTick(dt);buildingTick(dt);enemyTick(dt);bulletTick(S.bullets,dt,false);bulletTick(S.enemyBullets,dt,true);phaseTick(dt);for(let i=S.particles.length-1;i>=0;i--){const p=S.particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.life<=0)S.particles.splice(i,1)}S.camera.x=clamp(S.player.x-canvas.width/2,0,WORLD.width-canvas.width);S.camera.y=clamp(S.player.y-canvas.height/2,0,WORLD.height-canvas.height);updateUI()}render();requestAnimationFrame(step)}

window.addEventListener('keydown',e=>{if(document.activeElement===U.chatInput){if(e.key==='Enter'){e.preventDefault();sendChat(U.chatInput.value);U.chatInput.value='';U.chatInput.blur()}if(e.key==='Escape'){U.chatInput.value='';U.chatInput.blur()}return}const k=e.key.toLowerCase();if(e.key==='Enter'){e.preventDefault();U.chatInput.focus();return}S.keys.add(k);if(['1','2','3','4'].includes(k)){const key=Object.keys(BUILDINGS)[Number(k)-1];if(key)pick(key)}if(k==='q'&&has('ranged')){S.weapon=S.weapon==='sword'?'gun':'sword';toast(S.weapon==='gun'?'카빈 장착':'검 장착')}if(k==='f')manualGather();if(e.code==='Space'&&S.player.dashCd<=0&&S.player.hp>0){S.player.dashCd=PLAYER.dashCooldown;S.player.dashT=PLAYER.dashDuration;dashFx();e.preventDefault()}});
window.addEventListener('keyup',e=>S.keys.delete(e.key.toLowerCase()));
canvas.addEventListener('mousemove',e=>{S.mouse.x=e.clientX;S.mouse.y=e.clientY});
canvas.addEventListener('mousedown',e=>{S.mouse.x=e.clientX;S.mouse.y=e.clientY;if(e.button===0){if(S.sel){const w=world(e.clientX,e.clientY);place(S.sel,w.x,w.y)}else S.mouse.down=true}else if(e.button===2){const w=world(e.clientX,e.clientY);remove(w.x,w.y)}});
window.addEventListener('mouseup',e=>{if(e.button===0)S.mouse.down=false});
canvas.addEventListener('contextmenu',e=>e.preventDefault());
$('helpButton').onclick=()=>$('helpDialog').showModal();
$('restartButton').onclick=reset;
U.chatInput.addEventListener('focus',()=>U.chatHint.textContent='Enter 전송 · /w <이름> <메시지> 귓속말');
U.chatInput.addEventListener('blur',()=>U.chatHint.textContent='Enter로 채팅');

reset();requestAnimationFrame(step);