import {WORLD,PLAYER,BUILDINGS,ENEMIES,AI_PLAYERS,RESEARCH} from './config.js';

const c=document.getElementById('gameCanvas'),x=c.getContext('2d'),$=id=>document.getElementById(id);
const U=['heartHp','heartBar','waveText','phaseText','woodText','stoneText','crystalText','teamText','scoreText','dashText','dashBar','weaponText','buildList','buildInfo','squadList','researchList','banner','toast'].reduce((o,k)=>(o[k]=$(k),o),{});
const C=(v,a,b)=>Math.max(a,Math.min(b,v)),D=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),R=(a,b)=>a+Math.random()*(b-a),N=(a,b)=>{const m=Math.hypot(a,b)||1;return{x:a/m,y:b/m}},G=()=>WORLD.gridSize;
const S={last:performance.now(),time:0,keys:new Set(),mouse:{x:0,y:0,down:false},camera:{x:0,y:0},phase:'prep',phaseTime:0,wave:0,score:0,res:{wood:90,stone:70,crystal:15},sel:null,tech:new Set(),weapon:'sword',over:false,heart:null,player:null,ais:[],buildings:[],nodes:[],enemies:[],bullets:[],enemyBullets:[],particles:[]};
const has=id=>S.tech.has(id),wallMul=()=>1+(has('wallI')?0.35:0)+(has('wallII')?0.35:0),fortMul=()=>has('fortify')?0.8:1;

function human(){return{x:WORLD.heart.x,y:WORLD.heart.y+120,radius:PLAYER.radius,hp:PLAYER.maxHp,maxHp:PLAYER.maxHp,angle:0,cd:0,dashCd:0,dashT:0,trail:0,color:'#e9f4ff',name:'YOU'}}
function bot(i){const q=AI_PLAYERS[i];return{x:WORLD.heart.x+R(-90,90),y:WORLD.heart.y+R(-90,90),radius:12,hp:115,maxHp:115,cd:R(0,.4),gather:0,color:q.accent,name:q.name,aim:{x:1,y:0}}}
function seed(){S.nodes=[];for(let i=0;i<62;i++){const a=Math.random()*Math.PI*2,r=R(260,980),t=Math.random()<.58;S.nodes.push({type:t?'tree':'rock',x:C(WORLD.heart.x+Math.cos(a)*r,70,WORLD.width-70),y:C(WORLD.heart.y+Math.sin(a)*r,70,WORLD.height-70),radius:t?24:22,hp:85,maxHp:85})}}
function reset(){S.time=0;S.last=performance.now();S.phase='prep';S.phaseTime=WORLD.prepSeconds;S.wave=0;S.score=0;S.res={wood:90,stone:70,crystal:15};S.sel=null;S.tech=new Set();S.weapon='sword';S.over=false;S.heart={...WORLD.heart,hp:WORLD.heart.maxHp,maxHp:WORLD.heart.maxHp};S.player=human();S.ais=AI_PLAYERS.map((_,i)=>bot(i));S.buildings=[];S.enemies=[];S.bullets=[];S.enemyBullets=[];S.particles=[];seed();buildUI();researchUI();info();banner('BUILD PHASE',1400)}
function banner(t,ms=1500){U.banner.textContent=t;U.banner.classList.remove('hidden');clearTimeout(banner.t);banner.t=setTimeout(()=>U.banner.classList.add('hidden'),ms)}
function toast(t){U.toast.textContent=t;U.toast.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>U.toast.classList.add('hidden'),1300)}

function unlocked(k){return !BUILDINGS[k].research||has(BUILDINGS[k].research)}
function pick(k){if(!unlocked(k))return toast('연구가 필요합니다.');S.sel=S.sel===k?null:k;buildUI();info()}
function buildUI(){U.buildList.innerHTML='';Object.entries(BUILDINGS).forEach(([k,b],i)=>{const lock=!unlocked(k),q=document.createElement('button');q.className='build-item'+(S.sel===k?' active':'')+(lock?' locked':'');q.disabled=lock;q.innerHTML=`<span>${i+1}. ${b.label}${lock?' 🔒':''}</span><small>${b.wood||0}W ${b.stone||0}S ${b.crystal||0}C</small>`;q.onclick=()=>pick(k);U.buildList.appendChild(q)})}
function info(){const b=BUILDINGS[S.sel];U.buildInfo.className=b?'build-info':'build-info empty';U.buildInfo.innerHTML=b?`<strong>${b.label}</strong><p>${b.description}</p><span class="footprint">토대 ${b.gridW}×${b.gridH} · ${b.gridW*b.gridH}칸</span>`:'<strong>건물 선택 없음</strong><p>벽과 함정은 처음부터, 터렛과 발전기는 연구 후 사용할 수 있습니다.</p>'}
function squadUI(){U.squadList.innerHTML='';for(const p of[S.player,...S.ais]){const q=document.createElement('div');q.className='squad-member'+(p===S.player?' player-self':'');q.innerHTML=`<b style="color:${p.color}">${p.name}</b><small>${Math.ceil(Math.max(0,p.hp))}/${p.maxHp}</small>`;U.squadList.appendChild(q)}}
function researchUI(){U.researchList.innerHTML='';for(const[id,r]of Object.entries(RESEARCH)){const done=has(id),ready=(r.requires||[]).every(has),q=document.createElement('button');q.className='research-item'+(done?' done':'');q.disabled=done||!ready;q.innerHTML=`<span><b>${r.label}</b><small>${r.branch}</small></span><em>${done?'완료':r.cost+'C'}</em><p>${r.description}</p>`;q.onclick=()=>research(id);U.researchList.appendChild(q)}}
function research(id){const r=RESEARCH[id];if(!r||has(id))return;if((r.requires||[]).some(v=>!has(v)))return toast('선행 연구가 필요합니다.');if(S.res.crystal<r.cost)return toast('Crystal이 부족합니다.');S.res.crystal-=r.cost;S.tech.add(id);if(id==='wallI'||id==='wallII')for(const b of S.buildings)if(b.type==='wall'){const ratio=b.hp/b.maxHp;b.maxHp=BUILDINGS.wall.hp*wallMul();b.hp=b.maxHp*ratio}if(id==='corePlating'){S.heart.maxHp+=350;S.heart.hp=Math.min(S.heart.maxHp,S.heart.hp+350)}if(id==='squadTraining')for(const a of S.ais){a.maxHp+=35;a.hp+=35}researchUI();buildUI();info();toast(r.label+' 연구 완료')}

function fp(type,wx,wy){const b=BUILDINGS[type];return{gx:Math.floor(wx/G()),gy:Math.floor(wy/G()),gw:b.gridW,gh:b.gridH}}
function cells(b){const z=[];for(let yy=0;yy<b.gh;yy++)for(let xx=0;xx<b.gw;xx++)z.push(`${b.gx+xx},${b.gy+yy}`);return z}
function rect(b){return{x:b.gx*G(),y:b.gy*G(),w:b.gw*G(),h:b.gh*G()}}
function hitRect(cx,cy,cr,r){const nx=C(cx,r.x,r.x+r.w),ny=C(cy,r.y,r.y+r.h);return Math.hypot(cx-nx,cy-ny)<cr}
function occupied(){const z=new Set();for(const b of S.buildings)for(const k of cells(b))z.add(k);return z}
function nearHeart(f){return hitRect(S.heart.x,S.heart.y,S.heart.radius+42,{x:f.gx*G(),y:f.gy*G(),w:f.gw*G(),h:f.gh*G()})}
function place(type,wx,wy){const b=BUILDINGS[type];if(!b||!unlocked(type))return false;if(S.res.wood<(b.wood||0)||S.res.stone<(b.stone||0)||S.res.crystal<(b.crystal||0))return toast('자원이 부족합니다.');const f=fp(type,wx,wy),used=occupied();if(f.gx<0||f.gy<0||(f.gx+f.gw)*G()>WORLD.width||(f.gy+f.gh)*G()>WORLD.height||nearHeart(f)||cells(f).some(k=>used.has(k)))return toast('이 슬롯은 사용할 수 없습니다.');const rr={x:f.gx*G(),y:f.gy*G(),w:f.gw*G(),h:f.gh*G()};if(type==='wall'&&[S.player,...S.ais].some(p=>p.hp>0&&hitRect(p.x,p.y,p.radius+2,rr)))return toast('플레이어가 서 있는 칸입니다.');S.res.wood-=b.wood||0;S.res.stone-=b.stone||0;S.res.crystal-=b.crystal||0;const mh=b.hp*(type==='wall'?wallMul():1),w=f.gw*G()+4,h=f.gh*G()+4;S.buildings.push({type,...f,x:(f.gx+f.gw/2)*G(),y:(f.gy+f.gh/2)*G(),radius:Math.hypot(w,h)/2,hp:mh,maxHp:mh,powered:false,cd:0,color:b.color});burst((f.gx+f.gw/2)*G(),(f.gy+f.gh/2)*G(),b.color,10);return true}
function remove(wx,wy){for(let i=S.buildings.length-1;i>=0;i--){const b=S.buildings[i],r=rect(b);if(wx>=r.x&&wx<=r.x+r.w&&wy>=r.y&&wy<=r.y+r.h){const q=BUILDINGS[b.type];S.res.wood+=Math.floor((q.wood||0)*.35);S.res.stone+=Math.floor((q.stone||0)*.35);S.buildings.splice(i,1);return}}}
function structureAt(px,py,rad){for(const b of S.buildings)if(b.hp>0&&hitRect(px,py,rad,rect(b)))return b;return null}
function wallAt(px,py,rad){for(const b of S.buildings)if(b.type==='wall'&&b.hp>0&&hitRect(px,py,rad,rect(b)))return true;return false}
function move(p,dx,dy,speed,dt,avoid=true){const n=N(dx,dy),step=speed*dt;const go=(a,b)=>{let ok=false,nx=C(p.x+a*step,p.radius,WORLD.width-p.radius);if(!wallAt(nx,p.y,p.radius)){p.x=nx;ok=true}let ny=C(p.y+b*step,p.radius,WORLD.height-p.radius);if(!wallAt(p.x,ny,p.radius)){p.y=ny;ok=true}return ok};if(go(n.x,n.y)||!avoid)return;const s=Math.sin(S.time*2.7+p.x*.013)>0?1:-1;if(!go(-n.y*s,n.x*s))go(n.y*s,-n.x*s)}

function burst(px,py,color,count=6,speed=90){for(let i=0;i<count;i++)S.particles.push({x:px,y:py,vx:R(-speed,speed),vy:R(-speed,speed),life:R(.2,.65),max:.65,color,size:R(2,5),kind:'spark'})}
function dashFx(){const p=S.player;for(let i=0;i<16;i++){const a=Math.PI*2*i/16;S.particles.push({x:p.x,y:p.y,vx:Math.cos(a)*R(80,210),vy:Math.sin(a)*R(80,210),life:.35,max:.35,color:'#74d3ff',size:R(3,7),kind:'dash'})}}
function trail(){const p=S.player;S.particles.push({x:p.x,y:p.y,vx:0,vy:0,life:.24,max:.24,color:'#74d3ff',size:p.radius*1.6,kind:'ghost'})}
function fire(o,tx,ty,enemy=false,damage=PLAYER.gunDamage,speed=PLAYER.bulletSpeed){const n=N(tx-o.x,ty-o.y),b={x:o.x+n.x*(o.radius||10),y:o.y+n.y*(o.radius||10),vx:n.x*speed,vy:n.y*speed,radius:4,life:1.5,damage};(enemy?S.enemyBullets:S.bullets).push(b)}
function sword(a,damage=PLAYER.swordDamage){const aim=a===S.player?{x:Math.cos(a.angle),y:Math.sin(a.angle)}:a.aim;for(const e of S.enemies){if(e.spawnDelay>0||e.hp<=0)continue;const dx=e.x-a.x,dy=e.y-a.y,d=Math.hypot(dx,dy);if(d>PLAYER.swordRange+e.radius)continue;const n=N(dx,dy);if(n.x*aim.x+n.y*aim.y<.15)continue;e.hp-=damage;burst(e.x,e.y,'#d9f6ff',4,70)}S.particles.push({x:a.x+aim.x*34,y:a.y+aim.y*34,vx:0,vy:0,life:.14,max:.14,color:'#e8f4ff',size:38,kind:'slash',angle:Math.atan2(aim.y,aim.x)})}

function spawn(type,delay=0){const edge=Math.floor(Math.random()*4);let px,py;if(edge===0){px=R(0,WORLD.width);py=-30}else if(edge===1){px=WORLD.width+30;py=R(0,WORLD.height)}else if(edge===2){px=R(0,WORLD.width);py=WORLD.height+30}else{px=-30;py=R(0,WORLD.height)}const q=ENEMIES[type],sc=1+S.wave*.09;S.enemies.push({type,x:px,y:py,spawnDelay:delay,hp:q.hp*sc,maxHp:q.hp*sc,speed:q.speed*(1+S.wave*.012),damage:q.damage*(1+S.wave*.06),radius:q.radius,reward:q.reward,color:q.color,cd:R(0,.5),shoot:R(.2,1.1)})}
function wave(){S.wave++;S.phase='wave';S.phaseTime=WORLD.baseWaveSeconds+S.wave*2;for(let i=0;i<6+S.wave*3;i++){const r=Math.random(),t=i<S.wave/2&&r<.22?'runner':r<Math.min(.12+S.wave*.02,.35)?'brute':r<.5?'spitter':'grunt';spawn(t,i*.34)}if(S.wave%5===0)spawn('boss',2);banner(S.wave%5===0?`WAVE ${S.wave} · BOSS INBOUND`:`WAVE ${S.wave}`,2000)}
function nearestEnemy(o,range=1e9){let z=null,d=range;for(const e of S.enemies)if(e.spawnDelay<=0&&e.hp>0&&D(o,e)<d){d=D(o,e);z=e}return z}
function nearestNode(o,range=1e9){let z=null,d=range;for(const n of S.nodes)if(n.hp>0&&D(o,n)<d){d=D(o,n);z=n}return z}
function nearestDamaged(o,range=1e9){let z=null,d=range;for(const b of S.buildings)if(b.hp<b.maxHp&&D(o,b)<d){d=D(o,b);z=b}return z}
function blocking(e){const dx=S.heart.x-e.x,dy=S.heart.y-e.y,l=Math.hypot(dx,dy)||1,ux=dx/l,uy=dy/l;let z=null,best=110;for(const b of S.buildings){if(b.hp<=0)continue;const vx=b.x-e.x,vy=b.y-e.y,along=vx*ux+vy*uy,perp=Math.abs(vx*uy-vy*ux),rr=Math.max(b.gw,b.gh)*G()/2+e.radius,d=D(e,b);if(along>=0&&along<=140&&perp<rr&&d<best){best=d;z=b}}return z}
function secondary(e){let z=null,best=95;for(const p of[S.player,...S.ais])if(p.hp>0&&D(e,p)<best){best=D(e,p);z=p}return z}
function harvest(n){S.res[n.type==='tree'?'wood':'stone']+=n.type==='tree'?22:18;if(Math.random()<.2)S.res.crystal+=1+Math.floor(Math.random()*2);burst(n.x,n.y,n.type==='tree'?'#5e9a67':'#8b929a',10);n.hp=0;setTimeout(()=>{n.x=R(80,WORLD.width-80);n.y=R(80,WORLD.height-80);n.hp=n.maxHp},12000+Math.random()*7000)}

function playerTick(dt){const p=S.player;if(p.hp<=0){p.hp=Math.min(p.maxHp,p.hp+28*dt);if(p.hp>=p.maxHp*.5){p.x=S.heart.x;p.y=S.heart.y+105;toast('전선에 복귀했습니다.')}return}p.cd=Math.max(0,p.cd-dt);p.dashCd=Math.max(0,p.dashCd-dt);p.dashT=Math.max(0,p.dashT-dt);p.trail=Math.max(0,p.trail-dt);const dx=(S.keys.has('d')?1:0)-(S.keys.has('a')?1:0),dy=(S.keys.has('s')?1:0)-(S.keys.has('w')?1:0);if(dx||dy)move(p,dx,dy,p.dashT>0?PLAYER.dashSpeed:PLAYER.speed,dt,false);if(p.dashT>0&&p.trail<=0){trail();p.trail=.025}const a=world(S.mouse.x,S.mouse.y);p.angle=Math.atan2(a.y-p.y,a.x-p.x);if(S.mouse.down&&!S.sel&&p.cd<=0){if(S.weapon==='gun'&&has('ranged')){fire(p,a.x,a.y,false,PLAYER.gunDamage);p.cd=PLAYER.fireRate}else{sword(p);p.cd=PLAYER.swordCooldown}}}
function aiTick(dt){for(const a of S.ais){if(a.hp<=0){a.hp+=16*dt;if(a.hp>=a.maxHp*.55){a.x=S.heart.x+R(-70,70);a.y=S.heart.y+R(-70,70)}continue}a.cd=Math.max(0,a.cd-dt);a.gather=Math.max(0,a.gather-dt);const e=nearestEnemy(a,380);if(e){const dx=e.x-a.x,dy=e.y-a.y,d=Math.hypot(dx,dy);a.aim=N(dx,dy);if(has('ranged')&&d>95){if(d>245)move(a,dx,dy,135,dt,true);if(a.cd<=0&&d<300){fire(a,e.x,e.y,false,18+(has('squadTraining')?6:0),620);a.cd=.55}}else{if(d>55)move(a,dx,dy,145,dt,true);if(a.cd<=0&&d<76){sword(a,28+(has('squadTraining')?7:0));a.cd=.55}}continue}const damaged=nearestDamaged(a,230);if(damaged){if(D(a,damaged)>44)move(a,damaged.x-a.x,damaged.y-a.y,110,dt,true);else damaged.hp=Math.min(damaged.maxHp,damaged.hp+18*dt);continue}const n=nearestNode(a,470);if(n&&S.phase!=='wave'){if(D(a,n)>45)move(a,n.x-a.x,n.y-a.y,120,dt,true);else if(a.gather<=0){n.hp-=20;a.gather=.48;if(n.hp<=0)harvest(n)}continue}const i=S.ais.indexOf(a),guard={x:S.heart.x+Math.cos(i*2.1)*110,y:S.heart.y+Math.sin(i*2.1)*110};move(a,guard.x-a.x,guard.y-a.y,105,dt,true)}}
function nodesTick(dt){for(const n of S.nodes)if(n.hp>0&&S.player.hp>0&&S.mouse.down&&!S.sel&&S.weapon==='sword'&&D(S.player,n)<70&&Math.random()<dt*3.5){n.hp-=12;if(n.hp<=0)harvest(n)}}
function buildingTick(dt){for(const b of S.buildings)b.powered=b.type==='generator'||S.buildings.some(q=>q.type==='generator'&&q.hp>0&&D(b,q)<280);for(const b of S.buildings){if(b.hp<=0)continue;b.cd=Math.max(0,b.cd-dt);if(has('fieldRepair')&&S.phase!=='wave'&&b.hp<b.maxHp)b.hp=Math.min(b.maxHp,b.hp+3.5*dt);if(b.type==='turret'){const e=nearestEnemy(b,b.powered?370:270);if(e&&b.cd<=0){fire(b,e.x,e.y,false,b.powered?(has('overcharge')?36:25):17,700);b.cd=b.powered?.38:.58}}if(b.type==='trap')for(const e of S.enemies)if(e.spawnDelay<=0&&D(b,e)<b.radius+e.radius+6)e.hp-=(b.powered?(has('overcharge')?80:62):38)*dt}S.buildings=S.buildings.filter(b=>{if(b.hp>0)return true;burst(b.x,b.y,'#9a7f6f',18);return false})}
function hurtStructure(b,amount,attacker){b.hp=Math.max(0,b.hp-amount*fortMul());if(b.type==='wall'&&has('thorns')&&attacker)attacker.hp=Math.max(0,attacker.hp-8)}
function enemyTick(dt){for(const e of S.enemies){if(e.spawnDelay>0){e.spawnDelay-=dt;continue}e.cd=Math.max(0,e.cd-dt);e.shoot=Math.max(0,e.shoot-dt);if(D(e,S.heart)<S.heart.radius+e.radius+8){if(e.cd<=0){S.heart.hp=Math.max(0,S.heart.hp-e.damage);e.cd=e.type==='boss'?.65:.9}continue}const b=blocking(e);if(b){const d=D(e,b),reach=e.radius+Math.max(b.gw,b.gh)*G()/2+10;if(e.type==='spitter'&&d<280&&e.shoot<=0){fire(e,b.x,b.y,true,e.damage,390);e.shoot=1.4}else if(d<reach){if(e.cd<=0){hurtStructure(b,e.damage,e);e.cd=e.type==='boss'?.6:.85}}else{const n=N(b.x-e.x,b.y-e.y);e.x+=n.x*e.speed*dt;e.y+=n.y*e.speed*dt}continue}const p=secondary(e);if(p){const d=D(e,p);if(e.type==='spitter'&&d<260&&e.shoot<=0){fire(e,p.x,p.y,true,e.damage,390);e.shoot=1.4}else if(d<e.radius+p.radius+7){if(e.cd<=0){p.hp=Math.max(0,p.hp-e.damage);e.cd=.9}}else{const n=N(p.x-e.x,p.y-e.y);e.x+=n.x*e.speed*dt;e.y+=n.y*e.speed*dt}continue}const n=N(S.heart.x-e.x,S.heart.y-e.y),nx=e.x+n.x*e.speed*dt,ny=e.y+n.y*e.speed*dt,ob=structureAt(nx,ny,e.radius);if(ob){if(e.cd<=0){hurtStructure(ob,e.damage,e);e.cd=.85}}else{e.x=nx;e.y=ny}}for(let i=S.enemies.length-1;i>=0;i--){const e=S.enemies[i];if(e.hp<=0){S.res.crystal+=e.reward;S.score+=e.reward*10;burst(e.x,e.y,e.color,e.type==='boss'?28:9);S.enemies.splice(i,1)}}}
function bulletTick(list,dt,enemy=false){for(let i=list.length-1;i>=0;i--){const b=list[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;let h=false;if(enemy){const st=structureAt(b.x,b.y,b.radius);if(st){hurtStructure(st,b.damage);h=true}if(!h&&D(b,S.heart)<b.radius+S.heart.radius){S.heart.hp=Math.max(0,S.heart.hp-b.damage);h=true}if(!h)for(const p of[S.player,...S.ais])if(p.hp>0&&D(b,p)<b.radius+p.radius){p.hp=Math.max(0,p.hp-b.damage);h=true;break}}else for(const e of S.enemies)if(e.spawnDelay<=0&&D(b,e)<b.radius+e.radius){e.hp-=b.damage;h=true;break}if(h||b.life<=0||b.x<0||b.y<0||b.x>WORLD.width||b.y>WORLD.height)list.splice(i,1)}}
function phaseTick(dt){S.phaseTime-=dt;if(S.heart.hp<=0&&!S.over){S.over=true;banner(`HEART LOST · SCORE ${S.score}`,100000)}if(S.over)return;if(S.phase==='prep'&&S.phaseTime<=0){S.phase='warning';S.phaseTime=WORLD.warningSeconds;banner('⚠ MASS MOVEMENT DETECTED',2200)}else if(S.phase==='warning'&&S.phaseTime<=0)wave();else if(S.phase==='wave'&&(S.phaseTime<=0||S.enemies.length===0)){S.phase='prep';S.phaseTime=Math.max(22,WORLD.prepSeconds-S.wave*.8);S.res.wood+=15;S.res.stone+=12;S.res.crystal+=3;banner('WAVE CLEARED · REBUILD',1700)}}

function world(sx,sy){const r=c.getBoundingClientRect();return{x:(sx-r.left)*(c.width/r.width)+S.camera.x,y:(sy-r.top)*(c.height/r.height)+S.camera.y}}
function camera(){S.camera.x=C(S.player.x-c.width/2,0,WORLD.width-c.width);S.camera.y=C(S.player.y-c.height/2,0,WORLD.height-c.height)}
function hud(){U.heartHp.textContent=`${Math.ceil(S.heart.hp)} / ${S.heart.maxHp}`;U.heartBar.style.width=C(S.heart.hp/S.heart.maxHp*100,0,100)+'%';U.waveText.textContent=S.wave?`Wave ${S.wave}`:'준비 중';U.phaseText.textContent=`${S.phase==='prep'?'탐색/건축':S.phase==='warning'?'경고':'침공'} · ${Math.max(0,Math.ceil(S.phaseTime))}s`;U.woodText.textContent=Math.floor(S.res.wood);U.stoneText.textContent=Math.floor(S.res.stone);U.crystalText.textContent=Math.floor(S.res.crystal);U.scoreText.textContent='Score '+S.score;U.teamText.textContent=`1 Player + ${S.ais.length} AI`;U.dashBar.style.width=C((1-S.player.dashCd/PLAYER.dashCooldown)*100,0,100)+'%';U.dashText.textContent=S.player.dashCd<=0?'READY':S.player.dashCd.toFixed(1)+'s';U.weaponText.textContent=S.weapon==='gun'&&has('ranged')?'CARBINE':'SWORD';squadUI()}
function circle(o,color,stroke){x.beginPath();x.arc(o.x-S.camera.x,o.y-S.camera.y,o.radius,0,Math.PI*2);x.fillStyle=color;x.fill();if(stroke){x.strokeStyle=stroke;x.lineWidth=2;x.stroke()}}
function hp(o){if(o.hp>=o.maxHp)return;const w=(o.radius||24)*2,px=o.x-S.camera.x-w/2,py=o.y-S.camera.y-(o.radius||24)-10;x.fillStyle='#351f24';x.fillRect(px,py,w,4);x.fillStyle='#77df9d';x.fillRect(px,py,w*C(o.hp/o.maxHp,0,1),4)}
function draw(){x.fillStyle='#0e1820';x.fillRect(0,0,c.width,c.height);x.save();x.translate(-S.camera.x,-S.camera.y);x.strokeStyle='rgba(91,125,142,.07)';for(let gx=0;gx<WORLD.width;gx+=G()){x.beginPath();x.moveTo(gx,0);x.lineTo(gx,WORLD.height);x.stroke()}for(let gy=0;gy<WORLD.height;gy+=G()){x.beginPath();x.moveTo(0,gy);x.lineTo(WORLD.width,gy);x.stroke()}for(const n of S.nodes)if(n.hp>0){x.fillStyle=n.type==='tree'?'#395d43':'#68717a';x.beginPath();x.arc(n.x,n.y,n.radius,0,Math.PI*2);x.fill()}for(const b of S.buildings){const r=rect(b);x.fillStyle=b.color;x.fillRect(r.x-2,r.y-2,r.w+4,r.h+4);x.strokeStyle=b.powered?'#b7f1ff':'#2f3d4b';x.strokeRect(r.x,r.y,r.w,r.h);if(b.hp<b.maxHp){x.fillStyle='#3b2025';x.fillRect(r.x,r.y-7,r.w,4);x.fillStyle='#77df9d';x.fillRect(r.x,r.y-7,r.w*b.hp/b.maxHp,4)}}x.restore();circle(S.heart,'#77d7ff','#d9f6ff');for(const e of S.enemies)if(e.spawnDelay<=0){circle(e,e.color,e.type==='boss'?'#ffd0df':null);hp(e)}for(const a of S.ais)if(a.hp>0){circle(a,a.color);hp(a);x.fillStyle='#dce9f5';x.font='10px system-ui';x.textAlign='center';x.fillText(a.name,a.x-S.camera.x,a.y-S.camera.y-20)}if(S.player.hp>0){circle(S.player,S.player.color,'#74d3ff');x.strokeStyle='#74d3ff';x.beginPath();x.moveTo(S.player.x-S.camera.x,S.player.y-S.camera.y);x.lineTo(S.player.x-S.camera.x+Math.cos(S.player.angle)*26,S.player.y-S.camera.y+Math.sin(S.player.angle)*26);x.stroke();hp(S.player)}for(const b of S.bullets)circle(b,'#d9f6ff');for(const b of S.enemyBullets)circle(b,'#ff9d9d');for(const p of S.particles){x.globalAlpha=C(p.life/p.max,0,1);if(p.kind==='slash'){x.strokeStyle=p.color;x.lineWidth=6;x.beginPath();x.arc(p.x-S.camera.x,p.y-S.camera.y,22,p.angle-.8,p.angle+.8);x.stroke()}else{x.fillStyle=p.color;x.beginPath();x.arc(p.x-S.camera.x,p.y-S.camera.y,p.size,0,Math.PI*2);x.fill()}x.globalAlpha=1}if(S.sel){const w=world(S.mouse.x,S.mouse.y),f=fp(S.sel,w.x,w.y),b=BUILDINGS[S.sel];x.globalAlpha=.35;x.fillStyle=b.color;x.fillRect(f.gx*G()-S.camera.x,f.gy*G()-S.camera.y,f.gw*G(),f.gh*G());x.globalAlpha=1}}
function frame(now){const dt=Math.min((now-S.last)/1000,.033);S.last=now;if(!S.over){S.time+=dt;playerTick(dt);aiTick(dt);nodesTick(dt);buildingTick(dt);enemyTick(dt);bulletTick(S.bullets,dt,false);bulletTick(S.enemyBullets,dt,true);phaseTick(dt);for(let i=S.particles.length-1;i>=0;i--){const p=S.particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.life<=0)S.particles.splice(i,1)}camera();hud()}draw();requestAnimationFrame(frame)}

window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();S.keys.add(k);if(['1','2','3','4'].includes(k)){const key=Object.keys(BUILDINGS)[Number(k)-1];if(key)pick(key)}if(k==='x'){S.sel=null;buildUI();info()}if(k==='q'&&has('ranged')){S.weapon=S.weapon==='sword'?'gun':'sword';toast(S.weapon==='gun'?'카빈 장착':'검 장착')}if(e.code==='Space'&&S.player.dashCd<=0&&S.player.hp>0){S.player.dashCd=PLAYER.dashCooldown;S.player.dashT=PLAYER.dashDuration;dashFx();e.preventDefault()}});window.addEventListener('keyup',e=>S.keys.delete(e.key.toLowerCase()));
c.addEventListener('mousemove',e=>{S.mouse.x=e.clientX;S.mouse.y=e.clientY});c.addEventListener('mousedown',e=>{S.mouse.x=e.clientX;S.mouse.y=e.clientY;if(e.button===0){if(S.sel){const w=world(e.clientX,e.clientY);place(S.sel,w.x,w.y)}else S.mouse.down=true}else if(e.button===2){const w=world(e.clientX,e.clientY);remove(w.x,w.y)}});window.addEventListener('mouseup',e=>{if(e.button===0)S.mouse.down=false});c.addEventListener('contextmenu',e=>e.preventDefault());
$('helpButton').onclick=()=>$('helpDialog').showModal();$('restartButton').onclick=reset;reset();requestAnimationFrame(frame);
