import {WORLD,PLAYER,BUILDINGS,ENEMIES,AI_ROLES} from './config.js';

const canvas=document.getElementById('gameCanvas');
const ctx=canvas.getContext('2d');
const ui={heartHp:document.getElementById('heartHp'),heartBar:document.getElementById('heartBar'),waveText:document.getElementById('waveText'),phaseText:document.getElementById('phaseText'),woodText:document.getElementById('woodText'),stoneText:document.getElementById('stoneText'),crystalText:document.getElementById('crystalText'),teamText:document.getElementById('teamText'),scoreText:document.getElementById('scoreText'),buildList:document.getElementById('buildList'),squadList:document.getElementById('squadList'),banner:document.getElementById('banner'),toast:document.getElementById('toast')};

const state={time:0,last:performance.now(),keys:new Set(),mouse:{x:0,y:0,worldX:0,worldY:0,down:false},camera:{x:0,y:0},phase:'prep',phaseTime:WORLD.prepSeconds,wave:0,score:0,resources:{wood:90,stone:70,crystal:15},selectedBuild:null,order:'defend',gameOver:false,weaponLevel:1,aiLevel:1,heart:{...WORLD.heart,hp:WORLD.heart.maxHp},bullets:[],enemyBullets:[],enemies:[],buildings:[],nodes:[],particles:[],ais:[],player:null};

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const rand=(a,b)=>a+Math.random()*(b-a);
const norm=(x,y)=>{const m=Math.hypot(x,y)||1;return{x:x/m,y:y/m};};
const circleHit=(a,b,pad=0)=>Math.hypot(a.x-b.x,a.y-b.y)<(a.radius||a.size/2||0)+(b.radius||b.size/2||0)+pad;

function makePlayer(){return{x:WORLD.heart.x,y:WORLD.heart.y+100,radius:PLAYER.radius,hp:PLAYER.maxHp,maxHp:PLAYER.maxHp,angle:0,shootCd:0,dashCd:0,dashT:0,color:'#e9f4ff'};}
function makeAI(i){const spec=AI_ROLES[i];return{x:WORLD.heart.x+rand(-90,90),y:WORLD.heart.y+rand(-90,90),radius:12,hp:115,maxHp:115,shootCd:0,target:null,role:spec.role,name:spec.name,color:spec.accent,gatherCd:0,buildCd:0};}

function seedWorld(){state.nodes=[];for(let i=0;i<62;i++){const ang=Math.random()*Math.PI*2;const r=rand(250,980);state.nodes.push({type:Math.random()<.58?'tree':'rock',x:clamp(WORLD.heart.x+Math.cos(ang)*r,70,WORLD.width-70),y:clamp(WORLD.heart.y+Math.sin(ang)*r,70,WORLD.height-70),radius:Math.random()<.58?24:22,hp:85,maxHp:85});}}
function reset(){state.time=0;state.last=performance.now();state.phase='prep';state.phaseTime=WORLD.prepSeconds;state.wave=0;state.score=0;state.gameOver=false;state.weaponLevel=1;state.aiLevel=1;state.heart={...WORLD.heart,hp:WORLD.heart.maxHp};state.resources={wood:90,stone:70,crystal:15};state.bullets=[];state.enemyBullets=[];state.enemies=[];state.buildings=[];state.particles=[];state.player=makePlayer();state.ais=AI_ROLES.map((_,i)=>makeAI(i));seedWorld();showBanner('BUILD PHASE',1500);renderBuildButtons();}

function showBanner(text,ms=1600){ui.banner.textContent=text;ui.banner.classList.remove('hidden');clearTimeout(showBanner.t);showBanner.t=setTimeout(()=>ui.banner.classList.add('hidden'),ms);}
function toast(text){ui.toast.textContent=text;ui.toast.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>ui.toast.classList.add('hidden'),1400);}
function toggleBuildSelection(key){state.selectedBuild=state.selectedBuild===key?null:key;renderBuildButtons();}

function renderBuildButtons(){ui.buildList.innerHTML='';Object.entries(BUILDINGS).forEach(([key,b],i)=>{const btn=document.createElement('button');btn.className='build-item'+(state.selectedBuild===key?' active':'');btn.innerHTML=`<span>${i+1}. ${b.label}</span><small>${b.wood||0}W ${b.stone||0}S ${b.crystal||0}C</small>`;btn.addEventListener('click',()=>toggleBuildSelection(key));ui.buildList.appendChild(btn);});}
function renderSquad(){ui.squadList.innerHTML='';state.ais.forEach(ai=>{const el=document.createElement('div');el.className='squad-member';el.innerHTML=`<b style="color:${ai.color}">${ai.name}</b><small>${ai.role} · ${Math.max(0,Math.ceil(ai.hp))}/${ai.maxHp}</small>`;ui.squadList.appendChild(el);});}

function canAfford(b){return state.resources.wood>=(b.wood||0)&&state.resources.stone>=(b.stone||0)&&state.resources.crystal>=(b.crystal||0);}
function spend(b){state.resources.wood-=b.wood||0;state.resources.stone-=b.stone||0;state.resources.crystal-=b.crystal||0;}
function buildingsOverlapTooMuch(a,b){const allowedOverlap=Math.min(a.size,b.size)*.28;return dist(a,b)<a.radius+b.radius-allowedOverlap;}
function wallBlocksCircle(x,y,radius){for(const b of state.buildings){if(b.type!=='wall'||b.hp<=0)continue;const half=b.size/2;const nearestX=clamp(x,b.x-half,b.x+half);const nearestY=clamp(y,b.y-half,b.y+half);if(Math.hypot(x-nearestX,y-nearestY)<radius)return true;}return false;}
function placeBuilding(type,x,y,free=false){const b=BUILDINGS[type];if(!b)return false;if(!free&&!canAfford(b)){toast('자원이 부족합니다.');return false;}x=clamp(x,b.size,WORLD.width-b.size);y=clamp(y,b.size,WORLD.height-b.size);const candidate={type,x,y,size:b.size,radius:b.size*.55,hp:b.hp,maxHp:b.hp,powered:false,cooldown:0,color:b.color};if(dist(candidate,state.heart)<95||state.buildings.some(o=>buildingsOverlapTooMuch(candidate,o))){if(!free)toast('여기에는 설치할 수 없습니다.');return false;}if(type==='wall'&&state.player?.hp>0&&wallWouldTrapPlayer(candidate,state.player)){if(!free)toast('플레이어와 너무 겹치게 벽을 설치할 수 없습니다.');return false;}if(!free)spend(b);state.buildings.push(candidate);burst(x,y,b.color,10);return true;}
function wallWouldTrapPlayer(wall,player){const half=wall.size/2;const nearestX=clamp(player.x,wall.x-half,wall.x+half);const nearestY=clamp(player.y,wall.y-half,wall.y+half);return Math.hypot(player.x-nearestX,player.y-nearestY)<player.radius+2;}
function removeAt(x,y){for(let i=state.buildings.length-1;i>=0;i--){if(dist({x,y},state.buildings[i])<state.buildings[i].radius+8){const b=state.buildings[i];state.resources.wood+=Math.floor((BUILDINGS[b.type].wood||0)*.35);state.resources.stone+=Math.floor((BUILDINGS[b.type].stone||0)*.35);state.buildings.splice(i,1);return;}}}

function fire(origin,tx,ty,team='friendly',damage=PLAYER.damage,speed=PLAYER.bulletSpeed){const d=norm(tx-origin.x,ty-origin.y);const list=team==='enemy'?state.enemyBullets:state.bullets;list.push({x:origin.x+d.x*(origin.radius||10),y:origin.y+d.y*(origin.radius||10),vx:d.x*speed,vy:d.y*speed,radius:4,life:1.5,damage,team});}
function hurt(target,amount){target.hp-=amount;if(target.hp<=0)target.hp=0;}
function burst(x,y,color,count=6){for(let i=0;i<count;i++)state.particles.push({x,y,vx:rand(-90,90),vy:rand(-90,90),life:rand(.25,.7),color,size:rand(2,5)});}

function spawnWave(){state.wave++;state.phase='wave';state.phaseTime=WORLD.baseWaveSeconds+state.wave*2;const count=6+state.wave*3;for(let i=0;i<count;i++)spawnEnemy(i<Math.floor(state.wave/2)&&Math.random()<.25?'runner':Math.random()<Math.min(.12+state.wave*.02,.35)?'brute':Math.random()<.18?'spitter':'grunt',i*.35);if(state.wave%5===0)spawnEnemy('boss',2);showBanner(state.wave%5===0?`WAVE ${state.wave} · BOSS INBOUND`:`WAVE ${state.wave}`,2200);}
function spawnEnemy(type,delay=0){const edge=Math.floor(Math.random()*4);let x,y;if(edge===0){x=rand(0,WORLD.width);y=-30}else if(edge===1){x=WORLD.width+30;y=rand(0,WORLD.height)}else if(edge===2){x=rand(0,WORLD.width);y=WORLD.height+30}else{x=-30;y=rand(0,WORLD.height)}const base=ENEMIES[type];state.enemies.push({type,x,y,spawnDelay:delay,hp:base.hp*(1+state.wave*.09),maxHp:base.hp*(1+state.wave*.09),speed:base.speed*(1+state.wave*.012),damage:base.damage*(1+state.wave*.06),radius:base.radius,reward:base.reward,color:base.color,attackCd:rand(0,.5),shootCd:rand(.2,1.1)});}

function nearestEnemy(entity,range=Infinity){let best=null,bd=range;for(const e of state.enemies){if(e.spawnDelay>0||e.hp<=0)continue;const d=dist(entity,e);if(d<bd){bd=d;best=e;}}return best;}
function nearestNode(entity,range=Infinity){let best=null,bd=range;for(const n of state.nodes){if(n.hp<=0)continue;const d=dist(entity,n);if(d<bd){bd=d;best=n;}}return best;}
function nearestDamagedBuilding(entity,range=Infinity){let best=null,bd=range;for(const b of state.buildings){if(b.hp>=b.maxHp)continue;const d=dist(entity,b);if(d<bd){bd=d;best=b;}}return best;}
function moveToward(e,target,speed,dt){if(!target)return;const d=norm(target.x-e.x,target.y-e.y);e.x+=d.x*speed*dt;e.y+=d.y*speed*dt;}

function updatePlayer(dt){const p=state.player;if(p.hp<=0){p.hp=Math.min(p.maxHp,p.hp+30*dt);if(p.hp>=p.maxHp*.5){p.x=state.heart.x;p.y=state.heart.y+90;toast('전선에 복귀했습니다.');}return;}let dx=(state.keys.has('d')?1:0)-(state.keys.has('a')?1:0);let dy=(state.keys.has('s')?1:0)-(state.keys.has('w')?1:0);const d=norm(dx,dy);p.dashCd=Math.max(0,p.dashCd-dt);p.dashT=Math.max(0,p.dashT-dt);const speed=p.dashT>0?PLAYER.dashSpeed:PLAYER.speed;if(dx||dy){const nextX=clamp(p.x+d.x*speed*dt,p.radius,WORLD.width-p.radius);if(!wallBlocksCircle(nextX,p.y,p.radius))p.x=nextX;const nextY=clamp(p.y+d.y*speed*dt,p.radius,WORLD.height-p.radius);if(!wallBlocksCircle(p.x,nextY,p.radius))p.y=nextY;}p.shootCd=Math.max(0,p.shootCd-dt);const aim=screenToWorld(state.mouse.x,state.mouse.y);p.angle=Math.atan2(aim.y-p.y,aim.x-p.x);if(state.mouse.down&&!state.selectedBuild&&p.shootCd<=0){fire(p,aim.x,aim.y,'friendly',PLAYER.damage*(1+(state.weaponLevel-1)*.28));p.shootCd=PLAYER.fireRate/(1+(state.weaponLevel-1)*.08);}}

function updateAI(dt){for(const ai of state.ais){if(ai.hp<=0){ai.hp+=18*dt;if(ai.hp>=ai.maxHp*.55){ai.x=state.heart.x+rand(-55,55);ai.y=state.heart.y+rand(-55,55);}continue;}ai.shootCd=Math.max(0,ai.shootCd-dt);ai.gatherCd=Math.max(0,ai.gatherCd-dt);ai.buildCd=Math.max(0,ai.buildCd-dt);const enemy=nearestEnemy(ai,330+state.aiLevel*35);if(enemy){moveToward(ai,enemy,ai.role==='Vanguard'?155:125,dt);if(dist(ai,enemy)<280&&ai.shootCd<=0){fire(ai,enemy.x,enemy.y,'friendly',18*(1+(state.aiLevel-1)*.25),620);ai.shootCd=.5/(1+(state.aiLevel-1)*.09);}continue;}if(state.order==='follow'){moveToward(ai,state.player,135,dt);continue;}if(state.order==='repair'||ai.role==='Builder'){const b=nearestDamagedBuilding(ai,360);if(b){moveToward(ai,b,115,dt);if(dist(ai,b)<42){b.hp=Math.min(b.maxHp,b.hp+(24+state.aiLevel*5)*dt);}if(ai.role==='Builder'&&state.phase!=='wave'&&ai.buildCd<=0&&state.resources.wood>28&&state.resources.stone>14){const ang=Math.random()*Math.PI*2;if(placeBuilding('wall',state.heart.x+Math.cos(ang)*rand(125,190),state.heart.y+Math.sin(ang)*rand(125,190))){ai.buildCd=6;}}continue;}}if(state.order==='gather'||ai.role==='Gatherer'){const node=nearestNode(ai,460);if(node){moveToward(ai,node,125,dt);if(dist(ai,node)<44&&ai.gatherCd<=0){node.hp-=24;ai.gatherCd=.45;if(node.hp<=0)harvestNode(node,ai);}continue;}}const guard={x:state.heart.x+Math.cos(state.ais.indexOf(ai)*2.1)*105,y:state.heart.y+Math.sin(state.ais.indexOf(ai)*2.1)*105};moveToward(ai,guard,110,dt);}}

function harvestNode(n,who){if(n.type==='tree')state.resources.wood+=22;else state.resources.stone+=18;if(Math.random()<.18)state.resources.crystal+=1+Math.floor(Math.random()*2);burst(n.x,n.y,n.type==='tree'?'#5e9a67':'#8b929a',12);n.hp=0;setTimeout(()=>{n.x=rand(80,WORLD.width-80);n.y=rand(80,WORLD.height-80);n.hp=n.maxHp;},12000+Math.random()*9000);if(who===state.player)state.score+=2;}

function updateNodes(dt){for(const n of state.nodes){if(n.hp<=0)continue;if(state.player.hp>0&&state.mouse.down&&!state.selectedBuild&&dist(state.player,n)<76&&Math.random()<dt*4){n.hp-=14;if(n.hp<=0)harvestNode(n,state.player);}}}

function updateBuildings(dt){for(const b of state.buildings)b.powered=b.type==='generator'||state.buildings.some(g=>g.type==='generator'&&g.hp>0&&dist(b,g)<280);for(const b of state.buildings){if(b.hp<=0)continue;b.cooldown=Math.max(0,b.cooldown-dt);if(b.type==='turret'){const e=nearestEnemy(b,b.powered?360:260);if(e&&b.cooldown<=0){fire({...b,radius:10},e.x,e.y,'friendly',b.powered?25:17,700);b.cooldown=b.powered?.36:.58;}}else if(b.type==='trap'){for(const e of state.enemies){if(e.spawnDelay<=0&&dist(b,e)<b.radius+e.radius+6){e.hp-=(b.powered?62:38)*dt;}}}}state.buildings=state.buildings.filter(b=>{if(b.hp>0)return true;burst(b.x,b.y,'#8b7b70',16);return false;});}

function chooseEnemyTarget(e){let target=state.heart,bd=dist(e,state.heart);for(const b of state.buildings){if(b.hp<=0)continue;const d=dist(e,b);if(d<95&&d<bd){target=b;bd=d;}}const candidates=[state.player,...state.ais].filter(x=>x.hp>0);for(const c of candidates){const d=dist(e,c);if(d<75&&d<bd){target=c;bd=d;}}return target;}
function updateEnemies(dt){for(const e of state.enemies){if(e.spawnDelay>0){e.spawnDelay-=dt;continue;}e.attackCd=Math.max(0,e.attackCd-dt);e.shootCd=Math.max(0,e.shootCd-dt);const target=chooseEnemyTarget(e);const d=dist(e,target);if(e.type==='spitter'&&d<300&&e.shootCd<=0){fire(e,target.x,target.y,'enemy',e.damage,380);e.shootCd=1.45;}else if(d<(target.radius||target.size/2||20)+e.radius+8){if(e.attackCd<=0){hurt(target,e.damage);e.attackCd=e.type==='boss'?.65:.9;burst(target.x,target.y,e.color,4);}}else moveToward(e,target,e.speed,dt);}for(let i=state.enemies.length-1;i>=0;i--){const e=state.enemies[i];if(e.hp<=0){state.resources.crystal+=e.reward;state.score+=e.reward*10;burst(e.x,e.y,e.color,e.type==='boss'?30:10);state.enemies.splice(i,1);}}}

function updateBullets(list,dt,isEnemy=false){for(let i=list.length-1;i>=0;i--){const b=list[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;let hit=false;if(isEnemy){for(const t of [state.player,...state.ais]){if(t.hp>0&&dist(b,t)<b.radius+t.radius){hurt(t,b.damage);hit=true;break;}}if(!hit&&dist(b,state.heart)<b.radius+state.heart.radius){hurt(state.heart,b.damage);hit=true;}}else{for(const e of state.enemies){if(e.spawnDelay<=0&&dist(b,e)<b.radius+e.radius){hurt(e,b.damage);hit=true;break;}}}if(hit||b.life<=0||b.x<0||b.y<0||b.x>WORLD.width||b.y>WORLD.height){if(hit)burst(b.x,b.y,isEnemy?'#e87e7e':'#d9f6ff',3);list.splice(i,1);}}}

function updatePhase(dt){state.phaseTime-=dt;if(state.gameOver)return;if(state.heart.hp<=0){state.gameOver=true;showBanner(`HEART LOST · SCORE ${state.score}`,100000);return;}if(state.phase==='prep'&&state.phaseTime<=0){state.phase='warning';state.phaseTime=WORLD.warningSeconds;showBanner('⚠ MASS MOVEMENT DETECTED',2500);}else if(state.phase==='warning'&&state.phaseTime<=0)spawnWave();else if(state.phase==='wave'&&(state.phaseTime<=0||state.enemies.length===0)){state.phase='prep';state.phaseTime=Math.max(22,WORLD.prepSeconds-state.wave*.8);state.resources.wood+=15;state.resources.stone+=12;state.resources.crystal+=3;showBanner('WAVE CLEARED · REBUILD',1700);}}

function updateCamera(){const viewW=canvas.width,viewH=canvas.height;state.camera.x=clamp(state.player.x-viewW/2,0,WORLD.width-viewW);state.camera.y=clamp(state.player.y-viewH/2,0,WORLD.height-viewH);}
function screenToWorld(sx,sy){const r=canvas.getBoundingClientRect();return{x:(sx-r.left)*(canvas.width/r.width)+state.camera.x,y:(sy-r.top)*(canvas.height/r.height)+state.camera.y};}

function updateUI(){ui.heartHp.textContent=`${Math.ceil(state.heart.hp)} / ${state.heart.maxHp}`;ui.heartBar.style.width=`${clamp(state.heart.hp/state.heart.maxHp*100,0,100)}%`;ui.waveText.textContent=state.wave?`Wave ${state.wave}`:'준비 중';ui.phaseText.textContent=`${state.phase==='prep'?'탐색/건축':state.phase==='warning'?'경고':'침공'} · ${Math.max(0,Math.ceil(state.phaseTime))}s`;ui.woodText.textContent=Math.floor(state.resources.wood);ui.stoneText.textContent=Math.floor(state.resources.stone);ui.crystalText.textContent=Math.floor(state.resources.crystal);ui.scoreText.textContent=`Score ${state.score}`;renderSquad();}

function drawGrid(){ctx.fillStyle='#0e1820';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.save();ctx.translate(-state.camera.x,-state.camera.y);ctx.strokeStyle='rgba(91,125,142,.07)';ctx.lineWidth=1;for(let x=0;x<WORLD.width;x+=50){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,WORLD.height);ctx.stroke()}for(let y=0;y<WORLD.height;y+=50){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(WORLD.width,y);ctx.stroke()}ctx.restore();}
function drawCircle(o,color,outline=null){ctx.beginPath();ctx.arc(o.x-state.camera.x,o.y-state.camera.y,o.radius,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();if(outline){ctx.strokeStyle=outline;ctx.lineWidth=2;ctx.stroke();}}
function drawHealth(o,yOffset=0){if(o.hp>=o.maxHp)return;const w=(o.radius||20)*2;const x=o.x-state.camera.x-w/2,y=o.y-state.camera.y-(o.radius||20)-10+yOffset;ctx.fillStyle='#371d22';ctx.fillRect(x,y,w,4);ctx.fillStyle='#77df9d';ctx.fillRect(x,y,w*clamp(o.hp/o.maxHp,0,1),4);}
function render(){drawGrid();ctx.save();ctx.translate(-state.camera.x,-state.camera.y);for(const n of state.nodes){if(n.hp<=0)continue;if(n.type==='tree'){ctx.fillStyle='#395d43';ctx.beginPath();ctx.arc(n.x,n.y,n.radius,0,Math.PI*2);ctx.fill();ctx.fillStyle='#644b39';ctx.fillRect(n.x-4,n.y+12,8,18);}else{ctx.fillStyle='#68717a';ctx.beginPath();ctx.arc(n.x,n.y,n.radius,0,Math.PI*2);ctx.fill();}}for(const b of state.buildings){ctx.fillStyle=b.color;ctx.fillRect(b.x-b.size/2,b.y-b.size/2,b.size,b.size);ctx.strokeStyle=b.powered?'#b7f1ff':'#2f3d4b';ctx.lineWidth=b.powered?2:1;ctx.strokeRect(b.x-b.size/2,b.y-b.size/2,b.size,b.size);if(b.type==='turret'){ctx.fillStyle='#20313e';ctx.beginPath();ctx.arc(b.x,b.y,8,0,Math.PI*2);ctx.fill();}if(b.type==='generator'){ctx.fillStyle='rgba(130,210,255,.08)';ctx.beginPath();ctx.arc(b.x,b.y,280,0,Math.PI*2);ctx.fill();}}ctx.restore();drawCircle(state.heart,'#77d7ff','#d9f6ff');ctx.font='bold 12px system-ui';ctx.textAlign='center';ctx.fillStyle='#e9fbff';ctx.fillText('HEART',state.heart.x-state.camera.x,state.heart.y-state.camera.y+4);for(const e of state.enemies){if(e.spawnDelay>0)continue;drawCircle(e,e.color,e.type==='boss'?'#ffd0df':null);drawHealth(e);}for(const ai of state.ais){if(ai.hp<=0)continue;drawCircle(ai,ai.color);ctx.fillStyle='#dce9f5';ctx.font='10px system-ui';ctx.fillText(ai.name,ai.x-state.camera.x,ai.y-state.camera.y-20);drawHealth(ai);}if(state.player.hp>0){drawCircle(state.player,state.player.color,'#74d3ff');ctx.strokeStyle='#74d3ff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(state.player.x-state.camera.x,state.player.y-state.camera.y);ctx.lineTo(state.player.x-state.camera.x+Math.cos(state.player.angle)*25,state.player.y-state.camera.y+Math.sin(state.player.angle)*25);ctx.stroke();drawHealth(state.player);}for(const b of state.bullets)drawCircle(b,'#d9f6ff');for(const b of state.enemyBullets)drawCircle(b,'#ff9d9d');for(const p of state.particles){ctx.globalAlpha=clamp(p.life*2,0,1);ctx.fillStyle=p.color;ctx.fillRect(p.x-state.camera.x,p.y-state.camera.y,p.size,p.size);ctx.globalAlpha=1;}if(state.selectedBuild){const w=screenToWorld(state.mouse.x,state.mouse.y);const b=BUILDINGS[state.selectedBuild];ctx.globalAlpha=.45;ctx.fillStyle=b.color;ctx.fillRect(w.x-state.camera.x-b.size/2,w.y-state.camera.y-b.size/2,b.size,b.size);ctx.globalAlpha=1;}if(state.gameOver){ctx.fillStyle='rgba(0,0,0,.45)';ctx.fillRect(0,0,canvas.width,canvas.height);}}

function step(now){const dt=Math.min((now-state.last)/1000,.033);state.last=now;if(!state.gameOver){state.time+=dt;updatePlayer(dt);updateAI(dt);updateNodes(dt);updateBuildings(dt);updateEnemies(dt);updateBullets(state.bullets,dt,false);updateBullets(state.enemyBullets,dt,true);updatePhase(dt);for(let i=state.particles.length-1;i>=0;i--){const p=state.particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.life<=0)state.particles.splice(i,1);}updateCamera();updateUI();}render();requestAnimationFrame(step);}

window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();state.keys.add(k);if(['1','2','3','4'].includes(k)){const key=Object.keys(BUILDINGS)[Number(k)-1];toggleBuildSelection(key);}if(k==='x'){state.selectedBuild=null;renderBuildButtons();}if(e.code==='Space'&&state.player.dashCd<=0&&state.player.hp>0){state.player.dashCd=PLAYER.dashCooldown;state.player.dashT=PLAYER.dashDuration;e.preventDefault();}});window.addEventListener('keyup',e=>state.keys.delete(e.key.toLowerCase()));
canvas.addEventListener('mousemove',e=>{state.mouse.x=e.clientX;state.mouse.y=e.clientY;});canvas.addEventListener('mousedown',e=>{state.mouse.x=e.clientX;state.mouse.y=e.clientY;if(e.button===0){if(state.selectedBuild){const w=screenToWorld(e.clientX,e.clientY);if(placeBuilding(state.selectedBuild,w.x,w.y))renderBuildButtons();}else state.mouse.down=true;}else if(e.button===2){const w=screenToWorld(e.clientX,e.clientY);removeAt(w.x,w.y);}});window.addEventListener('mouseup',e=>{if(e.button===0)state.mouse.down=false;});canvas.addEventListener('contextmenu',e=>e.preventDefault());

document.querySelectorAll('[data-order]').forEach(btn=>btn.addEventListener('click',()=>{state.order=btn.dataset.order;toast(`AI 명령: ${btn.textContent}`);}));document.getElementById('helpButton').addEventListener('click',()=>document.getElementById('helpDialog').showModal());document.getElementById('restartButton').addEventListener('click',reset);document.getElementById('upgradeWeapon').addEventListener('click',()=>{if(state.resources.crystal<25)return toast('Crystal이 부족합니다.');state.resources.crystal-=25;state.weaponLevel++;toast(`무기 Lv.${state.weaponLevel}`);});document.getElementById('upgradeHeart').addEventListener('click',()=>{if(state.resources.crystal<40)return toast('Crystal이 부족합니다.');state.resources.crystal-=40;state.heart.maxHp+=220;state.heart.hp=Math.min(state.heart.maxHp,state.heart.hp+220);toast(`HEART 최대 체력 ${state.heart.maxHp}`);});document.getElementById('upgradeTeam').addEventListener('click',()=>{if(state.resources.crystal<30)return toast('Crystal이 부족합니다.');state.resources.crystal-=30;state.aiLevel++;toast(`AI 훈련 Lv.${state.aiLevel}`);});

reset();requestAnimationFrame(step);
