export const SUPPORTED_LANGUAGES=['en','ko','ja','zh'];
export function detectLanguage(){
  const saved=localStorage.getItem('rbf.lang');
  if(SUPPORTED_LANGUAGES.includes(saved))return saved;
  const langs=navigator.languages?.length?navigator.languages:[navigator.language||'en'];
  for(const raw of langs){const l=String(raw).toLowerCase();if(l.startsWith('ko'))return'ko';if(l.startsWith('ja'))return'ja';if(l.startsWith('zh'))return'zh';if(l.startsWith('en'))return'en';}
  return'en';
}
export const STRINGS={
 en:{play:'Play',account:'Account',customize:'Customize',settings:'Settings',login:'Log in',signup:'Sign up',logout:'Log out',deleteAccount:'Delete account',quickPlay:'QuickPlay',sameLanguage:'Prefer rooms using my language',createRoom:'Create room',join:'Join',roomName:'Room name',description:'Description',map:'Map',difficulty:'Difficulty',players:'Players',ready:'Ready',unready:'Not ready',startGame:'Start game',waitingReady:'Waiting for everyone to be ready',guest:'Guest',volume:'Volume',language:'Language',reducedMotion:'Reduced motion',chat:'Chat',inventory:'Inventory',crafting:'Crafting',armor:'Armor',revive:'Revive',dead:'Down',deposit:'Deposit',resources:'Resources',currentZone:'Current zone',help:'Help',back:'Back',save:'Save',delete:'Delete',newTemplate:'New template',uploadImage:'Upload image',watchAd:'Watch one ad to unlock image upload',draw:'Draw',stickers:'Stickers',accountRequired:'Sign in to save progress and customization.',roomBrowser:'Open rooms',create:'Create',difficultyEasy:'Easy',difficultyNormal:'Normal',difficultyHard:'Hard',host:'Host',you:'You',spectating:'Waiting for revival',reviveCost:'Revival cost',depositHint:'Carry gathered items back to HEART to bank them.',craft2:'Pocket Crafting · 2×2',craft3:'Workbench · 3×3',craft4:'Grand Workbench · 4×4'},
 ko:{play:'플레이',account:'계정',customize:'커스터마이즈',settings:'설정',login:'로그인',signup:'회원가입',logout:'로그아웃',deleteAccount:'회원탈퇴',quickPlay:'빠른 참가',sameLanguage:'동일 언어 방 접속 우선',createRoom:'방 만들기',join:'참가',roomName:'방 이름',description:'설명',map:'지도',difficulty:'난이도',players:'인원',ready:'준비 완료',unready:'준비 취소',startGame:'게임 시작',waitingReady:'모든 인원이 준비되기를 기다리는 중',guest:'비회원',volume:'소리 볼륨',language:'언어',reducedMotion:'화면 효과 줄이기',chat:'채팅',inventory:'인벤토리',crafting:'제작',armor:'방어구',revive:'부활',dead:'쓰러짐',deposit:'반납',resources:'자원',currentZone:'현재 구역',help:'도움말',back:'뒤로',save:'저장',delete:'삭제',newTemplate:'새 템플릿 추가',uploadImage:'이미지 업로드',watchAd:'광고 1회 시청 후 이미지 업로드 잠금 해제',draw:'그리기',stickers:'스티커',accountRequired:'플레이 기록과 커스터마이즈 저장은 로그인이 필요합니다.',roomBrowser:'열린 방',create:'생성',difficultyEasy:'쉬움',difficultyNormal:'보통',difficultyHard:'어려움',host:'방장',you:'나',spectating:'부활 대기 중',reviveCost:'부활 비용',depositHint:'채집한 아이템은 HEART까지 가져와 반납해야 팀 자원이 됩니다.',craft2:'휴대 제작 · 2×2',craft3:'제작대 · 3×3',craft4:'대형 제작대 · 4×4'},
 ja:{play:'プレイ',account:'アカウント',customize:'カスタマイズ',settings:'設定',login:'ログイン',signup:'新規登録',logout:'ログアウト',deleteAccount:'アカウント削除',quickPlay:'クイックプレイ',sameLanguage:'同じ言語の部屋を優先',createRoom:'ルーム作成',join:'参加',roomName:'ルーム名',description:'説明',map:'マップ',difficulty:'難易度',players:'人数',ready:'準備完了',unready:'準備解除',startGame:'ゲーム開始',waitingReady:'全員の準備完了を待っています',guest:'ゲスト',volume:'音量',language:'言語',reducedMotion:'モーションを減らす',chat:'チャット',inventory:'インベントリ',crafting:'クラフト',armor:'防具',revive:'復活',dead:'ダウン',deposit:'納品',resources:'資源',currentZone:'現在地',help:'ヘルプ',back:'戻る',save:'保存',delete:'削除',newTemplate:'新しいテンプレート',uploadImage:'画像アップロード',watchAd:'広告を1回見て画像アップロードを解放',draw:'描画',stickers:'ステッカー',accountRequired:'進行状況とカスタマイズの保存にはログインが必要です。',roomBrowser:'公開ルーム',create:'作成',difficultyEasy:'簡単',difficultyNormal:'普通',difficultyHard:'難しい',host:'ホスト',you:'自分',spectating:'復活待機中',reviveCost:'復活コスト',depositHint:'採集したアイテムはHEARTへ持ち帰って納品するとチーム資源になります。',craft2:'携帯クラフト · 2×2',craft3:'作業台 · 3×3',craft4:'大型作業台 · 4×4'},
 zh:{play:'开始游戏',account:'账户',customize:'自定义',settings:'设置',login:'登录',signup:'注册',logout:'退出登录',deleteAccount:'删除账户',quickPlay:'快速加入',sameLanguage:'优先加入相同语言房间',createRoom:'创建房间',join:'加入',roomName:'房间名称',description:'说明',map:'地图',difficulty:'难度',players:'人数',ready:'准备',unready:'取消准备',startGame:'开始游戏',waitingReady:'等待所有玩家准备',guest:'游客',volume:'音量',language:'语言',reducedMotion:'减少动态效果',chat:'聊天',inventory:'物品栏',crafting:'制作',armor:'护甲',revive:'复活',dead:'倒下',deposit:'存入',resources:'资源',currentZone:'当前区域',help:'帮助',back:'返回',save:'保存',delete:'删除',newTemplate:'新增模板',uploadImage:'上传图片',watchAd:'观看一次广告后解锁图片上传',draw:'绘制',stickers:'贴纸',accountRequired:'登录后才能保存进度与自定义内容。',roomBrowser:'开放房间',create:'创建',difficultyEasy:'简单',difficultyNormal:'普通',difficultyHard:'困难',host:'房主',you:'你',spectating:'等待复活',reviveCost:'复活费用',depositHint:'采集到的物品必须带回HEART存入，才会成为团队资源。',craft2:'随身制作 · 2×2',craft3:'工作台 · 3×3',craft4:'大型工作台 · 4×4'}
};
export function createI18n(){let lang=detectLanguage();const t=k=>STRINGS[lang]?.[k]??STRINGS.en[k]??k;return{get lang(){return lang},set(next){lang=SUPPORTED_LANGUAGES.includes(next)?next:'en';localStorage.setItem('rbf.lang',lang);document.documentElement.lang=lang;window.dispatchEvent(new CustomEvent('rbf-language',{detail:lang}));},t};}
