export const SUPPORTED_LANGUAGES=['en','ko','ja','zh'];

export function detectLanguage(){
  const saved=localStorage.getItem('rbf.lang');
  if(SUPPORTED_LANGUAGES.includes(saved))return saved;
  const langs=navigator.languages?.length?navigator.languages:[navigator.language||'en'];
  for(const raw of langs){
    const l=String(raw).toLowerCase();
    if(l.startsWith('ko'))return'ko';
    if(l.startsWith('ja'))return'ja';
    if(l.startsWith('zh'))return'zh';
    if(l.startsWith('en'))return'en';
  }
  return'en';
}

const EN={
  play:'Play',account:'Account',customize:'Customize',settings:'Settings',login:'Log in',signup:'Sign up',logout:'Log out',deleteAccount:'Delete account',
  quickPlay:'QuickPlay',sameLanguage:'Prefer rooms using my language',createRoom:'Create room',join:'Join',roomName:'Room name',description:'Description',map:'Map',difficulty:'Difficulty',players:'Players',
  ready:'Ready',unready:'Not ready',startGame:'Start game',waitingReady:'Waiting for everyone to be ready',guest:'Guest',volume:'Volume',language:'Language',reducedMotion:'Reduced motion',highContrast:'High contrast',showTips:'Show game tips',
  chat:'Chat',lobbyChat:'Lobby chat',send:'Send',inventory:'Inventory',crafting:'Crafting',armor:'Armor',revive:'Revive',dead:'Down',deposit:'Deposit',resources:'Resources',currentZone:'Current zone',help:'Help',back:'Back',save:'Save',delete:'Delete',
  newTemplate:'New template',uploadImage:'Upload image',watchAd:'Watch one ad to unlock image upload',draw:'Draw',stickers:'Stickers',accountRequired:'Sign in to save progress and customization.',roomBrowser:'Open rooms',create:'Create',
  difficultyEasy:'Easy',difficultyNormal:'Normal',difficultyHard:'Hard',host:'Host',you:'You',spectating:'Waiting for revival',reviveCost:'Revival cost',depositHint:'Carry gathered items to HEART or a depot to bank them.',
  craft2:'Pocket Crafting · 2×2',craft3:'Workbench · 3×3',craft4:'Grand Workbench · 4×4',username:'Username',password:'Password',credentialsRule:'Username 3+ characters / password 8+ characters.',
  oauthPlanned:'Google and Discord linking can be enabled when provider credentials are configured.',backendRequired:'The account server is not connected.',clear:'Clear',templates:'Templates',noTemplates:'No saved templates.',noRooms:'No rooms are currently open.',
  build:'Build',research:'Research',squad:'Squad',score:'Score',wave:'Wave',clickExpand:'Click to expand',gatherDeposit:'F · gather / deposit',locked:'Locked',outOfBounds:'Out of bounds',occupied:'Occupied',heartClearance:'Too close to HEART',entityInSlot:'A player or monster occupies this slot',
  bankInsufficient:'Not enough banked resources',playerNotFound:'Player not found',noRecipe:'No matching recipe',inventoryFull:'Inventory is full',incoming:'Incoming',recovery:'Recovery',overtime:'OVERTIME',heartLost:'HEART lost',
  roomInfo:'Rooms · QuickPlay · Lobby',accountInfo:'Profile and saved progress',customInfo:'Draw · Stickers · Templates',settingsInfo:'Language · Volume · Accessibility',uploadUnlocked:'Image upload unlocked',adDev:'Ad reward gate is running in development mode.',
  roomSearch:'Search rooms',allDifficulties:'All difficulties',roomCode:'Room code',copy:'Copy',copied:'Copied',addAI:'Add AI player',removeAI:'Remove AI',aiPlayer:'AI player',autoReady:'Auto ready',leaveRoom:'Leave room',leaveWarn:'You will leave the room. Continue?',maxPlayers15:'Maximum players is 15.',startingIn:'Game starts in',cancel:'Cancel',
  pause:'Pause',paused:'Paused',resume:'Resume',restart:'Restart',returnLobby:'Return to lobby',result:'Run result',survivedWaves:'Waves survived',waypoint:'Waypoint',clearWaypoint:'Clear waypoint',
  tutorial:'Field guide',tutorialMove:'Move around and learn the shape of the area.',tutorialGather:'Gather nearby resource nodes and pick up the drops.',tutorialDeposit:'Carry resources to HEART or a depot and deposit them.',tutorialBuild:'Use the Builder Kit to place defenses and support structures.',tutorialResearch:'Spend banked Crystal on research that changes your fortress.',tutorialChat:'Use chat to coordinate. Whisper with /w <player> <message>.',
  tips:'Tips',tipRoles:'There are no fixed classes. Divide gathering, hauling, building, scouting and defense naturally.',tipLogistics:'Forward depots shorten dangerous hauling routes.',tipOvertime:'A wave does not end until the remaining enemies are cleared.',
  res_wood:'Wood',res_stone:'Stone',res_fiber:'Fiber',res_iron:'Iron',res_crystal:'Crystal',res_quartz:'Quartz',res_herb:'Herb',res_resin:'Resin',res_scrap:'Scrap',res_copper:'Copper',
  zone_greenwood:'Greenwood',zone_stonefall:'Stonefall Quarry',zone_crystalreach:'Crystal Reach',zone_mire:'Verdant Mire',zone_heartlands:'Heartlands',zone_scrapyard:'Old Scrapyard',
  build_wall:'Wall',build_generator:'Generator',build_relay:'Repair Relay',build_depot:'Supply Depot',
  item_fieldTool:'Field Tool',item_surveyTool:'Survey Tool',item_builderKit:'Builder Kit',item_armorShell:'Reinforced Shell',item_workbench:'Workbench',item_grandWorkbench:'Grand Workbench',item_plank:'Board',item_cord:'Cord',item_metalPlate:'Metal Plate',item_circuit:'Circuit',
  research_wallI:'Reinforced Wall I',research_wallII:'Reinforced Wall II',research_fortify:'Structural Fortification',research_corePlating:'HEART Plating',research_powerGrid:'Power Grid',research_fieldRepair:'Field Repair',research_logistics:'Logistics',research_rescue:'Rescue Protocol',research_survey:'Resource Surveying'
};

const KO={
  play:'플레이',account:'계정',customize:'커스터마이즈',settings:'설정',login:'로그인',signup:'회원가입',logout:'로그아웃',deleteAccount:'회원탈퇴',quickPlay:'빠른 참가',sameLanguage:'동일 언어 방 접속 우선',createRoom:'방 만들기',join:'참가',roomName:'방 이름',description:'설명',map:'지도',difficulty:'난이도',players:'인원',
  ready:'준비 완료',unready:'준비중',startGame:'게임 시작',waitingReady:'모든 인원이 준비되기를 기다리는 중',guest:'비회원',volume:'소리 볼륨',language:'언어',reducedMotion:'화면 효과 줄이기',highContrast:'고대비 UI',showTips:'게임 팁 표시',chat:'채팅',lobbyChat:'방 채팅',send:'보내기',inventory:'인벤토리',crafting:'제작',armor:'방어구',revive:'부활',dead:'쓰러짐',deposit:'반납',resources:'자원',currentZone:'현재 구역',help:'도움말',back:'뒤로',save:'저장',delete:'삭제',
  newTemplate:'새 템플릿 추가',uploadImage:'이미지 업로드',watchAd:'광고 1회 시청 후 이미지 업로드 잠금 해제',draw:'그리기',stickers:'스티커',accountRequired:'플레이 기록과 커스터마이즈 저장은 로그인이 필요합니다.',roomBrowser:'열린 방',create:'생성',difficultyEasy:'쉬움',difficultyNormal:'보통',difficultyHard:'어려움',host:'방장',you:'나',spectating:'부활 대기 중',reviveCost:'부활 비용',depositHint:'채집한 아이템은 HEART 또는 보급고까지 운반해 반납해야 팀 자원이 됩니다.',
  craft2:'휴대 제작 · 2×2',craft3:'제작대 · 3×3',craft4:'대형 제작대 · 4×4',username:'사용자 이름',password:'비밀번호',credentialsRule:'사용자 이름 3자 이상 / 비밀번호 8자 이상',oauthPlanned:'Google·Discord 연동은 공급자 인증키를 설정하면 활성화할 수 있습니다.',backendRequired:'계정 서버가 연결되지 않았습니다.',clear:'초기화',templates:'템플릿',noTemplates:'저장된 템플릿이 없습니다.',noRooms:'현재 열린 방이 없습니다.',
  build:'건설',research:'연구',squad:'분대',score:'점수',wave:'웨이브',clickExpand:'클릭하여 확대',gatherDeposit:'F · 채집 / 반납',locked:'잠김',outOfBounds:'지도 밖입니다',occupied:'이미 사용 중인 슬롯입니다',heartClearance:'HEART와 너무 가깝습니다',entityInSlot:'플레이어나 몬스터가 슬롯을 점유하고 있습니다',bankInsufficient:'보관된 자원이 부족합니다',playerNotFound:'플레이어를 찾을 수 없습니다',noRecipe:'일치하는 제작법이 없습니다',inventoryFull:'인벤토리가 가득 찼습니다',incoming:'침공 접근',recovery:'복구 단계',overtime:'연장전',heartLost:'HEART 파괴',
  roomInfo:'방 목록 · 빠른 참가 · 로비',accountInfo:'프로필 및 저장된 진행도',customInfo:'그리기 · 스티커 · 템플릿',settingsInfo:'언어 · 볼륨 · 접근성',uploadUnlocked:'이미지 업로드 잠금 해제',adDev:'광고 보상 게이트가 개발 모드로 동작 중입니다.',roomSearch:'방 검색',allDifficulties:'모든 난이도',roomCode:'방 코드',copy:'복사',copied:'복사됨',addAI:'AI 플레이어 추가',removeAI:'AI 제거',aiPlayer:'AI 플레이어',autoReady:'자동 준비 완료',leaveRoom:'방 나가기',leaveWarn:'방에서 나가게 됩니다. 계속하시겠습니까?',maxPlayers15:'최대 인원은 15명입니다.',startingIn:'게임 시작까지',cancel:'취소',
  pause:'일시정지',paused:'일시정지됨',resume:'계속하기',restart:'다시 시작',returnLobby:'로비로 돌아가기',result:'게임 결과',survivedWaves:'생존 웨이브',waypoint:'목적지',clearWaypoint:'목적지 제거',tutorial:'필드 가이드',tutorialMove:'이동하며 주변 지형을 확인하세요.',tutorialGather:'가까운 자원 노드를 채집하고 떨어진 자원을 주우세요.',tutorialDeposit:'자원을 HEART나 보급고까지 운반해 반납하세요.',tutorialBuild:'건설 키트로 방어 및 지원 구조물을 배치하세요.',tutorialResearch:'보관한 크리스탈을 사용해 요새를 발전시키세요.',tutorialChat:'채팅으로 협력하세요. /w <플레이어> <메시지>로 귓속말할 수 있습니다.',tips:'팁',tipRoles:'고정 직업은 없습니다. 채집·운반·건설·정찰·방어를 자연스럽게 역할 분담하는 것이 좋습니다.',tipLogistics:'전방 보급고를 활용하면 위험한 장거리 운반을 줄일 수 있습니다.',tipOvertime:'웨이브는 남은 몬스터를 모두 처리해야 끝납니다.',
  res_wood:'목재',res_stone:'석재',res_fiber:'섬유',res_iron:'철',res_crystal:'크리스탈',res_quartz:'석영',res_herb:'약초',res_resin:'수지',res_scrap:'고철',res_copper:'구리',zone_greenwood:'그린우드',zone_stonefall:'스톤폴 채석장',zone_crystalreach:'크리스탈 리치',zone_mire:'버던트 습지',zone_heartlands:'하트랜드',zone_scrapyard:'오래된 폐기장',build_wall:'벽',build_generator:'발전기',build_relay:'수리 중계기',build_depot:'보급고',item_fieldTool:'필드 툴',item_surveyTool:'조사 도구',item_builderKit:'건설 키트',item_armorShell:'강화 외피',item_workbench:'제작대',item_grandWorkbench:'대형 제작대',item_plank:'가공 판재',item_cord:'끈',item_metalPlate:'금속판',item_circuit:'회로',research_wallI:'강화벽 I',research_wallII:'강화벽 II',research_fortify:'구조 보강',research_corePlating:'HEART 장갑',research_powerGrid:'전력망',research_fieldRepair:'현장 수리',research_logistics:'물류',research_rescue:'구조 프로토콜',research_survey:'자원 조사'
};

const JA={
  play:'プレイ',account:'アカウント',customize:'カスタマイズ',settings:'設定',login:'ログイン',signup:'新規登録',logout:'ログアウト',deleteAccount:'アカウント削除',quickPlay:'クイックプレイ',sameLanguage:'同じ言語の部屋を優先',createRoom:'ルーム作成',join:'参加',roomName:'ルーム名',description:'説明',map:'マップ',difficulty:'難易度',players:'人数',ready:'準備完了',unready:'準備中',startGame:'ゲーム開始',waitingReady:'全員の準備完了を待っています',guest:'ゲスト',volume:'音量',language:'言語',reducedMotion:'モーションを減らす',highContrast:'高コントラストUI',showTips:'ゲームのヒントを表示',chat:'チャット',lobbyChat:'ロビーチャット',send:'送信',inventory:'インベントリ',crafting:'クラフト',armor:'防具',revive:'復活',dead:'ダウン',deposit:'納品',resources:'資源',currentZone:'現在地',help:'ヘルプ',back:'戻る',save:'保存',delete:'削除',newTemplate:'新しいテンプレート',uploadImage:'画像アップロード',watchAd:'広告を1回見て画像アップロードを解放',draw:'描画',stickers:'ステッカー',accountRequired:'進行状況とカスタマイズの保存にはログインが必要です。',roomBrowser:'公開ルーム',create:'作成',difficultyEasy:'簡単',difficultyNormal:'普通',difficultyHard:'難しい',host:'ホスト',you:'自分',spectating:'復活待機中',reviveCost:'復活コスト',depositHint:'採集物はHEARTまたは補給所へ運んで納品するとチーム資源になります。',craft2:'携帯クラフト · 2×2',craft3:'作業台 · 3×3',craft4:'大型作業台 · 4×4',username:'ユーザー名',password:'パスワード',credentialsRule:'ユーザー名3文字以上 / パスワード8文字以上',oauthPlanned:'Google・Discord連携は認証情報を設定すると有効化できます。',backendRequired:'アカウントサーバーに接続されていません。',clear:'クリア',templates:'テンプレート',noTemplates:'保存済みテンプレートはありません。',noRooms:'現在開いているルームはありません。',build:'建設',research:'研究',squad:'スクワッド',score:'スコア',wave:'ウェーブ',clickExpand:'クリックで拡大',gatherDeposit:'F · 採集 / 納品',locked:'ロック中',outOfBounds:'マップ外です',occupied:'使用済みスロットです',heartClearance:'HEARTに近すぎます',entityInSlot:'プレイヤーまたはモンスターがスロット内にいます',bankInsufficient:'保管資源が不足しています',playerNotFound:'プレイヤーが見つかりません',noRecipe:'一致するレシピがありません',inventoryFull:'インベントリがいっぱいです',incoming:'襲撃接近',recovery:'復旧フェーズ',overtime:'延長戦',heartLost:'HEART破壊',roomInfo:'ルーム · クイックプレイ · ロビー',accountInfo:'プロフィールと保存データ',customInfo:'描画 · ステッカー · テンプレート',settingsInfo:'言語 · 音量 · アクセシビリティ',uploadUnlocked:'画像アップロードを解放しました',adDev:'広告報酬ゲートは開発モードです。',roomSearch:'ルーム検索',allDifficulties:'すべての難易度',roomCode:'ルームコード',copy:'コピー',copied:'コピー済み',addAI:'AIプレイヤーを追加',removeAI:'AIを削除',aiPlayer:'AIプレイヤー',autoReady:'自動準備完了',leaveRoom:'ルーム退出',leaveWarn:'ルームから退出します。続けますか？',maxPlayers15:'最大人数は15人です。',startingIn:'ゲーム開始まで',cancel:'キャンセル',pause:'一時停止',paused:'一時停止中',resume:'再開',restart:'リスタート',returnLobby:'ロビーへ戻る',result:'結果',survivedWaves:'生存ウェーブ',waypoint:'ウェイポイント',clearWaypoint:'ウェイポイントを削除',tutorial:'フィールドガイド',tutorialMove:'移動して周囲の地形を確認しましょう。',tutorialGather:'近くの資源を採集し、ドロップを拾いましょう。',tutorialDeposit:'資源をHEARTか補給所へ運んで納品しましょう。',tutorialBuild:'ビルダーキットで防御・支援施設を配置しましょう。',tutorialResearch:'保管したクリスタルで要塞を研究強化しましょう。',tutorialChat:'チャットで連携できます。/w <プレイヤー> <メッセージ> でささやき可能です。',tips:'ヒント',tipRoles:'固定クラスはありません。採集・運搬・建設・偵察・防衛を自然に分担しましょう。',tipLogistics:'前線補給所で危険な長距離運搬を短縮できます。',tipOvertime:'残った敵をすべて倒すまでウェーブは終了しません。',
  res_wood:'木材',res_stone:'石材',res_fiber:'繊維',res_iron:'鉄',res_crystal:'クリスタル',res_quartz:'クォーツ',res_herb:'ハーブ',res_resin:'樹脂',res_scrap:'スクラップ',res_copper:'銅',zone_greenwood:'グリーンウッド',zone_stonefall:'ストーンフォール採石場',zone_crystalreach:'クリスタル・リーチ',zone_mire:'ヴァーダント湿地',zone_heartlands:'ハートランド',zone_scrapyard:'旧スクラップヤード',build_wall:'壁',build_generator:'発電機',build_relay:'修理リレー',build_depot:'補給所',item_fieldTool:'フィールドツール',item_surveyTool:'調査ツール',item_builderKit:'ビルダーキット',item_armorShell:'強化シェル',item_workbench:'作業台',item_grandWorkbench:'大型作業台',item_plank:'加工板',item_cord:'コード',item_metalPlate:'金属板',item_circuit:'回路',research_wallI:'強化壁 I',research_wallII:'強化壁 II',research_fortify:'構造強化',research_corePlating:'HEART装甲',research_powerGrid:'電力網',research_fieldRepair:'現地修理',research_logistics:'物流',research_rescue:'救助プロトコル',research_survey:'資源調査'
};

const ZH={
  play:'开始游戏',account:'账户',customize:'自定义',settings:'设置',login:'登录',signup:'注册',logout:'退出登录',deleteAccount:'删除账户',quickPlay:'快速加入',sameLanguage:'优先加入相同语言房间',createRoom:'创建房间',join:'加入',roomName:'房间名称',description:'说明',map:'地图',difficulty:'难度',players:'人数',ready:'准备完成',unready:'准备中',startGame:'开始游戏',waitingReady:'等待所有玩家准备',guest:'游客',volume:'音量',language:'语言',reducedMotion:'减少动态效果',highContrast:'高对比度界面',showTips:'显示游戏提示',chat:'聊天',lobbyChat:'房间聊天',send:'发送',inventory:'物品栏',crafting:'制作',armor:'护甲',revive:'复活',dead:'倒下',deposit:'存入',resources:'资源',currentZone:'当前区域',help:'帮助',back:'返回',save:'保存',delete:'删除',newTemplate:'新增模板',uploadImage:'上传图片',watchAd:'观看一次广告后解锁图片上传',draw:'绘制',stickers:'贴纸',accountRequired:'登录后才能保存进度与自定义内容。',roomBrowser:'开放房间',create:'创建',difficultyEasy:'简单',difficultyNormal:'普通',difficultyHard:'困难',host:'房主',you:'你',spectating:'等待复活',reviveCost:'复活费用',depositHint:'采集物必须运到HEART或补给站并存入后才会成为团队资源。',craft2:'便携制作 · 2×2',craft3:'工作台 · 3×3',craft4:'大型工作台 · 4×4',username:'用户名',password:'密码',credentialsRule:'用户名至少3个字符 / 密码至少8个字符',oauthPlanned:'配置认证信息后可启用Google和Discord关联。',backendRequired:'账户服务器未连接。',clear:'清除',templates:'模板',noTemplates:'没有已保存的模板。',noRooms:'当前没有开放房间。',build:'建造',research:'研究',squad:'小队',score:'分数',wave:'波次',clickExpand:'点击展开',gatherDeposit:'F · 采集 / 存入',locked:'未解锁',outOfBounds:'超出地图范围',occupied:'该格已被占用',heartClearance:'距离HEART太近',entityInSlot:'玩家或怪物占用了该格',bankInsufficient:'团队库存资源不足',playerNotFound:'找不到玩家',noRecipe:'没有匹配的配方',inventoryFull:'物品栏已满',incoming:'入侵接近',recovery:'恢复阶段',overtime:'加时',heartLost:'HEART已被摧毁',roomInfo:'房间 · 快速加入 · 大厅',accountInfo:'个人资料和保存进度',customInfo:'绘制 · 贴纸 · 模板',settingsInfo:'语言 · 音量 · 无障碍',uploadUnlocked:'图片上传已解锁',adDev:'广告奖励目前处于开发模式。',roomSearch:'搜索房间',allDifficulties:'全部难度',roomCode:'房间代码',copy:'复制',copied:'已复制',addAI:'添加AI玩家',removeAI:'移除AI',aiPlayer:'AI玩家',autoReady:'自动准备',leaveRoom:'离开房间',leaveWarn:'你将离开房间。是否继续？',maxPlayers15:'最大人数为15人。',startingIn:'距离游戏开始',cancel:'取消',pause:'暂停',paused:'已暂停',resume:'继续',restart:'重新开始',returnLobby:'返回大厅',result:'游戏结果',survivedWaves:'生存波次',waypoint:'导航点',clearWaypoint:'清除导航点',tutorial:'战地指南',tutorialMove:'移动并熟悉附近地形。',tutorialGather:'采集附近资源并拾取掉落物。',tutorialDeposit:'把资源运到HEART或补给站并存入。',tutorialBuild:'使用建造工具包布置防御和支援建筑。',tutorialResearch:'使用已存入的水晶研究并强化要塞。',tutorialChat:'使用聊天协作。输入 /w <玩家> <消息> 发送私聊。',tips:'提示',tipRoles:'没有固定职业。建议自然分工采集、运输、建造、侦察和防守。',tipLogistics:'前线补给站可以缩短危险的长途运输路线。',tipOvertime:'只要还有敌人存活，本波就不会结束。',
  res_wood:'木材',res_stone:'石材',res_fiber:'纤维',res_iron:'铁',res_crystal:'水晶',res_quartz:'石英',res_herb:'草药',res_resin:'树脂',res_scrap:'废料',res_copper:'铜',zone_greenwood:'绿林',zone_stonefall:'石瀑采石场',zone_crystalreach:'水晶之境',zone_mire:'翠绿沼泽',zone_heartlands:'核心地带',zone_scrapyard:'旧废料场',build_wall:'墙',build_generator:'发电机',build_relay:'维修中继站',build_depot:'补给站',item_fieldTool:'野外工具',item_surveyTool:'勘探工具',item_builderKit:'建造工具包',item_armorShell:'强化外壳',item_workbench:'工作台',item_grandWorkbench:'大型工作台',item_plank:'加工板材',item_cord:'绳索',item_metalPlate:'金属板',item_circuit:'电路',research_wallI:'强化墙 I',research_wallII:'强化墙 II',research_fortify:'结构加固',research_corePlating:'HEART装甲',research_powerGrid:'电网',research_fieldRepair:'现场维修',research_logistics:'物流',research_rescue:'救援协议',research_survey:'资源勘探'
};

export const STRINGS={en:{...EN},ko:{...EN,...KO},ja:{...EN,...JA},zh:{...EN,...ZH}};

export function createI18n(){
  let lang=detectLanguage();
  const apply=()=>{document.documentElement.lang=lang;localStorage.setItem('rbf.lang',lang)};
  apply();
  return{
    get lang(){return lang},
    set(next){if(!SUPPORTED_LANGUAGES.includes(next)||next===lang)return;lang=next;apply();window.dispatchEvent(new CustomEvent('rbf-language',{detail:{language:lang}}))},
    t(key){return STRINGS[lang]?.[key]??STRINGS.en[key]??key}
  };
}
